/****** Script for SelectTopNRows command from SSMS  ******/
SELECT [mailitem_id]
      ,[profile_id]
      ,[recipients]
      ,[copy_recipients]
      ,[blind_copy_recipients]
      ,[subject]
      ,[from_address]
      ,[reply_to]
      ,[body]
      ,[body_format]
      ,[importance]
      ,[sensitivity]
      ,[file_attachments]
      ,[attachment_encoding]
      ,[query]
      ,[execute_query_database]
      ,[attach_query_result_as_file]
      ,[query_result_header]
      ,[query_result_width]
      ,[query_result_separator]
      ,[exclude_query_output]
      ,[append_query_error]
      ,[send_request_date]
      ,[send_request_user]
      ,[sent_account_id]
      ,[sent_status]
      ,[sent_date]
      ,[last_mod_date]
      ,[last_mod_user]
  FROM [msdb].[dbo].[sysmail_mailitems]

ORDER BY [send_request_date] DESC