USE [master]
ALTER DATABASE [GlobalPayments] SET SINGLE_USER WITH ROLLBACK IMMEDIATE ;

RESTORE DATABASE [GlobalPayments] 
FROM  DISK = N'\\DBAMBK02PR\SQLBackup07\_GP_migration\GlobalPayments.BAK' 
WITH
 -- FILE = 1,  
	--NOUNLOAD,  
	REPLACE,  
	STATS = 5 ;

ALTER DATABASE [GlobalPayments] SET MULTI_USER ;
GO


USE [master]
ALTER DATABASE [GP.AccessControl] SET SINGLE_USER WITH ROLLBACK IMMEDIATE ;

RESTORE DATABASE [GP.AccessControl] 
FROM  DISK = N'\\DBAMBK02PR\SQLBackup07\_GP_migration\GP.AccessControl.BAK' 
WITH
 -- FILE = 1,  
	--NOUNLOAD,  
	REPLACE,  
	STATS = 5 ;

ALTER DATABASE [GP.AccessControl] SET MULTI_USER ;
GO


USE [master]
ALTER DATABASE [GP.Client] SET SINGLE_USER WITH ROLLBACK IMMEDIATE ;

RESTORE DATABASE [GP.Client] 
FROM  DISK = N'\\DBAMBK02PR\SQLBackup07\_GP_migration\GP.Client.BAK' 
WITH
 -- FILE = 1,  
	--NOUNLOAD,  
	REPLACE,  
	STATS = 5 ;

ALTER DATABASE [GP.Client] SET MULTI_USER ;
GO


USE [master]
ALTER DATABASE [GP.Logs] SET SINGLE_USER WITH ROLLBACK IMMEDIATE ;

RESTORE DATABASE [GP.Logs] 
FROM  DISK = N'\\DBAMBK02PR\SQLBackup07\_GP_migration\GP.Logs.BAK' 
WITH
 -- FILE = 1,  
	--NOUNLOAD,  
	REPLACE,  
	STATS = 5 ;

ALTER DATABASE [GP.Logs] SET MULTI_USER ;
GO


USE [master]
ALTER DATABASE [GP.Reporting] SET SINGLE_USER WITH ROLLBACK IMMEDIATE ;

RESTORE DATABASE [GP.Reporting] 
FROM  DISK = N'\\DBAMBK02PR\SQLBackup07\_GP_migration\GP.Reporting.BAK' 
WITH
 -- FILE = 1,  
	--NOUNLOAD,  
	REPLACE,  
	STATS = 5 ;

ALTER DATABASE [GP.Reporting] SET MULTI_USER ;
GO


USE [master]
ALTER DATABASE [gp_kiosk_server] SET SINGLE_USER WITH ROLLBACK IMMEDIATE ;

RESTORE DATABASE [gp_kiosk_server] 
FROM  DISK = N'\\DBAMBK02PR\SQLBackup07\_GP_migration\gp_kiosk_server.BAK' 
WITH
 -- FILE = 1,  
	--NOUNLOAD,  
	REPLACE,  
	STATS = 5 ;

ALTER DATABASE [gp_kiosk_server] SET MULTI_USER ;
GO

