USE MASTER
GO

--DROP DATABASE CMKTIMPORT10
--GO

RESTORE FILELISTONLY FROM
DISK =  
 'R:\Program Files\Microsoft SQL Server\MSSQL.1\MSSQL\Backup\CMKTIMPORT_backup_201606060330.bak'
GO

RESTORE DATABASE CMKTIMPORT10_TEST FROM
 DISK = 'R:\Program Files\Microsoft SQL Server\MSSQL.1\MSSQL\Backup\CMKTIMPORT_backup_201606060330.bak'
WITH
 MOVE 'CMKTIMPORT'     TO 'J:\UserDBdata2\CMKTIMPORT10_TEST_data.mdf'
,MOVE 'CMKTIMPORT_log' TO 'L:\UserDBlog\CMKTIMPORT10_TEST_log.ldf'

,STATS = 5
GO
