USE [master]
RESTORE DATABASE [CMKTDB10_FINAL2] FROM  
 DISK = '\\CMKTDB01PR\SQLBackup\CMKTDB01PR_CMKTDB_1.bak'
,DISK = '\\CMKTDB01PR\SQLBackup\CMKTDB01PR_CMKTDB_2.bak'
,DISK = '\\CMKTDB01PR\SQLBackup\CMKTDB01PR_CMKTDB_3.bak' 
WITH  
 FILE = 1
,MOVE N'CMktDB'     TO N'R:\UserDBdataTemp\CMKTDB10_FINAL2_data.mdf'
,MOVE N'CMKTDB_2'   TO N'R:\UserDBdataTemp\CMKTDB10_FINAL2_data2.ndf'
,MOVE N'CMKTDB_3'   TO N'R:\UserDBdataTemp\CMKTDB10_FINAL2_data3.ndf'
,MOVE N'CMKTDB_4'   TO N'R:\UserDBdataTemp\CMKTDB10_FINAL2_data4.ndf'
,MOVE N'CMKTDB_5'   TO N'R:\UserDBdataTemp\CMKTDB10_FINAL2_data5.ndf'
,MOVE N'CMKTDB_6'   TO N'K:\UserDBdataTemp\CMKTDB10_FINAL2_data6.ndf'
,MOVE N'CMKTDB_7'   TO N'K:\UserDBdataTemp\CMKTDB10_FINAL2_data7.ndf'
,MOVE N'CMKTDB_8'   TO N'K:\UserDBdataTemp\CMKTDB10_FINAL2_data8.ndf'
,MOVE N'CMktDB_log' TO N'R:\UserDBlogTemp\CMKTDB10_FINAL2_log.ldf'
,NOUNLOAD
,NORECOVERY
,STATS = 5
GO

USE [master]
RESTORE DATABASE [CMKTDB10_FINAL2] FROM  
 DISK = '\\CMKTDB01PR\SQLBackup\CMKTDB01PR_CMKTDB.DIF'
WITH  
 FILE = 1
,MOVE N'CMktDB' TO N'R:\UserDBdataTemp\CMKTDB10_FINAL2_data.mdf'
,MOVE N'CMKTDB_2' TO N'R:\UserDBdataTemp\CMKTDB10_FINAL2_data2.ndf'
,MOVE N'CMKTDB_3' TO N'R:\UserDBdataTemp\CMKTDB10_FINAL2_data3.ndf'
,MOVE N'CMKTDB_4' TO N'R:\UserDBdataTemp\CMKTDB10_FINAL2_data4.ndf'
,MOVE N'CMKTDB_5' TO N'R:\UserDBdataTemp\CMKTDB10_FINAL2_data5.ndf'
,MOVE N'CMKTDB_6' TO N'K:\UserDBdataTemp\CMKTDB10_FINAL2_data6.ndf'
,MOVE N'CMKTDB_7' TO N'K:\UserDBdataTemp\CMKTDB10_FINAL2_data7.ndf'
,MOVE N'CMKTDB_8' TO N'K:\UserDBdataTemp\CMKTDB10_FINAL2_data8.ndf'
,MOVE N'CMktDB_log' TO N'R:\UserDBlogTemp\CMKTDB10_FINAL2_log.ldf'
,NOUNLOAD
,RECOVERY
,STATS = 5
GO