USE MASTER
GO

--DROP DATABASE CMKTCRYPTO10
--GO

RESTORE FILELISTONLY FROM
DISK = 'R:\Program Files\Microsoft SQL Server\MSSQL.1\MSSQL\Backup\CMKTCRYPTO_backup_201606060330.bak'
GO

RESTORE DATABASE CMKTCRYPTO10_TEST FROM
DISK = 'R:\Program Files\Microsoft SQL Server\MSSQL.1\MSSQL\Backup\CMKTCRYPTO_backup_201606060330.bak'
WITH
 MOVE 'CMKTCRYPTO'     TO 'J:\UserDBdata2\CMKTCRYPTO10_TEST_data.mdf'
,MOVE 'CMKTCRYPTO_log' TO 'L:\UserDBlog\CMKTCRYPTO10_TEST_log.ldf'

,STATS = 5
GO
