USE [master]
RESTORE DATABASE [CMKTDB10_TEST] FROM  
 DISK = 'R:\Program Files\Microsoft SQL Server\MSSQL.1\MSSQL\Backup\CMKTDB01PR_CMKTDB.DIF'
WITH  
 FILE = 1
,MOVE N'CMktDB' TO N'J:\UserDBdata2\CMKTDB10_TEST_data.mdf'
,MOVE N'CMKTDB_2' TO N'J:\UserDBdata2\CMKTDB10_data_TEST_2.ndf'
,MOVE N'CMKTDB_3' TO N'J:\UserDBdata2\CMKTDB10_data_TEST_3.ndf'
,MOVE N'CMKTDB_4' TO N'J:\UserDBdata2\CMKTDB10_data_TEST_4.ndf'
,MOVE N'CMKTDB_5' TO N'J:\UserDBdata2\CMKTDB10_data_TEST_5.ndf'
,MOVE N'CMKTDB_6' TO N'J:\UserDBdata2\CMKTDB10_data_TEST_6.ndf'
,MOVE N'CMKTDB_7' TO N'J:\UserDBdata2\CMKTDB10_data_TEST_7.ndf'
,MOVE N'CMKTDB_8' TO N'J:\UserDBdata2\CMKTDB10_data_TEST_8.ndf'
,MOVE N'CMktDB_log' TO N'L:\UserDBlog\CMKTDB10_TEST_log.ldf'
,NOUNLOAD
,RECOVERY
,STATS = 5
GO
