SELECT *
INTO [SDSVJPRD_Restores].[dbo].[SDT_MESSAGE_0531]
FROM [SDSVJPRD_mnt_0531].[SDT].[MESSAGE]
GO

SELECT *
INTO [SDSVJPRD_Restores].[dbo].[TRANSACTION_MASTER_0531]
FROM [SDSVJPRD_mnt_0531].[TRANSACTION].[TRANSACTION_MASTER]
GO

SELECT *
INTO [SDSVJPRD_Restores].[dbo].[TRANSACTION_MASTER_0620]
FROM [SDSVJPRD_mnt_0620].[TRANSACTION].[TRANSACTION_MASTER]
GO

SELECT *
INTO [SDSVJPRD_Restores].[dbo].[SDT_MESSAGE_0620]
FROM [SDSVJPRD_mnt_0620].[SDT].[MESSAGE]
GO

SELECT *
INTO [SDSVJPRD_Restores].[dbo].[TRANSACTION_MASTER_0715]
FROM [SDSVJPRD_mnt_0715].[TRANSACTION].[TRANSACTION_MASTER]
GO

SELECT *
INTO [SDSVJPRD_Restores].[dbo].[SDT_MESSAGE_0715]
FROM [SDSVJPRD_mnt_0715].[SDT].[MESSAGE]
GO