 SELECT 
   RQLOC.NAME
 , REQLINE.PURCH_MAJOR
 , RQLOC.REQ_LOCATION
 , REQLINE.ITEM
 , REQLINE.[DESCRIPTION]
 , REQLINE.ENTERED_UOM
 , WHSHIPLINE.UNIT_COST
 , WHSHIPLINE.SHIPPED_QTY
 , WHSHIPMENT.SHIP_DATE
 , REQLINE.REQ_NUMBER 
 
 FROM Prod.lawson.RQLOC RQLOC 

 INNER JOIN Prod.lawson.WHSHIPMENT WHSHIPMENT 
    ON RQLOC.COMPANY=WHSHIPMENT.COMPANY 
   AND RQLOC.REQ_LOCATION=WHSHIPMENT.REQ_LOCATION 

INNER JOIN Prod.lawson.WHSHIPLINE WHSHIPLINE 
   ON WHSHIPMENT.COMPANY=WHSHIPLINE.COMPANY 
  AND WHSHIPMENT.SYSTEM_CD=WHSHIPLINE.SYSTEM_CD 
  AND WHSHIPMENT.DOC_NBR=WHSHIPLINE.DOC_NBR 

INNER JOIN Prod.lawson.REQLINE REQLINE 
   ON WHSHIPLINE.COMPANY=REQLINE.COMPANY 
  AND WHSHIPLINE.DOC_NBR=REQLINE.REQ_NUMBER_A 
  AND WHSHIPLINE.LINE_NBR=REQLINE.LINE_NBR 

WHERE REQLINE.PURCH_MAJOR >= '000' 
  AND REQLINE.PURCH_MAJOR <= '999' 
  AND WHSHIPMENT.SHIP_DATE >= '2016-03-28 00:00:00' 
  AND WHSHIPMENT.SHIP_DATE < '2016-03-29 00:00:00' 

ORDER BY 
  RQLOC.REQ_LOCATION
, REQLINE.PURCH_MAJOR