USE [master] 
IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = N'VIEJAS\LWSNDB02PR$')
BEGIN
DECLARE @CreateError INT
CREATE LOGIN [VIEJAS\LWSNDB02PR$] FROM WINDOWS
SET @CreateError = @@ERROR


GRANT CONNECT SQL TO [VIEJAS\LWSNDB02PR$] 


------USE [ReportServer]
------IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'VIEJAS\LWSNDB02PR$')
------CREATE USER [VIEJAS\LWSNDB02PR$] FOR LOGIN [VIEJAS\LWSNDB02PR$] WITH DEFAULT_SCHEMA=[VIEJAS\LWSNDB02PR$]

------IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'RSExecRole' AND type = 'R')
------BEGIN
------CREATE ROLE [RSExecRole] AUTHORIZATION [dbo]
------GRANT DELETE ON [dbo].[ActiveSubscriptions]  TO [RSExecRole] 
------GRANT INSERT ON [dbo].[ActiveSubscriptions]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[ActiveSubscriptions]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[ActiveSubscriptions]  TO [RSExecRole] 
------GRANT UPDATE ON [dbo].[ActiveSubscriptions]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[AddBatchRecord]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[AddDataSet]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[AddDataSource]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[AddEvent]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[AddExecutionLogEntry]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[AddHistoryRecord]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[AddModelPerspective]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[AddPersistedStream]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[AddReportSchedule]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[AddReportToCache]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[AddRunningJob]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[AddSubscriptionToBeingDeleted]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[AnnounceOrGetKey]  TO [RSExecRole] 
------GRANT DELETE ON [dbo].[Batch]  TO [RSExecRole] 
------GRANT INSERT ON [dbo].[Batch]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[Batch]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[Batch]  TO [RSExecRole] 
------GRANT UPDATE ON [dbo].[Batch]  TO [RSExecRole] 
------GRANT DELETE ON [dbo].[CachePolicy]  TO [RSExecRole] 
------GRANT INSERT ON [dbo].[CachePolicy]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[CachePolicy]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[CachePolicy]  TO [RSExecRole] 
------GRANT UPDATE ON [dbo].[CachePolicy]  TO [RSExecRole] 
------GRANT DELETE ON [dbo].[Catalog]  TO [RSExecRole] 
------GRANT INSERT ON [dbo].[Catalog]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[Catalog]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[Catalog]  TO [RSExecRole] 
------GRANT UPDATE ON [dbo].[Catalog]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[ChangeStateOfDataSource]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[CheckSessionLock]  TO [RSExecRole] 
------GRANT DELETE ON [dbo].[ChunkData]  TO [RSExecRole] 
------GRANT INSERT ON [dbo].[ChunkData]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[ChunkData]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[ChunkData]  TO [RSExecRole] 
------GRANT UPDATE ON [dbo].[ChunkData]  TO [RSExecRole] 
------GRANT DELETE ON [dbo].[ChunkSegmentMapping]  TO [RSExecRole] 
------GRANT INSERT ON [dbo].[ChunkSegmentMapping]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[ChunkSegmentMapping]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[ChunkSegmentMapping]  TO [RSExecRole] 
------GRANT UPDATE ON [dbo].[ChunkSegmentMapping]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[CleanAllHistories]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[CleanBatchRecords]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[CleanBrokenSnapshots]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[CleanEventRecords]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[CleanExpiredCache]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[CleanExpiredEditSessions]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[CleanExpiredJobs]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[CleanExpiredServerParameters]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[CleanExpiredSessions]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[CleanHistoryForReport]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[CleanNotificationRecords]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[CleanOrphanedPolicies]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[CleanOrphanedSnapshots]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[ClearScheduleConsistancyFlags]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[ClearSessionSnapshot]  TO [RSExecRole] 
------GRANT DELETE ON [dbo].[ConfigurationInfo]  TO [RSExecRole] 
------GRANT INSERT ON [dbo].[ConfigurationInfo]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[ConfigurationInfo]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[ConfigurationInfo]  TO [RSExecRole] 
------GRANT UPDATE ON [dbo].[ConfigurationInfo]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[CopyChunks]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[CopyChunksOfType]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[CreateCacheUpdateNotifications]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[CreateChunkAndGetPointer]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[CreateChunkSegment]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[CreateDataDrivenNotification]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[CreateEditSession]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[CreateNewActiveSubscription]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[CreateNewSnapshotVersion]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[CreateObject]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[CreateRdlChunk]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[CreateRole]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[CreateSegmentedChunk]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[CreateSession]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[CreateSnapShotNotifications]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[CreateSubscription]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[CreateTask]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[CreateTimeBasedSubscriptionNotification]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[CreateTimeBasedSubscriptionSchedule]  TO [RSExecRole] 
------GRANT DELETE ON [dbo].[DataSets]  TO [RSExecRole] 
------GRANT INSERT ON [dbo].[DataSets]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[DataSets]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[DataSets]  TO [RSExecRole] 
------GRANT UPDATE ON [dbo].[DataSets]  TO [RSExecRole] 
------GRANT DELETE ON [dbo].[DataSource]  TO [RSExecRole] 
------GRANT INSERT ON [dbo].[DataSource]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[DataSource]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[DataSource]  TO [RSExecRole] 
------GRANT UPDATE ON [dbo].[DataSource]  TO [RSExecRole] 
------GRANT DELETE ON [dbo].[DBUpgradeHistory]  TO [RSExecRole] 
------GRANT INSERT ON [dbo].[DBUpgradeHistory]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[DBUpgradeHistory]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[DBUpgradeHistory]  TO [RSExecRole] 
------GRANT UPDATE ON [dbo].[DBUpgradeHistory]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[DecreaseTransientSnapshotRefcount]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[DeepCopySegment]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[DeleteActiveSubscription]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[DeleteAllHistoryForReport]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[DeleteAllModelItemPolicies]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[DeleteBatchRecords]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[DeleteDataSets]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[DeleteDataSources]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[DeleteDrillthroughReports]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[DeleteEncryptedContent]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[DeleteEvent]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[DeleteExpiredPersistedStreams]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[DeleteHistoriesWithNoPolicy]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[DeleteHistoryRecord]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[DeleteKey]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[DeleteModelItemPolicy]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[DeleteModelPerspectives]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[DeleteNotification]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[DeleteObject]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[DeleteOneChunk]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[DeletePersistedStream]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[DeletePersistedStreams]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[DeletePolicy]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[DeleteReportSchedule]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[DeleteRole]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[DeleteSnapshotAndChunks]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[DeleteSubscription]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[DeleteTask]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[DeleteTimeBasedSubscriptionSchedule]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[DeliveryRemovedInactivateSubscription]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[DereferenceSessionSnapshot]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[EnforceCacheLimits]  TO [RSExecRole] 
------GRANT DELETE ON [dbo].[Event]  TO [RSExecRole] 
------GRANT INSERT ON [dbo].[Event]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[Event]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[Event]  TO [RSExecRole] 
------GRANT UPDATE ON [dbo].[Event]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[ExecutionLog]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[ExecutionLog]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[ExecutionLog2]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[ExecutionLog2]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[ExecutionLog3]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[ExecutionLog3]  TO [RSExecRole] 
------GRANT DELETE ON [dbo].[ExecutionLogStorage]  TO [RSExecRole] 
------GRANT INSERT ON [dbo].[ExecutionLogStorage]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[ExecutionLogStorage]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[ExecutionLogStorage]  TO [RSExecRole] 
------GRANT UPDATE ON [dbo].[ExecutionLogStorage]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[ExpireExecutionLogEntries]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[ExtendedCatalog]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[ExtendedCatalog]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[ExtendedDataSets]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[ExtendedDataSets]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[ExtendedDataSources]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[ExtendedDataSources]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[FindItemsByDataSet]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[FindItemsByDataSource]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[FindItemsByDataSourceRecursive]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[FindObjectsByLink]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[FindObjectsNonRecursive]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[FindObjectsRecursive]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[FindParents]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[FlushCacheByID]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[FlushReportFromCache]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[Get_sqlagent_job_status]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetAllConfigurationInfo]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetAllProperties]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetAnnouncedKey]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetAReportsReportAction]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetBatchRecords]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetCacheOptions]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetCacheSchedule]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetChildrenBeforeDelete]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetChunkInformation]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetChunkPointerAndLength]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetCompiledDefinition]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetDataSetForExecution]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetDataSets]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetDataSourceForUpgrade]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetDatasourceInfoForReencryption]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetDataSources]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetDBVersion]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetDrillthroughReport]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetDrillthroughReports]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetExecutionOptions]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetFirstPortionPersistedStream]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetIDPairsByLink]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetModelDefinition]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetModelItemInfo]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetModelPerspectives]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetModelsAndPerspectives]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetMyRunningJobs]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetNameById]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetNextPortionPersistedStream]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetObjectContent]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetOneConfigurationInfo]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetParameters]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetPoliciesForRole]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetPolicy]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetPolicyRoots]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetPrincipalID]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetReportForExecution]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetReportParametersForExecution]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetRoles]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetSchedulesReports]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetServerParameters]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetSessionData]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetSharePointPathsForUpgrade]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetSharePointSchedulePathsForUpgrade]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetSnapshotChunks]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetSnapshotFromHistory]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetSnapshotPromotedInfo]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetSnapShotSchedule]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetSubscription]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetSubscriptionInfoForReencryption]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetSubscriptionsForUpgrade]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetSystemPolicy]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetTaskProperties]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetTimeBasedSubscriptionReportAction]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetTimeBasedSubscriptionSchedule]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetUpgradeItems]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetUserID]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetUserIDByName]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetUserIDBySid]  TO [RSExecRole] 
------GRANT DELETE ON [dbo].[History]  TO [RSExecRole] 
------GRANT INSERT ON [dbo].[History]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[History]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[History]  TO [RSExecRole] 
------GRANT UPDATE ON [dbo].[History]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[IncreaseTransientSnapshotRefcount]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[InsertUnreferencedSnapshot]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[InvalidateSubscription]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[IsSegmentedChunk]  TO [RSExecRole] 
------GRANT DELETE ON [dbo].[Keys]  TO [RSExecRole] 
------GRANT INSERT ON [dbo].[Keys]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[Keys]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[Keys]  TO [RSExecRole] 
------GRANT UPDATE ON [dbo].[Keys]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[ListHistory]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[ListInfoForReencryption]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[ListInstallations]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[ListRunningJobs]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[ListScheduledReports]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[ListSubscriptionIDs]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[ListSubscriptionsUsingDataSource]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[ListTasks]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[ListTasksForMaintenance]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[ListUsedDeliveryProviders]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[LoadForDefinitionCheck]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[LoadForRepublishing]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[LockPersistedStream]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[LockSnapshotForUpgrade]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[MarkSnapshotAsDependentOnUser]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[MigrateExecutionLog]  TO [RSExecRole] 
------GRANT DELETE ON [dbo].[ModelDrill]  TO [RSExecRole] 
------GRANT INSERT ON [dbo].[ModelDrill]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[ModelDrill]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[ModelDrill]  TO [RSExecRole] 
------GRANT UPDATE ON [dbo].[ModelDrill]  TO [RSExecRole] 
------GRANT DELETE ON [dbo].[ModelPerspective]  TO [RSExecRole] 
------GRANT INSERT ON [dbo].[ModelPerspective]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[ModelPerspective]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[ModelPerspective]  TO [RSExecRole] 
------GRANT UPDATE ON [dbo].[ModelPerspective]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[MoveObject]  TO [RSExecRole] 
------GRANT DELETE ON [dbo].[Notifications]  TO [RSExecRole] 
------GRANT INSERT ON [dbo].[Notifications]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[Notifications]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[Notifications]  TO [RSExecRole] 
------GRANT UPDATE ON [dbo].[Notifications]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[ObjectExists]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[OpenSegmentedChunk]  TO [RSExecRole] 
------GRANT DELETE ON [dbo].[Policies]  TO [RSExecRole] 
------GRANT INSERT ON [dbo].[Policies]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[Policies]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[Policies]  TO [RSExecRole] 
------GRANT UPDATE ON [dbo].[Policies]  TO [RSExecRole] 
------GRANT DELETE ON [dbo].[PolicyUserRole]  TO [RSExecRole] 
------GRANT INSERT ON [dbo].[PolicyUserRole]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[PolicyUserRole]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[PolicyUserRole]  TO [RSExecRole] 
------GRANT UPDATE ON [dbo].[PolicyUserRole]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[PromoteSnapshotInfo]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[ReadChunkPortion]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[ReadChunkSegment]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[ReadRoleProperties]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[RebindDataSet]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[RebindDataSource]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[RemoveReportFromSession]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[RemoveRunningJob]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[RemoveSegment]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[RemoveSegmentedMapping]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[RemoveSubscriptionFromBeingDeleted]  TO [RSExecRole] 
------GRANT DELETE ON [dbo].[ReportSchedule]  TO [RSExecRole] 
------GRANT INSERT ON [dbo].[ReportSchedule]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[ReportSchedule]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[ReportSchedule]  TO [RSExecRole] 
------GRANT UPDATE ON [dbo].[ReportSchedule]  TO [RSExecRole] 
------GRANT DELETE ON [dbo].[Roles]  TO [RSExecRole] 
------GRANT INSERT ON [dbo].[Roles]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[Roles]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[Roles]  TO [RSExecRole] 
------GRANT UPDATE ON [dbo].[Roles]  TO [RSExecRole] 
------GRANT DELETE ON [dbo].[RunningJobs]  TO [RSExecRole] 
------GRANT INSERT ON [dbo].[RunningJobs]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[RunningJobs]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[RunningJobs]  TO [RSExecRole] 
------GRANT UPDATE ON [dbo].[RunningJobs]  TO [RSExecRole] 
------GRANT DELETE ON [dbo].[Schedule]  TO [RSExecRole] 
------GRANT INSERT ON [dbo].[Schedule]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[Schedule]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[Schedule]  TO [RSExecRole] 
------GRANT UPDATE ON [dbo].[Schedule]  TO [RSExecRole] 
------GRANT DELETE ON [dbo].[SecData]  TO [RSExecRole] 
------GRANT INSERT ON [dbo].[SecData]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[SecData]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[SecData]  TO [RSExecRole] 
------GRANT UPDATE ON [dbo].[SecData]  TO [RSExecRole] 
------GRANT DELETE ON [dbo].[Segment]  TO [RSExecRole] 
------GRANT INSERT ON [dbo].[Segment]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[Segment]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[Segment]  TO [RSExecRole] 
------GRANT UPDATE ON [dbo].[Segment]  TO [RSExecRole] 
------GRANT DELETE ON [dbo].[SegmentedChunk]  TO [RSExecRole] 
------GRANT INSERT ON [dbo].[SegmentedChunk]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[SegmentedChunk]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[SegmentedChunk]  TO [RSExecRole] 
------GRANT UPDATE ON [dbo].[SegmentedChunk]  TO [RSExecRole] 
------GRANT DELETE ON [dbo].[ServerUpgradeHistory]  TO [RSExecRole] 
------GRANT INSERT ON [dbo].[ServerUpgradeHistory]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[ServerUpgradeHistory]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[ServerUpgradeHistory]  TO [RSExecRole] 
------GRANT UPDATE ON [dbo].[ServerUpgradeHistory]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[SetAllProperties]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[SetCacheLastUsed]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[SetCacheOptions]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[SetConfigurationInfo]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[SetDrillthroughReports]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[SetExecutionOptions]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[SetHistoryLimit]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[SetKeysForInstallation]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[SetLastModified]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[SetMachineName]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[SetModelItemPolicy]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[SetNotificationAttempt]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[SetObjectContent]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[SetParameters]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[SetPersistedStreamError]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[SetPolicy]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[SetReencryptedDatasourceInfo]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[SetReencryptedSubscriptionInfo]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[SetRoleProperties]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[SetSessionCredentials]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[SetSessionData]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[SetSessionParameters]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[SetSnapshotChunksVersion]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[SetSnapshotProcessingFlags]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[SetSystemPolicy]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[SetUpgradeItemStatus]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[ShallowCopyChunk]  TO [RSExecRole] 
------GRANT DELETE ON [dbo].[SnapshotData]  TO [RSExecRole] 
------GRANT INSERT ON [dbo].[SnapshotData]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[SnapshotData]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[SnapshotData]  TO [RSExecRole] 
------GRANT UPDATE ON [dbo].[SnapshotData]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[StoreServerParameters]  TO [RSExecRole] 
------GRANT DELETE ON [dbo].[Subscriptions]  TO [RSExecRole] 
------GRANT INSERT ON [dbo].[Subscriptions]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[Subscriptions]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[Subscriptions]  TO [RSExecRole] 
------GRANT UPDATE ON [dbo].[Subscriptions]  TO [RSExecRole] 
------GRANT DELETE ON [dbo].[SubscriptionsBeingDeleted]  TO [RSExecRole] 
------GRANT INSERT ON [dbo].[SubscriptionsBeingDeleted]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[SubscriptionsBeingDeleted]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[SubscriptionsBeingDeleted]  TO [RSExecRole] 
------GRANT UPDATE ON [dbo].[SubscriptionsBeingDeleted]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[TempChunkExists]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[UpdateActiveSubscription]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[UpdatePolicy]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[UpdatePolicyPrincipal]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[UpdatePolicyRole]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[UpdateRunningJob]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[UpdateScheduleNextRunTime]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[UpdateSnapshot]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[UpdateSnapshotPaginationInfo]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[UpdateSnapshotReferences]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[UpdateSubscription]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[UpdateSubscriptionLastRunInfo]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[UpdateSubscriptionStatus]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[UpdateTask]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[UpgradeSharePointPaths]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[UpgradeSharePointSchedulePaths]  TO [RSExecRole] 
------GRANT DELETE ON [dbo].[Users]  TO [RSExecRole] 
------GRANT INSERT ON [dbo].[Users]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[Users]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[Users]  TO [RSExecRole] 
------GRANT UPDATE ON [dbo].[Users]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[WriteChunkPortion]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[WriteChunkSegment]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[WriteFirstPortionPersistedStream]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[WriteLockSession]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[WriteNextPortionPersistedStream]  TO [RSExecRole] 
------END

------IF EXISTS (SELECT * FROM sys.database_principals WHERE name = N'RSExecRole' AND type = 'R')
------EXEC sp_addrolemember N'RSExecRole', N'VIEJAS\LWSNDB02PR$'

------IF EXISTS (SELECT * FROM sys.database_principals WHERE name = N'db_owner' AND type = 'R')
------EXEC sp_addrolemember N'db_owner', N'VIEJAS\LWSNDB02PR$'



------USE [ReportServerTempDB]
------IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'VIEJAS\LWSNDB02PR$')
------CREATE USER [VIEJAS\LWSNDB02PR$] FOR LOGIN [VIEJAS\LWSNDB02PR$] WITH DEFAULT_SCHEMA=[VIEJAS\LWSNDB02PR$]

------IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'RSExecRole' AND type = 'R')
------BEGIN
------CREATE ROLE [RSExecRole] AUTHORIZATION [dbo]
------GRANT DELETE ON [dbo].[ChunkData]  TO [RSExecRole] 
------GRANT INSERT ON [dbo].[ChunkData]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[ChunkData]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[ChunkData]  TO [RSExecRole] 
------GRANT UPDATE ON [dbo].[ChunkData]  TO [RSExecRole] 
------GRANT DELETE ON [dbo].[ChunkSegmentMapping]  TO [RSExecRole] 
------GRANT INSERT ON [dbo].[ChunkSegmentMapping]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[ChunkSegmentMapping]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[ChunkSegmentMapping]  TO [RSExecRole] 
------GRANT UPDATE ON [dbo].[ChunkSegmentMapping]  TO [RSExecRole] 
------GRANT DELETE ON [dbo].[DBUpgradeHistory]  TO [RSExecRole] 
------GRANT INSERT ON [dbo].[DBUpgradeHistory]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[DBUpgradeHistory]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[DBUpgradeHistory]  TO [RSExecRole] 
------GRANT UPDATE ON [dbo].[DBUpgradeHistory]  TO [RSExecRole] 
------GRANT DELETE ON [dbo].[ExecutionCache]  TO [RSExecRole] 
------GRANT INSERT ON [dbo].[ExecutionCache]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[ExecutionCache]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[ExecutionCache]  TO [RSExecRole] 
------GRANT UPDATE ON [dbo].[ExecutionCache]  TO [RSExecRole] 
------GRANT EXECUTE ON [dbo].[GetDBVersion]  TO [RSExecRole] 
------GRANT DELETE ON [dbo].[PersistedStream]  TO [RSExecRole] 
------GRANT INSERT ON [dbo].[PersistedStream]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[PersistedStream]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[PersistedStream]  TO [RSExecRole] 
------GRANT UPDATE ON [dbo].[PersistedStream]  TO [RSExecRole] 
------GRANT DELETE ON [dbo].[Segment]  TO [RSExecRole] 
------GRANT INSERT ON [dbo].[Segment]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[Segment]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[Segment]  TO [RSExecRole] 
------GRANT UPDATE ON [dbo].[Segment]  TO [RSExecRole] 
------GRANT DELETE ON [dbo].[SegmentedChunk]  TO [RSExecRole] 
------GRANT INSERT ON [dbo].[SegmentedChunk]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[SegmentedChunk]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[SegmentedChunk]  TO [RSExecRole] 
------GRANT UPDATE ON [dbo].[SegmentedChunk]  TO [RSExecRole] 
------GRANT DELETE ON [dbo].[SessionData]  TO [RSExecRole] 
------GRANT INSERT ON [dbo].[SessionData]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[SessionData]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[SessionData]  TO [RSExecRole] 
------GRANT UPDATE ON [dbo].[SessionData]  TO [RSExecRole] 
------GRANT DELETE ON [dbo].[SessionLock]  TO [RSExecRole] 
------GRANT INSERT ON [dbo].[SessionLock]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[SessionLock]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[SessionLock]  TO [RSExecRole] 
------GRANT UPDATE ON [dbo].[SessionLock]  TO [RSExecRole] 
------GRANT DELETE ON [dbo].[SnapshotData]  TO [RSExecRole] 
------GRANT INSERT ON [dbo].[SnapshotData]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[SnapshotData]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[SnapshotData]  TO [RSExecRole] 
------GRANT UPDATE ON [dbo].[SnapshotData]  TO [RSExecRole] 
------GRANT DELETE ON [dbo].[TempCatalog]  TO [RSExecRole] 
------GRANT INSERT ON [dbo].[TempCatalog]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[TempCatalog]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[TempCatalog]  TO [RSExecRole] 
------GRANT UPDATE ON [dbo].[TempCatalog]  TO [RSExecRole] 
------GRANT DELETE ON [dbo].[TempDataSets]  TO [RSExecRole] 
------GRANT INSERT ON [dbo].[TempDataSets]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[TempDataSets]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[TempDataSets]  TO [RSExecRole] 
------GRANT UPDATE ON [dbo].[TempDataSets]  TO [RSExecRole] 
------GRANT DELETE ON [dbo].[TempDataSources]  TO [RSExecRole] 
------GRANT INSERT ON [dbo].[TempDataSources]  TO [RSExecRole] 
------GRANT REFERENCES ON [dbo].[TempDataSources]  TO [RSExecRole] 
------GRANT SELECT ON [dbo].[TempDataSources]  TO [RSExecRole] 
------GRANT UPDATE ON [dbo].[TempDataSources]  TO [RSExecRole] 
------END

------IF EXISTS (SELECT * FROM sys.database_principals WHERE name = N'RSExecRole' AND type = 'R')
------EXEC sp_addrolemember N'RSExecRole', N'VIEJAS\LWSNDB02PR$'

------IF EXISTS (SELECT * FROM sys.database_principals WHERE name = N'db_owner' AND type = 'R')
------EXEC sp_addrolemember N'db_owner', N'VIEJAS\LWSNDB02PR$'



------USE [master]
------IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'VIEJAS\LWSNDB02PR$')
------CREATE USER [VIEJAS\LWSNDB02PR$] FOR LOGIN [VIEJAS\LWSNDB02PR$] WITH DEFAULT_SCHEMA=[VIEJAS\LWSNDB02PR$]

------IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'RSExecRole' AND type = 'R')
------BEGIN
------CREATE ROLE [RSExecRole] AUTHORIZATION [dbo]
------GRANT EXECUTE ON [sys].[xp_sqlagent_enum_jobs]  TO [RSExecRole] 
------GRANT EXECUTE ON [sys].[xp_sqlagent_is_starting]  TO [RSExecRole] 
------GRANT EXECUTE ON [sys].[xp_sqlagent_notify]  TO [RSExecRole] 
------END

------IF EXISTS (SELECT * FROM sys.database_principals WHERE name = N'RSExecRole' AND type = 'R')
------EXEC sp_addrolemember N'RSExecRole', N'VIEJAS\LWSNDB02PR$'



USE [msdb]
IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'VIEJAS\LWSNDB02PR$')
CREATE USER [VIEJAS\LWSNDB02PR$] FOR LOGIN [VIEJAS\LWSNDB02PR$] WITH DEFAULT_SCHEMA=[VIEJAS\LWSNDB02PR$]

IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'SQLAgentUserRole' AND type = 'R')
BEGIN
CREATE ROLE [SQLAgentUserRole] AUTHORIZATION [dbo]
GRANT EXECUTE ON [dbo].[sp_add_job]  TO [SQLAgentUserRole] 
GRANT EXECUTE ON [dbo].[sp_add_jobschedule]  TO [SQLAgentUserRole] 
GRANT EXECUTE ON [dbo].[sp_add_jobserver]  TO [SQLAgentUserRole] 
GRANT EXECUTE ON [dbo].[sp_add_jobstep]  TO [SQLAgentUserRole] 
GRANT EXECUTE ON [dbo].[sp_add_schedule]  TO [SQLAgentUserRole] 
GRANT EXECUTE ON [dbo].[sp_addtask]  TO [SQLAgentUserRole] 
GRANT EXECUTE ON [dbo].[sp_attach_schedule]  TO [SQLAgentUserRole] 
GRANT EXECUTE ON [dbo].[sp_check_for_owned_jobs]  TO [SQLAgentUserRole] 
GRANT EXECUTE ON [dbo].[sp_check_for_owned_jobsteps]  TO [SQLAgentUserRole] 
GRANT EXECUTE ON [dbo].[sp_delete_job]  TO [SQLAgentUserRole] 
GRANT EXECUTE ON [dbo].[sp_delete_jobschedule]  TO [SQLAgentUserRole] 
GRANT EXECUTE ON [dbo].[sp_delete_jobserver]  TO [SQLAgentUserRole] 
GRANT EXECUTE ON [dbo].[sp_delete_jobstep]  TO [SQLAgentUserRole] 
GRANT EXECUTE ON [dbo].[sp_delete_jobsteplog]  TO [SQLAgentUserRole] 
GRANT EXECUTE ON [dbo].[sp_delete_schedule]  TO [SQLAgentUserRole] 
GRANT EXECUTE ON [dbo].[sp_detach_schedule]  TO [SQLAgentUserRole] 
GRANT EXECUTE ON [dbo].[sp_droptask]  TO [SQLAgentUserRole] 
GRANT EXECUTE ON [dbo].[sp_enum_sqlagent_subsystems]  TO [SQLAgentUserRole] 
GRANT EXECUTE ON [dbo].[sp_get_job_alerts]  TO [SQLAgentUserRole] 
GRANT EXECUTE ON [dbo].[sp_get_jobstep_db_username]  TO [SQLAgentUserRole] 
GRANT EXECUTE ON [dbo].[sp_get_sqlagent_properties]  TO [SQLAgentUserRole] 
GRANT EXECUTE ON [dbo].[sp_help_category]  TO [SQLAgentUserRole] 
GRANT EXECUTE ON [dbo].[sp_help_job]  TO [SQLAgentUserRole] 
GRANT EXECUTE ON [dbo].[sp_help_jobactivity]  TO [SQLAgentUserRole] 
GRANT EXECUTE ON [dbo].[sp_help_jobcount]  TO [SQLAgentUserRole] 
GRANT EXECUTE ON [dbo].[sp_help_jobhistory]  TO [SQLAgentUserRole] 
GRANT EXECUTE ON [dbo].[sp_help_jobhistory_full]  TO [SQLAgentUserRole] 
GRANT EXECUTE ON [dbo].[sp_help_jobhistory_sem]  TO [SQLAgentUserRole] 
GRANT EXECUTE ON [dbo].[sp_help_jobhistory_summary]  TO [SQLAgentUserRole] 
GRANT EXECUTE ON [dbo].[sp_help_jobs_in_schedule]  TO [SQLAgentUserRole] 
GRANT EXECUTE ON [dbo].[sp_help_jobschedule]  TO [SQLAgentUserRole] 
GRANT EXECUTE ON [dbo].[sp_help_jobserver]  TO [SQLAgentUserRole] 
GRANT EXECUTE ON [dbo].[sp_help_jobstep]  TO [SQLAgentUserRole] 
GRANT EXECUTE ON [dbo].[sp_help_jobsteplog]  TO [SQLAgentUserRole] 
GRANT EXECUTE ON [dbo].[sp_help_operator]  TO [SQLAgentUserRole] 
GRANT EXECUTE ON [dbo].[sp_help_proxy]  TO [SQLAgentUserRole] 
GRANT EXECUTE ON [dbo].[sp_help_schedule]  TO [SQLAgentUserRole] 
GRANT EXECUTE ON [dbo].[sp_maintplan_subplans_by_job]  TO [SQLAgentUserRole] 
GRANT EXECUTE ON [dbo].[sp_notify_operator]  TO [SQLAgentUserRole] 
GRANT EXECUTE ON [dbo].[sp_start_job]  TO [SQLAgentUserRole] 
GRANT EXECUTE ON [dbo].[sp_stop_job]  TO [SQLAgentUserRole] 
GRANT EXECUTE ON [dbo].[sp_uniquetaskname]  TO [SQLAgentUserRole] 
GRANT EXECUTE ON [dbo].[sp_update_job]  TO [SQLAgentUserRole] 
GRANT EXECUTE ON [dbo].[sp_update_jobschedule]  TO [SQLAgentUserRole] 
GRANT EXECUTE ON [dbo].[sp_update_jobstep]  TO [SQLAgentUserRole] 
GRANT EXECUTE ON [dbo].[sp_update_schedule]  TO [SQLAgentUserRole] 
GRANT SELECT ON [dbo].[syscategories]  TO [SQLAgentUserRole] 
GRANT SELECT ON [dbo].[sysjobs_view]  TO [SQLAgentUserRole] 
GRANT SELECT ON [dbo].[sysschedules_localserver_view]  TO [SQLAgentUserRole] 
END

IF EXISTS (SELECT * FROM sys.database_principals WHERE name = N'SQLAgentUserRole' AND type = 'R')
EXEC sp_addrolemember N'SQLAgentUserRole', N'VIEJAS\LWSNDB02PR$'

IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'SQLAgentReaderRole' AND type = 'R')
BEGIN
CREATE ROLE [SQLAgentReaderRole] AUTHORIZATION [dbo]
END

IF EXISTS (SELECT * FROM sys.database_principals WHERE name = N'SQLAgentReaderRole' AND type = 'R')
EXEC sp_addrolemember N'SQLAgentReaderRole', N'VIEJAS\LWSNDB02PR$'

IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'SQLAgentOperatorRole' AND type = 'R')
BEGIN
CREATE ROLE [SQLAgentOperatorRole] AUTHORIZATION [dbo]
GRANT EXECUTE ON [dbo].[sp_enum_login_for_proxy]  TO [SQLAgentOperatorRole] 
GRANT EXECUTE ON [dbo].[sp_help_alert]  TO [SQLAgentOperatorRole] 
GRANT EXECUTE ON [dbo].[sp_help_notification]  TO [SQLAgentOperatorRole] 
GRANT EXECUTE ON [dbo].[sp_help_targetserver]  TO [SQLAgentOperatorRole] 
GRANT EXECUTE ON [dbo].[sp_purge_jobhistory]  TO [SQLAgentOperatorRole] 
GRANT SELECT ON [dbo].[sysalerts]  TO [SQLAgentOperatorRole] 
GRANT SELECT ON [dbo].[sysalerts_performance_counters_view]  TO [SQLAgentOperatorRole] 
GRANT SELECT ON [dbo].[sysnotifications]  TO [SQLAgentOperatorRole] 
GRANT SELECT ON [dbo].[sysoperators]  TO [SQLAgentOperatorRole] 
END

IF EXISTS (SELECT * FROM sys.database_principals WHERE name = N'SQLAgentOperatorRole' AND type = 'R')
EXEC sp_addrolemember N'SQLAgentOperatorRole', N'VIEJAS\LWSNDB02PR$'

IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'RSExecRole' AND type = 'R')
BEGIN
CREATE ROLE [RSExecRole] AUTHORIZATION [dbo]
GRANT EXECUTE ON [dbo].[sp_add_category]  TO [RSExecRole] 
GRANT EXECUTE ON [dbo].[sp_add_job]  TO [RSExecRole] 
GRANT EXECUTE ON [dbo].[sp_add_jobschedule]  TO [RSExecRole] 
GRANT EXECUTE ON [dbo].[sp_add_jobserver]  TO [RSExecRole] 
GRANT EXECUTE ON [dbo].[sp_add_jobstep]  TO [RSExecRole] 
GRANT EXECUTE ON [dbo].[sp_delete_job]  TO [RSExecRole] 
GRANT EXECUTE ON [dbo].[sp_help_category]  TO [RSExecRole] 
GRANT EXECUTE ON [dbo].[sp_help_job]  TO [RSExecRole] 
GRANT EXECUTE ON [dbo].[sp_help_jobschedule]  TO [RSExecRole] 
GRANT EXECUTE ON [dbo].[sp_verify_job_identifiers]  TO [RSExecRole] 
GRANT SELECT ON [dbo].[syscategories]  TO [RSExecRole] 
GRANT SELECT ON [dbo].[sysjobs]  TO [RSExecRole] 
END

IF EXISTS (SELECT * FROM sys.database_principals WHERE name = N'RSExecRole' AND type = 'R')
EXEC sp_addrolemember N'RSExecRole', N'VIEJAS\LWSNDB02PR$'



ALTER LOGIN [VIEJAS\LWSNDB02PR$] ENABLE

END