USE [master] 
IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = N'VIEJAS\HR_SQL')
BEGIN
DECLARE @CreateError INT
CREATE LOGIN [VIEJAS\HR_SQL] FROM WINDOWS
SET @CreateError = @@ERROR


GRANT CONNECT SQL TO [VIEJAS\HR_SQL] 


USE [LAWSON_EXTRACT]
IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'hr_sql')
CREATE USER [hr_sql] FOR LOGIN [VIEJAS\HR_SQL] WITH DEFAULT_SCHEMA=[hr_sql]



USE PROD10
IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'VIEJAS\HR_SQL')
CREATE USER [VIEJAS\HR_SQL] FOR LOGIN [VIEJAS\HR_SQL] WITH DEFAULT_SCHEMA=[dbo]


GRANT SELECT ON [lawson].[DEPTCODE]  TO [VIEJAS\HR_SQL] 
GRANT SELECT ON [lawson].[EMPLOYEE]  TO [VIEJAS\HR_SQL] 
GRANT SELECT ON [lawson].[JOBCODE]  TO [VIEJAS\HR_SQL] 
GRANT SELECT ON [lawson].[PAATTRIB]  TO [VIEJAS\HR_SQL] 
GRANT SELECT ON [lawson].[PACOST]  TO [VIEJAS\HR_SQL] 
GRANT SELECT ON [lawson].[PACOURSE]  TO [VIEJAS\HR_SQL] 
GRANT SELECT ON [lawson].[PAEMPCOSTS]  TO [VIEJAS\HR_SQL] 
GRANT SELECT ON [lawson].[PAEMPTRACK]  TO [VIEJAS\HR_SQL] 
GRANT SELECT ON [lawson].[PAINSCOURS]  TO [VIEJAS\HR_SQL] 
GRANT SELECT ON [lawson].[PAINSTRUCT]  TO [VIEJAS\HR_SQL] 
GRANT SELECT ON [lawson].[PAINSTSES]  TO [VIEJAS\HR_SQL] 
GRANT SELECT ON [lawson].[PAMODOPT]  TO [VIEJAS\HR_SQL] 
GRANT SELECT ON [lawson].[PAPREREQ]  TO [VIEJAS\HR_SQL] 
GRANT SELECT ON [lawson].[PASCOST]  TO [VIEJAS\HR_SQL] 
GRANT SELECT ON [lawson].[PASESSION]  TO [VIEJAS\HR_SQL] 
GRANT SELECT ON [lawson].[PATRACK]  TO [VIEJAS\HR_SQL] 
GRANT SELECT ON [lawson].[PATRACKDTL]  TO [VIEJAS\HR_SQL] 
GRANT SELECT ON [lawson].[PATRNHIST]  TO [VIEJAS\HR_SQL] 

ALTER LOGIN [VIEJAS\HR_SQL] ENABLE

END