USE [master] 
IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = N'VIEJAS\ERevak')
BEGIN
DECLARE @CreateError INT
CREATE LOGIN [VIEJAS\ERevak] FROM WINDOWS
SET @CreateError = @@ERROR


GRANT CONNECT SQL TO [VIEJAS\ERevak] 


USE PROD10
IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'VIEJAS\ERevak')
CREATE USER [VIEJAS\ERevak] FOR LOGIN [VIEJAS\ERevak] WITH DEFAULT_SCHEMA=[VIEJAS\ERevak]

IF EXISTS (SELECT * FROM sys.database_principals WHERE name = N'db_datareader' AND type = 'R')
EXEC sp_addrolemember N'db_datareader', N'VIEJAS\ERevak'


DENY ALTER ON [lawson].[PAYDEDUCTN]  TO [VIEJAS\ERevak] 
DENY CONTROL ON [lawson].[PAYDEDUCTN]  TO [VIEJAS\ERevak] 
DENY DELETE ON [lawson].[PAYDEDUCTN]  TO [VIEJAS\ERevak] 
DENY INSERT ON [lawson].[PAYDEDUCTN]  TO [VIEJAS\ERevak] 
DENY SELECT ON [lawson].[PAYDEDUCTN]  TO [VIEJAS\ERevak] 
DENY TAKE OWNERSHIP ON [lawson].[PAYDEDUCTN]  TO [VIEJAS\ERevak] 
DENY UPDATE ON [lawson].[PAYDEDUCTN]  TO [VIEJAS\ERevak] 
DENY ALTER ON [lawson].[PAYMASTR]  TO [VIEJAS\ERevak] 
DENY CONTROL ON [lawson].[PAYMASTR]  TO [VIEJAS\ERevak] 
DENY DELETE ON [lawson].[PAYMASTR]  TO [VIEJAS\ERevak] 
DENY INSERT ON [lawson].[PAYMASTR]  TO [VIEJAS\ERevak] 
DENY SELECT ON [lawson].[PAYMASTR]  TO [VIEJAS\ERevak] 
DENY TAKE OWNERSHIP ON [lawson].[PAYMASTR]  TO [VIEJAS\ERevak] 
DENY UPDATE ON [lawson].[PAYMASTR]  TO [VIEJAS\ERevak] 
DENY ALTER ON [lawson].[PAYSUMGRP]  TO [VIEJAS\ERevak] 
DENY CONTROL ON [lawson].[PAYSUMGRP]  TO [VIEJAS\ERevak] 
DENY DELETE ON [lawson].[PAYSUMGRP]  TO [VIEJAS\ERevak] 
DENY INSERT ON [lawson].[PAYSUMGRP]  TO [VIEJAS\ERevak] 
DENY SELECT ON [lawson].[PAYSUMGRP]  TO [VIEJAS\ERevak] 
DENY TAKE OWNERSHIP ON [lawson].[PAYSUMGRP]  TO [VIEJAS\ERevak] 
DENY UPDATE ON [lawson].[PAYSUMGRP]  TO [VIEJAS\ERevak] 

ALTER LOGIN [VIEJAS\ERevak] ENABLE

END