

MERGE INTO [iQ-Gaming].[CMP_13-1].[tTableRating] AS Target
USING [iQ-Gaming].[CMP_13-1].[tTableRating_Staging] AS Source  ON (Target.[TranId] = Source.[TranId] AND Target.[GamingDt] = Source.[GamingDt])
WHEN NOT MATCHED BY TARGET
THEN INSERT([TranID]
	      , [PlayerId]
	      , [IsVoid]
	      , [TranCodeID]
	      , [GamingDt]
	      , [Shift]
	      , [AgingDt]
	      , [PostDtm]
	      , [ComputerName]
	      , [EmpID]
	      , [AuthEmpId]
	      , [DeptID]
	      , [CasinoID]
	      , [AreaID]
	      , [LocnID]
	      , [GameID]
	      , [DenomID]
	      , [RepID]
	      , [DocumentNo]
	      , [Ref1]
	      , [Ref2]
	      , [IsOpenItem]
	      , [GroupID]
	      , [PlayerTypeID]
	      , [OriginalPlayerID]
	      , [RelatedTranID]
	      , [VoidTranID]
	      , [Flags]
	      , [IsDistributed]
	      , [OldRelatedTranID]
	      , [StratId]
	      , [RatingStartDtm]
	      , [RatingEndDtm]
	      , [CashBuyIn]
 	      , [CreditBuyIn]
	      , [ChipBuyIn]
	      , [PromoBuyIn]
	      , [ECreditBuyIn]
	      , [ECashBuyIn]
	      , [RatingPeriodMinutes]
	      , [Plays]
	      , [Bet]
	      , [PaidOut]
	      , [WalkedWith]
	      , [TheorHoldPc]
	      , [TheorWin]
	      , [GamePts]
	      , [CasinoWinCalcMethod]
	      , [CasinoWin]
	      , [HighBet]
	      , [MgmtRating]
	      , [LocnMinBet]
	      , [LocnMaxBet]
	      , [CasinoStatistic]
	      , [CreatedDtm]
	      , [CreatedBy]
	      , [ModifiedDtm]
	      , [ModifiedBy]
	      , [SeatNo]
	      , [FreqId]
	      , [AdjBet]
	      , [AdjPaidOut]
	      , [AdjTheorWin]
	      , [AdjCasinoWin]
	      , [DataRowVersion]
	      , [ActualRatingStartTime]
	      , [ActualRatingEndTime]
	      , [TripDt]
	      , [TripId]
	      , [TripType]
	      , [AllowedPurgeDt]
	      , [VIPPlayerID]
	      , [BetByBet]
	      , [IsBetByBet]
	      , [AverageBet]
	      , [PromoChips]  )
	 VALUES(Source.[TranID]
	      , Source.[PlayerId]
	      , Source.[IsVoid]
	      , Source.[TranCodeID]
	      , Source.[GamingDt]
	      , Source.[Shift]
	      , Source.[AgingDt]
	      , Source.[PostDtm]
	      , Source.[ComputerName]
	      , Source.[EmpID]
	      , Source.[AuthEmpId]
	      , Source.[DeptID]
	      , Source.[CasinoID]
	      , Source.[AreaID]
	      , Source.[LocnID]
	      , Source.[GameID]
	      , Source.[DenomID]
	      , Source.[RepID]
	      , Source.[DocumentNo]
	      , Source.[Ref1]
	      , Source.[Ref2]
	      , Source.[IsOpenItem]
	      , Source.[GroupID]
 	      , Source.[PlayerTypeID]
	      , Source.[OriginalPlayerID]
	      , Source.[RelatedTranID]
	      , Source.[VoidTranID]
	      , Source.[Flags]
	      , Source.[IsDistributed]
	      , Source.[OldRelatedTranID]
	      , Source.[StratId]
	      , Source.[RatingStartDtm]
	      , Source.[RatingEndDtm]
	      , Source.[CashBuyIn]
	      , Source.[CreditBuyIn]
	      , Source.[ChipBuyIn]
	      , Source.[PromoBuyIn]
	      , Source.[ECreditBuyIn]
   	      , Source.[ECashBuyIn]
   	      , Source.[RatingPeriodMinutes]
 	      , Source.[Plays]
	      , Source.[Bet]
	      , Source.[PaidOut]
	      , Source.[WalkedWith]
	      , Source.[TheorHoldPc]
	      , Source.[TheorWin]
	      , Source.[GamePts]
	      , Source.[CasinoWinCalcMethod]
	      , Source.[CasinoWin]
	      , Source.[HighBet]
	      , Source.[MgmtRating]
	      , Source.[LocnMinBet]
	      , Source.[LocnMaxBet]
	      , Source.[CasinoStatistic]
	      , Source.[CreatedDtm]
	      , Source.[CreatedBy]
	      , Source.[ModifiedDtm]
	      , Source.[ModifiedBy]
	      , Source.[SeatNo]
	      , Source.[FreqId]
	      , Source.[AdjBet]
	      , Source.[AdjPaidOut]
	      , Source.[AdjTheorWin]
	      , Source.[AdjCasinoWin]
   	      , Source.[DataRowVersion]
	      , Source.[ActualRatingStartTime]
	      , Source.[ActualRatingEndTime]
	      , Source.[TripDt]
	      , Source.[TripId]
	      , Source.[TripType]
	      , Source.[AllowedPurgeDt]
	      , Source.[VIPPlayerID]
	      , Source.[BetByBet]
	      , Source.[IsBetByBet]
	      , Source.[AverageBet]
	      , Source.[PromoChips] )
WHEN MATCHED AND (Source.[ModifiedDtm] <> Target.[ModifiedDtm])
THEN UPDATE SET Target.[PlayerId] = Source.[PlayerId]
	          , Target.[IsVoid] = Source.[IsVoid]
	          , Target.[TranCodeID] = Source.[TranCodeID]
	          , Target.[Shift] = Source.[Shift]
	          , Target.[AgingDt] = Source.[AgingDt]
	          , Target.[PostDtm] = Source.[PostDtm]
	          , Target.[ComputerName] = Source.[ComputerName]
	          , Target.[EmpID] = Source.[EmpID]
	          , Target.[AuthEmpId] = Source.[AuthEmpId]
	          , Target.[DeptID] = Source.[DeptID]
	          , Target.[CasinoID] = Source.[CasinoID]
	          , Target.[AreaID] = Source.[AreaID]
	          , Target.[LocnID] = Source.[LocnID]
	          , Target.[GameID] = Source.[GameID]
	          , Target.[DenomID] = Source.[DenomID]
	          , Target.[RepID] = Source.[RepID]
	          , Target.[DocumentNo] = Source.[DocumentNo]
	          , Target.[Ref1] = Source.[Ref1]
	          , Target.[Ref2] = Source.[Ref2]
	          , Target.[IsOpenItem] = Source.[IsOpenItem]
	          , Target.[GroupID] = Source.[GroupID]
	          , Target.[PlayerTypeID] = Source.[PlayerTypeID]
	          , Target.[OriginalPlayerID] = Source.[OriginalPlayerID]
	          , Target.[RelatedTranID] = Source.[RelatedTranID]
	          , Target.[VoidTranID] = Source.[VoidTranID]
	          , Target.[Flags] = Source.[Flags]
	          , Target.[IsDistributed] = Source.[IsDistributed]
	          , Target.[OldRelatedTranID] = Source.[OldRelatedTranID]
	          , Target.[StratId] = Source.[StratId]
	          , Target.[RatingStartDtm] = Source.[RatingStartDtm]
	          , Target.[RatingEndDtm] = Source.[RatingEndDtm]
	          , Target.[CashBuyIn] = Source.[CashBuyIn]
	          , Target.[CreditBuyIn] = Source.[CreditBuyIn]
	          , Target.[ChipBuyIn] = Source.[ChipBuyIn]
	          , Target.[PromoBuyIn] = Source.[PromoBuyIn]
	          , Target.[ECreditBuyIn] = Source.[ECreditBuyIn]
	          , Target.[ECashBuyIn] = Source.[ECashBuyIn]
	          , Target.[RatingPeriodMinutes] = Source.[RatingPeriodMinutes]
	          , Target.[Plays] = Source.[Plays]
	          , Target.[Bet] = Source.[Bet]
	          , Target.[PaidOut] = Source.[PaidOut]
	          , Target.[WalkedWith] = Source.[WalkedWith]
	          , Target.[TheorHoldPc] = Source.[TheorHoldPc]
	          , Target.[TheorWin] = Source.[TheorWin]
	          , Target.[GamePts] = Source.[GamePts]
	          , Target.[CasinoWinCalcMethod] = Source.[CasinoWinCalcMethod]
	          , Target.[CasinoWin] = Source.[CasinoWin]
	          , Target.[HighBet] = Source.[HighBet]
	          , Target.[MgmtRating] = Source.[MgmtRating]
	          , Target.[LocnMinBet] = Source.[LocnMinBet]
	          , Target.[LocnMaxBet] = Source.[LocnMaxBet]
	          , Target.[CasinoStatistic] = Source.[CasinoStatistic]
	          , Target.[CreatedDtm] = Source.[CreatedDtm]
	          , Target.[CreatedBy] = Source.[CreatedBy]
	          , Target.[ModifiedDtm] = Source.[ModifiedDtm]
	          , Target.[ModifiedBy] = Source.[ModifiedBy]
	          , Target.[SeatNo] = Source.[SeatNo]
	          , Target.[FreqId] = Source.[FreqId]
	          , Target.[AdjBet] = Source.[AdjBet]
	          , Target.[AdjPaidOut] = Source.[AdjPaidOut]
	          , Target.[AdjTheorWin] = Source.[AdjTheorWin]
	          , Target.[AdjCasinoWin] = Source.[AdjCasinoWin]
	          , Target.[DataRowVersion] = Source.[DataRowVersion]
	          , Target.[ActualRatingStartTime] = Source.[ActualRatingStartTime]
	          , Target.[ActualRatingEndTime] = Source.[ActualRatingEndTime]
	          , Target.[TripDt] = Source.[TripDt]
	          , Target.[TripId] = Source.[TripId]
	          , Target.[TripType] = Source.[TripType]
	          , Target.[AllowedPurgeDt] = Source.[AllowedPurgeDt]
	          , Target.[VIPPlayerID] = Source.[VIPPlayerID]
	          , Target.[BetByBet] = Source.[BetByBet]
	          , Target.[IsBetByBet] = Source.[IsBetByBet]
	          , Target.[AverageBet] = Source.[AverageBet]
	          , Target.[PromoChips] = Source.[PromoChips];
GO


MERGE INTO [CMP_13-1].[tTableRating_Inserted] AS Target
USING [CMP_13-1].[tTableRating_Staging] AS Source  ON (Target.[TranId] = Source.[TranId] AND Target.[GamingDt] = Source.[GamingDt])
WHEN NOT MATCHED BY TARGET
AND CAST([dbo].fn_ConvertUTCToPacific(Source.[ModifiedDtm]) AS DATE) > Source.[GamingDt]
THEN INSERT([TranID], [GamingDt], [AccountingDate])
VALUES (Source.[TranId], Source.[GamingDt], CAST([dbo].fn_ConvertUTCToPacific(Source.[RatingStartDtm]) AS DATE));

GO

TRUNCATE TABLE [CMP_13-1].[tTableRating_Staging]