-- Login: VIEJAS\APPSWB01PR$
CREATE LOGIN [VIEJAS\APPSWB01PR$] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: VIEJAS\APPSWB02PR$
CREATE LOGIN [VIEJAS\APPSWB02PR$] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: VIEJAS\APPSWB21APR$
CREATE LOGIN [VIEJAS\APPSWB21APR$] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: VIEJAS\APPSWB21BPR$
CREATE LOGIN [VIEJAS\APPSWB21BPR$] FROM WINDOWS WITH DEFAULT_DATABASE = [master]