SELECT --top 10 
  RESV_NAME_ID
, NAME_ID
, MEMBERSHIP_ID
, TRX_CODE
, TRX_DATE
FROM OPERA..OPERA.FINANCIAL_TRANSACTIONS
--FROM OPERA..OPERA.NAME_RESERVATION
--WHERE NAME_ID = '71'
WHERE MEMBERSHIP_ID = 975

USE [iQ-Gaming]
GO


SELECT TOP 10 *
FROM [iQ-Gaming].[CMP_13-1].tPlayer tp
--LEFT JOIN Opera_5_0.FINANCIAL_TRANSACTIONS oft
--ON tp.Playerid = oft.RESV_NAME_ID

WHERE tp.PlayerId = '71'