USE [iQ-Gaming]
GO

SELECT 
  nr.RESV_NAME_ID
, nr.RESERVATION_DATE
, nr.MEMBERSHIP_NUMBER
, nr.UPDATE_DATE
, nr.INSERT_DATE
, nr.GUEST_FIRST_NAME
, nr.GUEST_NAME
, ft.TRX_NO
, ft.TRX_DATE

FROM Opera_5_0.NAME_RESERVATION nr
LEFT JOIN Opera_5_0.FINANCIAL_TRANSACTIONS ft
--LEFT JOIN OPERA..[OPERA].[FINANCIAL_TRANSACTIONS_VIEW]ft
ON nr.RESV_NAME_ID = ft.RESV_NAME_ID

--WHERE nr.MEMBERSHIP_NUMBER = 975
WHERE ft.RESV_NAME_ID is null

ORDER BY 
 INSERT_DATE DESC