-- ssothras
USE [master]
GO

ALTER LOGIN [VIEJAS\ssothras] DISABLE
GO

--CREATE LOGIN [VIEJAS\ssothras] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english]
--GO

--USE [CMP13]
--GO

--CREATE USER [VIEJAS\ssothras] FOR LOGIN [VIEJAS\ssothras] WITH DEFAULT_SCHEMA=[dbo]
--GO

--ALTER ROLE [db_datareader] ADD MEMBER [VIEJAS\ssothras]
--GO


-- RScott
USE [master]
GO

ALTER LOGIN [VIEJAS\RScott] DISABLE
GO

--CREATE LOGIN [VIEJAS\RScott] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english]
--GO

--USE [CMP13]
--GO

--CREATE USER [VIEJAS\RScott] FOR LOGIN [VIEJAS\RScott] WITH DEFAULT_SCHEMA=[dbo]
--GO

--ALTER ROLE [db_datareader] ADD MEMBER [VIEJAS\RScott]
--GO


-- TGrady
USE [master]
GO

ALTER LOGIN [VIEJAS\TGrady] DISABLE
GO

--CREATE LOGIN [VIEJAS\TGrady] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english]
--GO

--USE [CMP13]
--GO

--CREATE USER [VIEJAS\TGrady] FOR LOGIN [VIEJAS\TGrady] WITH DEFAULT_SCHEMA=[dbo]
--GO

--ALTER ROLE [db_datareader] ADD MEMBER [VIEJAS\TGrady]
--GO


-- NDollins
USE [master]
GO

ALTER LOGIN [VIEJAS\NDollins] DISABLE
GO

--CREATE LOGIN [VIEJAS\NDollins] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english]
--GO

--USE [CMP13]
--GO

--CREATE USER [VIEJAS\NDollins] FOR LOGIN [VIEJAS\NDollins] WITH DEFAULT_SCHEMA=[dbo]
--GO

--ALTER ROLE [db_datareader] ADD MEMBER [VIEJAS\NDollins]
--GO


-- MGoens
USE [master]
GO

ALTER LOGIN [VIEJAS\MGoens] DISABLE
GO

--CREATE LOGIN [VIEJAS\MGoens] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english]
--GO

--USE [CMP13]
--GO

--CREATE USER [VIEJAS\MGoens] FOR LOGIN [VIEJAS\MGoens] WITH DEFAULT_SCHEMA=[dbo]
--GO

--ALTER ROLE [db_datareader] ADD MEMBER [VIEJAS\MGoens]
--GO