USE [iQ-Gaming]
GO

--/****** Object:  View [Tableau].[player_award_fact_dailyFacts]    Script Date: 5/17/2024 11:18:56 AM ******/
--SET ANSI_NULLS ON
--GO

--SET QUOTED_IDENTIFIER ON
--GO


--CREATE   VIEW [Tableau].[player_award_fact_dailyFacts]
--AS
SELECT top 10000
a.PlayerId,
a.DATE_KEY,
cast(convert(varchar(10), nullif(a.DATE_KEY, 0)) as datetime) as gaming_date,
b.*,
c.player_type				as player_type_hist,
c.player_club_level			as player_club_level_hist,
c.player_zip				as player_zip_hist,
c.player_host				as player_host_hist,
c.player_age_category		as player_age_category_hist,
c.player_gaming_type		as player_gaming_type_hist,
c.player_slot_type			as player_slot_type_hist,
c.player_table_type			as player_table_type_hist,
c.player_frequency			as player_frequency_hist,
c.player_adt_category		as player_adt_category_hist,
c.player_lifecycle			as player_lifecycle_hist,
d.geo_city,
d.geo_county,
d.geo_state,
d.geo_country,
d.geo_distance,
d.geo_distance_category,
d.geo_distance_subcategory,
d.geo_population,
d.geo_market,
a.a_award_id,
a.a_IsVoid,
a.a_TranCode,
a.a_GroupCode,
a.a_DeptCode,
a.a_AreaCode,
a.a_LocnCode,
a.a_GameCode,
a.a_DenomCode,
a.a_PrizeCode,
a.a_PrizeName,
a.[Prize Name],
a.a_PrizeQty,
a.PostDtm,
a.ComputerName,
a.Outlet,
a.AuthorizedBy,
a.Ref1,
a.Ref2,
a.award_CompsUsed_Total_Finance,
a.award_CompsUsed_Total_Mktg,
a.award_Benefits_FB,
a.award_FPAwarded_MonthlyOffer,
a.award_FPAwarded_Supplemental,
a.award_FPAwarded_PromoWinner,
a.award_FPAwarded_Other,
a.award_FPAwarded_Pts,
a.award_FPAwarded_NonPts,
a.award_FPAwarded_Total,
a.award_FreePlay_Used,
a.award_PromoChipsAwarded,
a.award_CashAwarded_Bingo,
a.award_CashAwarded_Promotional,
a.award_CashAwarded_Other,
a.award_PointsAwarded_Base,
a.award_PointsAwarded_Bonus,
a.award_PointsAwarded_Other,
a.award_PointsAwarded_Total,
a.award_PointsRedeemed,
a.award_PointsExpired,
a.award_PointsPurchased,
a.award_PointsUsed_POS,
a.award_AwardUsed AwardUsed,
--a.BasePts as a_BasePts,
--a.BonusPts as a_BonusPts,
--a.EarnedPts as a_EarnedPts,
--a.RedeemPts as a_RedeemPts,
--a.NetPts as a_NetPts,
--a.ExpirePts as a_ExpirePts,
--a.BaseStubs as a_BaseStubs,
--a.BonusStubs as a_BonusStubs,
--a.EarnedStubs as a_EarnedStubs,
--a.Promo1 as a_Promo1,
--a.BonusPromo1 as a_BonusPromo1,
--a.Promo1Used as a_Promo1Used,
--a.NetPromo1 as a_NetPromo1,
--a.Promo2 as a_Promo2,
--a.BonusPromo2 as a_BonusPromo2,
--a.Promo2Used as a_Promo2Used,
--a.NetPromo2 as a_NetPromo2,
--case when a.PrizeCode not like 'CSH%' and a.PrizeCode not like 'FP[_]%' then a.netPromo1 else 0 end	as a_FPCAwarded,
--case when a.PrizeCode like 'CSH%' or a.PrizeCode like 'FP[_]%' then a.netPromo1 else 0 end			as a_FPCUsed,
--a.AuthAward as a_AuthAward,
--a.AwardUsed as a_AwardUsed ,
--a.EarnedComp as a_EarnedComp,
--a.CompUsed as a_CompUsed,
--a.NetComp as a_NetComp,
--a.EarnedAltComp as a_EarnedAltComp,
--a.NetAltComp as a_NetAltComp,
--a.AwardCode as a_AwardCode,
--a.Room as a_Room,
--a.Entertainment as a_Entertainment ,
--a.Food as a_Food,
--a.Travel as a_Travel,
--a.Merchandise as a_Merchandise,
--a.Other as a_Other,
--a.PromoCredit as a_PromoCredit,
--a.CashAward as a_CashAward,
--a.MachineCredit as a_MachineCredit,
--a.eCOUPON as a_eCOUPON,
df.gaming_days as df_gaming_days,
df.slot_minutes_played as df_slot_minutes_played,
df.slot_buyin_cash as df_slot_buyin_cash,
df.slot_buyin_credit as df_slot_buyin_credit,
df.slot_buyin_chips as df_slot_buyin_chips ,
df.slot_buyin_promo as df_slot_buyin_promo ,
df.slot_buyin_Ecredit as df_slot_buyin_Ecredit,
df.slot_plays as df_slot_plays,
df.slot_total_bet as df_slot_total_bet ,
df.slot_paid_out as df_slot_paid_out,
df.slot_theo_win as df_slot_theo_win,
df.slot_actual_win as df_slot_actual_win,
df.slot_jackpot_win as df_slot_jackpot_win,
df.table_minutes_played as df_table_minutes_played,
df.table_buyin_cash as df_table_buyin_cash,
df.table_buyin_credit as df_table_buyin_credit,
df.table_buyin_chips as df_table_buyin_chips,
df.table_buyin_promo as df_table_buyin_promo,
df.table_buyin_Ecredit as df_table_buyin_Ecredit,
df.table_plays as df_table_plays ,
df.table_total_bet as df_table_total_bet,
df.table_paid_out as df_table_paid_out,
df.table_theo_win as df_table_theo_win,
df.table_actual_win as df_table_actual_win,
df.other_minutes_played as df_other_minutes_played,
df.other_buyin_cash as df_other_buyin_cash,
df.other_buyin_credit as df_other_buyin_credit,
df.other_buyin_chips as df_other_buyin_chips,
df.other_buyin_promo as df_other_buyin_promo,
df.other_buyin_Ecredit as df_other_buyin_Ecredit,
df.other_plays as df_other_plays,
df.other_total_bet as df_other_total_bet,
df.other_paid_out as df_other_paid_out ,
df.other_theo_win as df_other_theo_win,
df.other_actual_win as df_other_actual_win,
case when df.slot_theo_win + df.table_theo_win + df.other_theo_win >= df.slot_actual_win + df.table_actual_win + df.other_actual_win
	then df.slot_theo_win + df.table_theo_win + df.other_theo_win
	else df.slot_actual_win + df.table_actual_win + df.other_actual_win end * .4 as df_daily_worth,
df.points_earned as df_points_earned,
df.bonus_points_earned as df_bonus_points_earned,
df.comps_earned as comps_earned,
df.comps_alt_earned as df_comps_alt_earned,
df.offer_redeemed_total as df_offer_redeemed_total,
df.offer_redeemed_hotel as df_offer_redeemed_hotel,
df.offer_redeemed_event as df_offer_redeemed_event,
df.offer_redeemed_FPC as df_offer_redeemed_FPC,
df.offer_redeemed_other as df_offer_redeemed_other ,
df.award_AwardUsed					as df_award_AwardUsed,
df.award_HotelReservations			as df_award_HotelReservations,
df.award_CompsUsed_Hotel_Finance	as df_award_CompsUsed_Hotel_Finance,
df.award_CompsUsed_Hotel_Mktg		as df_award_CompsUsed_Hotel_Mktg,
df.award_CompsUsed_Hotel_Folio		as df_award_CompsUsed_Hotel_Folio,
df.award_CompsUsed_Total_Finance	as df_award_CompsUsed_Total_Finance,
df.award_CompsUsed_Total_Mktg		as df_award_CompsUsed_Total_Mktg,
df.award_Benefits_FB				as df_award_Benefits_FB,
df.award_FPAwarded_MonthlyOffer		as df_award_FPAwarded_MonthlyOffer,
df.award_FPAwarded_Supplemental		as df_award_FPAwarded_Supplemental,
df.award_FPAwarded_PromoWinner		as df_award_FPAwarded_PromoWinner,
df.award_FPAwarded_Other			as df_award_FPAwarded_Other,
df.award_FPAwarded_Pts				as df_award_FPAwarded_Pts,
df.award_FPAwarded_NonPts			as df_award_FPAwarded_NonPts,
df.award_FPAwarded_Total			as df_award_FPAwarded_Total,
df.award_FreePlay_Used				as df_award_FreePlay_Used,
df.award_PromoChipsAwarded			as df_award_PromoChipsAwarded,
df.award_CashAwarded_Bingo			as df_award_CashAwarded_Bingo,
df.award_CashAwarded_Promotional	as df_award_CashAwarded_Promotional,
df.award_CashAwarded_Other			as df_award_CashAwarded_Other,
df.award_PointsAwarded_Base			as df_award_PointsAwarded_Base,
df.award_PointsAwarded_Bonus		as df_award_PointsAwarded_Bonus,
df.award_PointsAwarded_Other		as df_award_PointsAwarded_Other,
df.award_PointsAwarded_Total		as df_award_PointsAwarded_Total,
df.award_PointsRedeemed				as df_award_PointsRedeemed,
df.award_PointsExpired				as df_award_PointsExpired,
df.award_PointsPurchased			as df_award_PointsPurchased,
df.award_PointsUsed_POS				as df_award_PointsUsed_POS,
df.award_CompsUsed_FB				as df_award_CompsUsed_FB,
df.award_CompsUsed_Other			as df_award_CompsUsed_Other,
df.award_CompsUsed_Merchandise		as df_award_CompsUsed_Merchandise,
df.days_since_last_trip				as df_days_since_last_trip
from [dbo].[v_IQC_Player_Awards_Rollup] (nolock) a 
inner join [tableau].player_dim b (nolock) on a.PlayerId = b.player_id
left join [player].tab_daily_fact df (nolock) on a.PlayerId = df.player_id and a.DATE_KEY = df.DATE_KEY
left join [player].tab_player_hist_dim c (nolock) on a.PlayerId = c.player_id and a.DATE_KEY between c.START_DATE_KEY and c.END_DATE_KEY
left join [VCR].tab_geo_dim d (nolock) on isnull(c.player_zip, b.player_zip) = d.geo_zip
GO


