USE [CMP13]
GO

SELECT 
  [PlayerID]
, [TranId]
, [TranCode]
, COUNT(*)

      --,[GamingDt]
      --,[Shift]
      --,[Outlet]
      --,[EmpID]
      --,[AuthEmpID]
      --,[PostDtm]
      --,[ComputerName]
      --,[TripDt]
      --,[GroupCode]
      --,[PlayerTypeCode]
      --,[CasinoCode]
      --,[DeptCode]
      --,[AreaCode]
      --,[LocnCode]
      --,[GameCode]
      --,[DenomCode]
      --,[DocumentNo]
      --,[IsVoid]
      --,[AwardID]
      --,[AwardID2]
      --,[PrizeCode]
      --,[PrizeQty]
      --,[GamePts]
      --,[BasePts]
      --,[GameBasePts]
      --,[BonusPts]
      --,[EarnedPts]
      --,[AdjPtsDr]
      --,[AdjPtsCr]
      --,[RedeemPts]
      --,[NetPts]
      --,[ExpirePts]
      --,[BaseStubs]
      --,[BonusStubs]
      --,[EarnedStubs]
      --,[AdjStubsDr]
      --,[AdjStubsCr]
      --,[RedeemStubs]
      --,[NetStubs]
      --,[ExpireStubs]
      --,[Promo1]
      --,[BonusPromo1]
      --,[AdjPromo1Dr]
      --,[AdjPromo1Cr]
      --,[Promo1Used]
      --,[NetPromo1]
      --,[Promo2]
      --,[BonusPromo2]
      --,[AdjPromo2Dr]
      --,[AdjPromo2Cr]
      --,[Promo2Used]
      --,[ExpirePromo1]
      --,[ExpirePromo2]
      --,[NetPromo2]
      --,[AuthAward]
      --,[AwardUsed]
      --,[EarnedComp]
      --,[AdjCompDr]
      --,[AdjCompCr]
      --,[CompUsed]
      --,[PtsBal]
      --,[CompBal]
      --,[AltCompBal]
      --,[StubsBal]
      --,[Promo1Bal]
      --,[Promo2Bal]
      --,[NetComp]
      --,[EarnedAltComp]
      --,[ExpireComp]
      --,[ExpireAltComp]
      --,[NetAltComp]
      --,[AwardCode]
      --,[Room]
      --,[Entertainment]
      --,[Food]
      --,[Travel]
      --,[Merchandise]
      --,[Other]
      --,[PromoCredit]
      --,[CashAward]
      --,[MachineCredit]
      --,[eCOUPON]
      --,[Ref1]
      --,[Ref2]
      --,[VoidTranId]
      --,[ItemID]
      --,[IsOpenItem]
      --,[ItemCode]
      --,[IssueTrMasID]
      --,[VoidSubfunction]
      --,[TranClass]
      --,[TranType]
  FROM [dbo].[viewAwardsViejas]

GROUP BY 
  [PlayerID]
, [TranId]
, [TranCode]
HAVING COUNT(*) > 1

GO


