--BACKUP DATABASE CMKTCRYPTO TO  DISK = N'\\CMKTDB13BPR\SQLBackup\CMKTCRYPTO.bak'
--WITH NOFORMAT, INIT, COPY_ONLY, STATS = 5
--GO

BACKUP DATABASE CMP_RATING TO  DISK = N'\\CMKTDB13BPR\SQLBackup\CMP_RATING.bak'
WITH NOFORMAT, INIT, COPY_ONLY, STATS = 5
GO

--BACKUP DATABASE CMP13 TO  DISK = N'\\CMKTDB13BPR\SQLBackup\CMP13.bak'
--WITH NOFORMAT, INIT, COPY_ONLY, STATS = 5
--GO

BACKUP DATABASE CMPAPI TO  DISK = N'\\CMKTDB13BPR\SQLBackup\CMPAPI.bak'
WITH NOFORMAT, INIT, COPY_ONLY, STATS = 5
GO

BACKUP DATABASE CMPSDS TO  DISK = N'\\CMKTDB13BPR\SQLBackup\CMPSDS.bak'
WITH NOFORMAT, INIT, COPY_ONLY, STATS = 5
GO

BACKUP DATABASE dbInfogenesis TO  DISK = N'\\CMKTDB13BPR\SQLBackup\dbInfogenesis.bak'
WITH NOFORMAT, INIT, COPY_ONLY, STATS = 5
GO

BACKUP DATABASE PKMS_OBJ TO  DISK = N'\\CMKTDB13BPR\SQLBackup\PKMS_OBJ.bak'
WITH NOFORMAT, INIT, COPY_ONLY, STATS = 5
GO

BACKUP DATABASE PrintManager TO  DISK = N'\\CMKTDB13BPR\SQLBackup\PrintManager.bak'
WITH NOFORMAT, INIT, COPY_ONLY, STATS = 5
GO

BACKUP DATABASE TV13 TO  DISK = N'\\CMKTDB13BPR\SQLBackup\TV13.bak'
WITH NOFORMAT, INIT, COPY_ONLY, STATS = 5
GO

BACKUP DATABASE TVAlert13 TO  DISK = N'\\CMKTDB13BPR\SQLBackup\TVAlert13.bak'
WITH NOFORMAT, INIT, COPY_ONLY, STATS = 5
GO

BACKUP DATABASE vCMSUpdate TO  DISK = N'\\CMKTDB13BPR\SQLBackup\vCMSUpdate.bak'
WITH NOFORMAT, INIT, COPY_ONLY, STATS = 5
GO

BACKUP DATABASE ZipCodes TO  DISK = N'\\CMKTDB13BPR\SQLBackup\ZipCodes.bak'
WITH NOFORMAT, INIT, COPY_ONLY, STATS = 5
GO