USE [SSISDB];
GO
OPEN MASTER KEY DECRYPTION BY PASSWORD = N'Viejas123123456789'; -- Password used when creating SSISDB
ALTER MASTER KEY REGENERATE WITH ENCRYPTION BY PASSWORD = N'Viejas123456';
GO