USE master;
GO

ALTER DATABASE [iQ-Gaming]
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO

DBCC CHECKDB ('iQ-Gaming',REPAIR_ALLOW_DATA_LOSS) WITH ALL_ERRORMSGS, NO_INFOMSGS; 
GO

USE master;
GO

ALTER DATABASE [iQ-Gaming]
SET MULTI_USER;
GO