----------------------------------------------
-- CMP13
----------------------------------------------
USE [master]
ALTER DATABASE CMP13 SET  SINGLE_USER WITH ROLLBACK IMMEDIATE
GO

USE [master]
RESTORE DATABASE CMP13
FROM  DISK = N'\\DBAMBK01pr\SQLBackup03\CMKTMC13PR$CMKTAG13pr\CMP13\CMKTMC13PR$CMKTAG13pr_CMP13_FULL_20201102_033447.bak' 
WITH  
  FILE = 1
, MOVE N'CMKTDB13_Data'  TO N'K:\UserDBdata\CMP13_data.mdf'
, MOVE N'CMKTDB13_Data2' TO N'K:\UserDBdata\CMP13_data2.ndf'
, MOVE N'CMKTDB13_Log'   TO N'L:\UserDBlog\CMP13_log.ldf'
, NOUNLOAD
, REPLACE
, NORECOVERY
, STATS = 5
GO

USE [master]
RESTORE DATABASE CMP13
FROM  DISK = N'\\DBAMBK01pr\SQLBackup03\CMKTMC13PR$CMKTAG13pr\CMP13\CMKTMC13PR$CMKTAG13pr_CMP13_DIFF_20201104_040007.bak'
WITH  
  FILE = 1
, MOVE N'CMKTDB13_Data'  TO N'K:\UserDBdata\CMP13_data.mdf'
, MOVE N'CMKTDB13_Data2' TO N'K:\UserDBdata\CMP13_data2.ndf'
, MOVE N'CMKTDB13_Log'   TO N'L:\UserDBlog\CMP13_log.ldf'
, NOUNLOAD
, RECOVERY
, STATS = 5
GO

USE [master]
ALTER DATABASE CMP13 SET	MULTI_USER 
GO