--CASH_VARIANCE

CREATE DATABASE [CASH_VARIANCE]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CASH_VARIANCE_data', FILENAME = N'K:\UserDBdata\CASH_VARIANCE_data.mdf' , SIZE = 102400KB , FILEGROWTH = 102400KB )
 LOG ON 
( NAME = N'CASH_VARIANCE_log', FILENAME = N'L:\UserDBlog\CASH_VARIANCE_log.ldf' , SIZE = 51200KB , FILEGROWTH = 51200KB )
GO


--COMMON_SECURITY

CREATE DATABASE [COMMON_SECURITY]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'COMMON_SECURITY_data', FILENAME = N'K:\UserDBdata\COMMON_SECURITY_data.mdf' , SIZE = 102400KB , FILEGROWTH = 102400KB )
 LOG ON 
( NAME = N'COMMON_SECURITY_log', FILENAME = N'L:\UserDBlog\COMMON_SECURITY_log.ldf' , SIZE = 51200KB , FILEGROWTH = 51200KB )
GO


--COMMUNITY_RELATIONS

CREATE DATABASE [COMMUNITY_RELATIONS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'COMMUNITY_RELATIONS_data', FILENAME = N'K:\UserDBdata\COMMUNITY_RELATIONS_data.mdf' , SIZE = 102400KB , FILEGROWTH = 102400KB )
 LOG ON 
( NAME = N'COMMUNITY_RELATIONS_log', FILENAME = N'L:\UserDBlog\COMMUNITY_RELATIONS_log.ldf' , SIZE = 51200KB , FILEGROWTH = 51200KB )
GO


--FLOORVIZ

CREATE DATABASE [FLOORVIZ]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FLOORVIZ_data', FILENAME = N'K:\UserDBdata\FLOORVIZ_data.mdf' , SIZE = 102400KB , FILEGROWTH = 102400KB )
 LOG ON 
( NAME = N'FLOORVIZ_log', FILENAME = N'L:\UserDBlog\FLOORVIZ_log.ldf' , SIZE = 51200KB , FILEGROWTH = 51200KB )
GO


--ICBWebReportsII

CREATE DATABASE [ICBWebReportsII]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ICBWebReportsII_data', FILENAME = N'K:\UserDBdata\ICBWebReportsII_data.mdf' , SIZE = 102400KB , FILEGROWTH = 102400KB )
 LOG ON 
( NAME = N'ICBWebReportsII_log', FILENAME = N'L:\UserDBlog\ICBWebReportsII_log.ldf' , SIZE = 51200KB , FILEGROWTH = 51200KB )
GO


--IView_Ordering

CREATE DATABASE [IView_Ordering]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'IView_Ordering_data', FILENAME = N'K:\UserDBdata\IView_Ordering_data.mdf' , SIZE = 102400KB , FILEGROWTH = 102400KB )
 LOG ON 
( NAME = N'IView_Ordering_log', FILENAME = N'L:\UserDBlog\IView_Ordering_log.ldf' , SIZE = 51200KB , FILEGROWTH = 51200KB )
GO


--iView_Ordering_Dbg

CREATE DATABASE [iView_Ordering_Dbg]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'iView_Ordering_Dbg_data', FILENAME = N'K:\UserDBdata\iView_Ordering_Dbg_data.mdf' , SIZE = 102400KB , FILEGROWTH = 102400KB )
 LOG ON 
( NAME = N'iView_Ordering_Dbg_log', FILENAME = N'L:\UserDBlog\iView_Ordering_Dbg_log.ldf' , SIZE = 51200KB , FILEGROWTH = 51200KB )
GO

--JUNKET_REPORTING

CREATE DATABASE [JUNKET_REPORTING]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'JUNKET_REPORTING_data', FILENAME = N'K:\UserDBdata\JUNKET_REPORTING_data.mdf' , SIZE = 102400KB , FILEGROWTH = 102400KB )
 LOG ON 
( NAME = N'JUNKET_REPORTING_log', FILENAME = N'L:\UserDBlog\JUNKET_REPORTING_log.ldf' , SIZE = 51200KB , FILEGROWTH = 51200KB )
GO


--KIOSK

CREATE DATABASE [KIOSK]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'KIOSK_data', FILENAME = N'K:\UserDBdata\KIOSK_data.mdf' , SIZE = 102400KB , FILEGROWTH = 102400KB )
 LOG ON 
( NAME = N'KIOSK_log', FILENAME = N'L:\UserDBlog\KIOSK_log.ldf' , SIZE = 51200KB , FILEGROWTH = 51200KB )
GO


--POKER_IVIEW

CREATE DATABASE [POKER_IVIEW]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'POKER_IVIEW_data', FILENAME = N'K:\UserDBdata\POKER_IVIEW_data.mdf' , SIZE = 102400KB , FILEGROWTH = 102400KB )
 LOG ON 
( NAME = N'POKER_IVIEW_log', FILENAME = N'L:\UserDBlog\POKER_IVIEW_log.ldf' , SIZE = 51200KB , FILEGROWTH = 51200KB )
GO


--SLOT_PARTICIPATION

CREATE DATABASE [SLOT_PARTICIPATION]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SLOT_PARTICIPATION_data', FILENAME = N'K:\UserDBdata\SLOT_PARTICIPATION_data.mdf' , SIZE = 102400KB , FILEGROWTH = 102400KB )
 LOG ON 
( NAME = N'SLOT_PARTICIPATION_log', FILENAME = N'L:\UserDBlog\SLOT_PARTICIPATION_log.ldf' , SIZE = 51200KB , FILEGROWTH = 51200KB )
GO


--SLOT_SERVICE

CREATE DATABASE [SLOT_SERVICE]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SLOT_SERVICE_data', FILENAME = N'K:\UserDBdata\SLOT_SERVICE_data.mdf' , SIZE = 102400KB , FILEGROWTH = 102400KB )
 LOG ON 
( NAME = N'SLOT_SERVICE_log', FILENAME = N'L:\UserDBlog\SLOT_SERVICE_log.ldf' , SIZE = 51200KB , FILEGROWTH = 51200KB )
GO


--TITLE31

CREATE DATABASE [TITLE31]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TITLE31_data', FILENAME = N'K:\UserDBdata\TITLE31_data.mdf' , SIZE = 102400KB , FILEGROWTH = 102400KB )
 LOG ON 
( NAME = N'TITLE31_log', FILENAME = N'L:\UserDBlog\TITLE31_log.ldf' , SIZE = 51200KB , FILEGROWTH = 51200KB )
GO



