ALTER DATABASE [CCMData] SET EMERGENCY;
GO
ALTER DATABASE [CCMData] set single_user
GO
DBCC CHECKDB ([CCMData], REPAIR_ALLOW_DATA_LOSS) WITH ALL_ERRORMSGS;
GO
ALTER DATABASE [CCMData] set multi_user
GO