--CREATE NONCLUSTERED INDEX NCI_DPA_RECOMMENDED_1 ON SDSVJPRD.VOUCHER.TRANS 
--(
-- TRANS_TYPE_ID
--,STAT_ID
--,TRANS_BARCODE
--,TRANS_PLAYER_ID
--) 
--INCLUDE 
--(
-- TKT_ID
--,TRANS_LOCATION_NUMBER
--,TRANS_DATETIME
--)


CREATE NONCLUSTERED INDEX NCI_DPA_RECOMMENDED_2 ON SDSVJPRD.VOUCHER.TRANS 
(
 TRANS_TYPE_ID
,GAME_DATE
) 
INCLUDE 
(
 TRANS_ID
,TKT_ID
,TRANS_LOCATION_NUMBER
,ASST_ID
,TRANS_DATETIME
)