USE [iQ-Gaming]
GO

DROP TABLE IF EXISTS [dbo].[IQC_Awards_by_Bucket]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[IQC_Awards_by_Bucket](
	[PLAYERID] [int] NOT NULL,
	[GamingDate] [date] NOT NULL,
	[MARKET_GROUP] [varchar](16) NOT NULL,
	[SUB_MARKET_GROUP] [varchar](12) NOT NULL,
	[AWARD_TYPE] [varchar](13) NOT NULL,
	[AWARD_BUCKET] [varchar](35) NOT NULL,
	[WEEK] [char](1) NULL,
	[MONTH] [varchar](9) NULL,
	[QUARTER] [char](1) NULL,
	[YEAR] [char](4) NULL,
	[VALUE] [money] NULL,
 CONSTRAINT [PK_IQC_Awards_by_Bucket] PRIMARY KEY CLUSTERED 
(
	[PLAYERID] ASC,
	[GamingDate] ASC,
	[MARKET_GROUP] ASC,
	[SUB_MARKET_GROUP] ASC,
	[AWARD_TYPE] ASC,
	[AWARD_BUCKET] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


