--SQL Server instance SDSRPT13bp - There is 1 table in [SDSBNGPRD_Archive] that is at least 90 percent fragmented.
--    [ACCOUNTING].[REVENUE_METER_SNAPSHOT] is 99.30% fragmented.

ALTER INDEX ALL ON [SDSBNGPRD_Archive].[ACCOUNTING].[REVENUE_METER_SNAPSHOT] REORGANIZE;  

ALTER INDEX ALL ON [SDSBNGPRD_Archive].[ACCOUNTING].[REVENUE_METER_SNAPSHOT] REBUILD WITH (ONLINE = ON)