EXECUTE DBA.[dbo].[IndexOptimize] 
  @Databases = 'EveriTitle31'
, @Indexes = 'ALL_INDEXES'
, @FragmentationLow = NULL
, @FragmentationMedium = 'INDEX_REORGANIZE,INDEX_REBUILD_ONLINE,INDEX_REBUILD_OFFLINE'
, @FragmentationHigh = 'INDEX_REBUILD_ONLINE,INDEX_REBUILD_OFFLINE'
, @FragmentationLevel1 = 5
, @FragmentationLevel2 = 30
, @SortInTempdb = 'Y'
, @MaxDOP = 0
, @FillFactor = NULL
, @PadIndex = NULL
, @LOBCompaction = 'Y'
, @UpdateStatistics = 'ALL'
, @OnlyModifiedStatistics = 'Y'
, @StatisticsSample = NULL
, @StatisticsResample = 'N'
, @PartitionLevel = 'Y'
, @MinNumberOfPages = 1
--, @TimeLimit = 0
, @Delay = NULL
, @LogToTable = 'Y'