--Set new password --must be on original SQL server
ALTER MASTER KEY REGENERATE WITH ENCRYPTION BY PASSWORD = '6CgcqVuY##' 
 
--if above is successful, "re-sync" the encryption with MRI
OPEN MASTER KEY DECRYPTION BY PASSWORD = '6CgcqVuY##'
ALTER MASTER KEY ADD ENCRYPTION BY SERVICE MASTER KEY
GO
CLOSE MASTER KEY



OPEN MASTER KEY DECRYPTION BY PASSWORD = '6CgcqVuY##'

SELECT @@VERSION