SELECT ALL
    rn.resort,---property concered--a(all)
    rn.resv_name_id,--primary key --u(update)
    e.resort room_resort, --added to enhance performance for queries starting from reservation_daily_elements
    DECODE((DECODE(rn.resv_status,'RESERVED',-1,'PROSPECT',-1,1)+DECODE((TRUNC(pms_p.business_date,'DD')-TRUNC(rn.begin_date)),0,1,2)),
    0,'DUE IN',
    DECODE(
       (DECODE(rn.resv_status,'CHECKED IN',-1,1)+DECODE((TRUNC(pms_p.business_date,'DD')-TRUNC(rn.end_date)),0,1,2)),
             0,'DUE OUT',
             DECODE((DECODE(rn.resv_status,'CHECKED IN',-1,1)+
             DECODE(
             (ABS(TRUNC(pms_p.business_date,'DD')-TRUNC(rn.end_date))/
             DECODE((TRUNC(rn.end_date)-TRUNC(pms_p.business_date,'DD')),0,1,
             (TRUNC(rn.end_date)-TRUNC(pms_p.business_date,'DD')))),-1,1,2)),
             0,'PENDING CHECKOUT',
             DECODE((DECODE((ASCII(nvl(rn.walkin_yn,'N'))-ASCII('Y')),0,-2,-1)+
             DECODE(rn.resv_status,'RESERVED',1,'PROSPECT',1,'CHECKED IN',1,-1)+
             DECODE((TRUNC(pms_p.business_date,'DD')-TRUNC(rn.begin_date,'DD')),0,1,-2)),0,'WALKIN',rn.resv_status)
        ))) computed_resv_status,---display only(do)
    rn.resv_status,--do
    rn.begin_date arrival,--this also contains the time component-a
    decode(to_char(rn.begin_date,'HH24:MI'),'00:00',null,to_char(rn.begin_date,'HH24:MI')) arrival_time,--do
    (TRUNC(rn.end_date,'DD')-TRUNC(rn.begin_date,'DD')) nights,--a
    rn.end_date departure,--a
    decode(to_char(rn.end_date,'HH24:MI'),'00:00',null,to_char(rn.end_date,'HH24:MI')) departure_time,--do
    reservation_ref.get_confirmation_letter(rn.resort,rn.resv_name_id) confirmation_letter,--do
    reservation_ref.get_confirmation_letter_id(rn.resort,rn.resv_name_id) confirmation_letter_id,--
    reservation_ref.get_resv_conf_letter_id(rn.resort,rn.resv_name_id) resv_conf_letter_id,
    reservation_ref.get_resv_conf_letter_status(rn.resort,rn.resv_name_id) resv_conf_letter_status,
    reservation_ref.get_resv_conf_letter_lta(rn.resort,rn.resv_name_id) resv_conf_letter_lta,
    reservation_ref.get_resv_cl_destination(rn.resort,rn.resv_name_id) resv_cl_destination,
    reservation_ref.get_resv_cl_destination_id(rn.resort,rn.resv_name_id) resv_cl_destination_id,
    rn.payment_method,--payment_methods.payment_method
    reservation_ref.get_payment_method_desc(rn.payment_method) payment_method_desc,
    reservation_ref.get_credit_card_number(rn.credit_card_id) credit_card_number,
    reservation_ref.get_credit_card_exp_date(rn.credit_card_id) credit_card_exp_date,
    reservation_ref.get_credit_card_type(rn.payment_method, rn.resort) credit_card_type,
    reservation_ref.get_swcard_issue_number(rn.credit_card_id) swcard_issue_number,
    reservation_ref.get_swcard_start_date(rn.credit_card_id) swcard_start_date,
    'Y' attach_cc_to_profile,rn.posting_allowed_yn,rn.print_rate_yn,rn.confirmation_no,
    rn.SGUEST_FIRSTNAME sfirst_guest_name,--- this alias is different for backward compatibility
    rn.GUEST_LAST_NAME guest_name,
    rn.GUEST_FIRST_NAME ,
    rn.GUEST_LAST_NAME_SDX,
    rn.GUEST_FIRST_NAME_SDX,
    reservation_ref.get_guest_phone_no(rn.phone_id) guest_phone,
    reservation_ref.get_guest_country(rn.address_id) guest_country,
    reservation_ref.get_country_desc(reservation_ref.get_guest_country(rn.address_id)) guest_country_desc,
    rn.name_id guest_name_id,
    rn.phone_id,
    rn.address_id,
    rn.name_usage_type,--'DG','AG','CN'
    rn.display_color room_plan_color,
    rn.do_not_move_room,
    rn.walkin_yn,
    rn.arrival_transport_type,
    rn.arrival_station_code ,
    rn.arrival_carrier_code ,
    rn.arrival_transport_code,
    rn.arrival_date_time ,
    rn.arrival_estimate_time,--not using
    rn.arrival_tranportation_yn,
    rn.arrival_comments,
    rn.departure_transport_type,
    rn.departure_station_code ,
    rn.departure_carrier_code ,
    rn.departure_transport_code ,
    rn.departure_date_time,
    rn.departure_estimate_time,--not using
    rn.departure_transportation_yn,
    rn.departure_comments ,
    rn.cancellation_no,
    rn.cancellation_date,
    rn.cancellation_reason_code,
    rn.CANCELLATION_REASON_DESC,
    rn.wl_reason_code,
    rn.wl_priority,
    rn.wl_reason_description,
    rn.actual_check_in_date,
    rn.actual_check_out_date,
    rn.trunc_actual_check_out_date,
    rn.original_end_date,
    rn.guarantee_code,
    reservation_ref.get_guarantee_code_desc(rn.guarantee_code,rn.resort) guarantee_code_desc,
    reservation_ref.get_comments(rn.resort,rn.resv_name_id,
                                 decode(rn.resv_status, 'CHECKED IN', 'IN HOUSE', 'CHECKED OUT', 'IN HOUSE',
                                        'RESERVATION')) comments,
    reservation_ref.get_special_requests(rn.resort,rn.resv_name_id) special_requests,
    reservation_ref.get_products(rn.resort,rn.resv_name_id) products,
    reservation_ref.get_promotions(rn.resort,rn.resv_name_id) promotions,
    rn.consumer_yn,--not used
    rn.financially_responsible_yn,
    rn.intermediary_yn,--not used
    rn.parent_resv_name_id,
    rn.party_code,
    rn.external_reference,
    rn.credit_limit,--not used
    rn.insert_date,
    business_date_created,
    rn.insert_user ,rn.update_date,rn.update_user ,
    rn.name_tax_type name_tax_type,
    reservation_ref.get_name_tax_description(rn.name_tax_type) name_tax_description,
    rn.tax_exempt_no,
    dn.discount_amt,
    dn.discount_prcnt,
    dn.discount_reason_code,
    rn.commission_paid,
    rn.membership_id,
    reservation_ref.get_membership_number(rn.resort, rn.resv_name_id, rn.membership_id) membership_number,
    reservation_ref.get_membership_type(rn.resort, rn.resv_name_id, rn.membership_id) membership_type,
    reservation_ref.get_membership_level(rn.resort, rn.resv_name_id, rn.membership_id) membership_level,
    rn.event_id,
    rn.revenue_type_code,
    dn.fixed_rate_yn,
    dn.adults,
    dn.children,
    dn.share_amount ,
    dn.base_rate_amount my_room_rate,
    dn.share_prcnt,--not used
    dn.company_id,
    reservation_ref.get_name(dn.company_id) company_name,
    reservation_ref.get_name(dn.travel_agent_id) travel_agent_name,
    dn.travel_agent_id,
    DECODE(dn.group_id,NULL,rn.party_code,reservation_ref.get_name(dn.group_id)) group_name,
    dn.group_id,reservation_ref.get_name(dn.source_id) source_name,dn.source_id,
    e.origin_of_booking,
    reservation_ref.get_booking_origin_desc(e.origin_of_booking) origin_of_booking_desc,
    e.market_code,
    reservation_ref.get_market_desc (e.market_code) market_desc,
    dn.rate_code,
    e.allotment_header_id ,
    reservation_ref.get_block_code(rn.resort,e.allotment_header_id) block_code,
    sc_activity.get_bookname(e.allotment_header_id) block_description,
    e.room_class,
    e.room_category,
    reservation_ref.get_room_category_label(e.room_category,e.resort) room_category_label,
    e.booked_room_category,
    reservation_ref.get_room_category_label(e.booked_room_category,e.resort) booked_room_category_label,
    reservation_ref.get_psuedo_room_type(e.room_category,e.resort) psuedo_room_type,
    e.quantity no_of_rooms,
    e.room,
    e.original_base_rate,
    e.base_rate_amount ,
    e.room_cost,--not used
    e.rate_amount effective_rate_amount,
    dn.currency_code,
    NULL exchange_rate, --e.exchange_rate,
    dn.exchange_posting_type,
    e.reservation_date,--do
    dn.reservation_date rden_reservation_date,---- SRB 07/25
    reservation_ref.has_any_share_fixed_rate_yn(rn.resort,rn.resv_name_id,e.reservation_date) has_any_share_fixed_rate_yn,
    e.resv_daily_el_seq share_id,
    nvl('QUERIED', 'QUERIED') sys_status,
    reservation_ref.is_multiple(rn.resort,rn.resv_name_id) multiple_yn,
    reservation_ref.is_multiple_room_category(rn.resort,rn.resv_name_id) multiple_room_category_yn,
    reservation_ref.is_multiple_room(rn.resort,rn.resv_name_id) multiple_room_yn,
    reservation_ref.is_multiple_booked_room_cat(rn.resort,rn.resv_name_id) multiple_booked_room_cat_yn,
    reservation_ref.is_multiple_rate_code(rn.resort,rn.resv_name_id) multiple_rate_code_yn,
    reservation_ref.is_multiple_market_code(rn.resort,rn.resv_name_id) multiple_market_code_yn,
    reservation_ref.is_multiple_origin_of_booking(rn.resort,rn.resv_name_id) multiple_origin_of_booking_yn,
    reservation_ref.is_multiple_share_amount(rn.resort,rn.resv_name_id) multiple_share_amount_yn,
    reservation_ref.is_multiple_adults(rn.resort,rn.resv_name_id) multiple_adults_yn,
    reservation_ref.is_multiple_children(rn.resort,rn.resv_name_id) multiple_children_yn,
    reservation_ref.is_multiple_fixed_rate(rn.resort,rn.resv_name_id) multiple_fixed_rate,
    reservation_ref.is_multiple_memberships_yn(rn.resort, rn.resv_name_id) multiple_memberships_yn,
    reservation_ref.is_shared_yn(rn.resort,rn.resv_name_id) shared_yn,reservation_ref.is_accompanying_yn(rn.resort,rn.resv_name_id) accompanying_yn,
    reservation_ref.is_message_yn(rn.resort,rn.resv_name_id) message_yn,reservation_ref.is_trace_yn(rn.resort,rn.resv_name_id) trace_yn,
    reservation_ref.is_routing_yn(rn.resort,rn.resv_name_id) routing_yn,
    reservation_ref.is_folio_yn(rn.resort,rn.resv_name_id) folio_yn,
    reservation_ref.is_locator_yn(rn.resort,rn.resv_name_id) locator_yn,
    reservation_ref.is_mealplan_yn(rn.resort,rn.resv_name_id) mealplan_yn,
    reservation_ref.is_authorised_billing_yn(rn.resort,rn.resv_name_id) authorised_billing_yn,
    reservation_ref.multiple_comments_yn(rn.resort,rn.resv_name_id) multiple_comments_yn,
    reservation_ref.preferred_room_type(rn.resort,rn.name_id) preferred_room_type,
    reservation_ref.last_room(rn.resort,rn.name_id) last_room,
    reservation_ref.suite_with(rn.resort,rn.resv_name_id) suite_with,
    rn.contact_name_id,
    rn.credit_card_id,
    rn.commission_code,
    rn.resv_no,
    reservation_ref.get_fixed_charge(rn.resort,rn.resv_name_id) fixed_charge,--do
    reservation_ref.get_payment(rn.resort,rn.resv_name_id) payment_amount,--do
    reservation_ref.get_revenue(rn.resort,rn.resv_name_id,'FB') fb_revenue,--do
    reservation_ref.get_revenue(rn.resort,rn.resv_name_id,'ROOM') room_revenue,--do
    reservation_ref.get_revenue(rn.resort,rn.resv_name_id,'TOTAL') total_revenue,--do
    reservation_ref.accompanying_guests(rn.resort,rn.resv_name_id) accompanying_names,--do
    reservation_ref.guest_balance(rn.resort,rn.resv_name_id) balance,--do
    reservation_ref.is_complimentary_yn(rn.resort,rn.resv_name_id) complimentary_yn,--do
    rn.room_features,rn.wl_telephone_no,rn.video_checkout_yn,
    null override_inventory_yn,
    null reinstate_yn,
    null break_to_empty_room_yn,
    null do_not_update_profile,
    null recalculate_rate_yn,
    null in_person_to_share_with,
    rn.trunc_begin_date trunc_arrival,
    rn.trunc_end_date trunc_departure,
    rn.sguest_name,
    rn.channel,
    rn.share_seq_no,  -- requirement from cris
    e.ext_seq_no, -- requirement from cris
    e.ext_seg_no, -- requirement from cris
    rn.guest_signature, -- requirement for palm to store signature.
    rn.hurdle,  -- requirement for business events
    rn.hurdle_override, -- requirement for business events
    rn.rateable_value,  -- requirement for business events
    rn.restriction_override,  -- requirement for business events
    rn.yieldable_yn,  -- requirement for business events
    rn.extension_id,
    reservation_ref.get_extn_number(rn.resort, rn.resv_name_id, rn.extension_id) extn_number, -- gets the extn number
    reservation_ref.get_extn_type(rn.resort, rn.resv_name_id, rn.extension_id) extn_type, -- gets the extn type
    reservation_ref.is_multiple_extensions_yn(rn.resort, rn.resv_name_id) multiple_extensions_yn,
    e.cribs,
    e.extra_beds,
    NVL(dn.resv_contact_id,rn.resv_contact_id) AS resv_contact_id,
    reservation_ref.get_name(NVL(dn.resv_contact_id,rn.resv_contact_id), 'F,') resv_contact_name,
    NVL(dn.billing_contact_id,rn.billing_contact_id) AS billing_contact_id,
    reservation_ref.get_name(NVL(dn.billing_contact_id,rn.billing_contact_id), 'F,') billing_contact_name,
    reservation_ref.is_multiple_segments_yn(rn.resort, rn.resv_name_id) multiple_segments_yn,
    rn.UDFC01 rg_udfc01,
    rn.UDFC02 rg_udfc02,
    rn.UDFC03 rg_udfc03,
    rn.UDFC04 rg_udfc04,
    rn.UDFC05 rg_udfc05,
    rn.UDFC06 rg_udfc06,
    rn.UDFC07 rg_udfc07,
    rn.UDFC08 rg_udfc08,
    rn.UDFC09 rg_udfc09,
    rn.UDFC10 rg_udfc10,
    rn.UDFC11 rg_udfc11,
    rn.UDFC12 rg_udfc12,
    rn.UDFC13 rg_udfc13,
    rn.UDFC14 rg_udfc14,
    rn.UDFC15 rg_udfc15,
    rn.UDFC16 rg_udfc16,
    rn.UDFC17 rg_udfc17,
    rn.UDFC18 rg_udfc18,
    rn.UDFC19 rg_udfc19,
    rn.UDFC20 rg_udfc20,
    rn.UDFC21 rg_udfc21,
    rn.UDFC22 rg_udfc22,
    rn.UDFC23 rg_udfc23,
    rn.UDFC24 rg_udfc24,
    rn.UDFC25 rg_udfc25,
    rn.UDFC26 rg_udfc26,
    rn.UDFC27 rg_udfc27,
    rn.UDFC28 rg_udfc28,
    rn.UDFC29 rg_udfc29,
    rn.UDFC30 rg_udfc30,
    rn.UDFC31 rg_udfc31,
    rn.UDFC32 rg_udfc32,
    rn.UDFC33 rg_udfc33,
    rn.UDFC34 rg_udfc34,
    rn.UDFC35 rg_udfc35,
    rn.UDFC36 rg_udfc36,
    rn.UDFC37 rg_udfc37,
    rn.UDFC38 rg_udfc38,
    rn.UDFC39 rg_udfc39,
    rn.UDFC40 rg_udfc40,
    rn.UDFD01 rg_udfd01,
    rn.UDFD02 rg_udfd02,
    rn.UDFD03 rg_udfd03,
    rn.UDFD04 rg_udfd04,
    rn.UDFD05 rg_udfd05,
    rn.UDFD06 rg_udfd06,
    rn.UDFD07 rg_udfd07,
    rn.UDFD08 rg_udfd08,
    rn.UDFD09 rg_udfd09,
    rn.UDFD10 rg_udfd10,
    rn.UDFD11 rg_udfd11,
    rn.UDFD12 rg_udfd12,
    rn.UDFD13 rg_udfd13,
    rn.UDFD14 rg_udfd14,
    rn.UDFD15 rg_udfd15,
    rn.UDFD16 rg_udfd16,
    rn.UDFD17 rg_udfd17,
    rn.UDFD18 rg_udfd18,
    rn.UDFD19 rg_udfd19,
    rn.UDFD20 rg_udfd20,
    rn.UDFN01 rg_udfn01,
    rn.UDFN02 rg_udfn02,
    rn.UDFN03 rg_udfn03,
    rn.UDFN04 rg_udfn04,
    rn.UDFN05 rg_udfn05,
    rn.UDFN06 rg_udfn06,
    rn.UDFN07 rg_udfn07,
    rn.UDFN08 rg_udfn08,
    rn.UDFN09 rg_udfn09,
    rn.UDFN10 rg_udfn10,
    rn.UDFN11 rg_udfn11,
    rn.UDFN12 rg_udfn12,
    rn.UDFN13 rg_udfn13,
    rn.UDFN14 rg_udfn14,
    rn.UDFN15 rg_udfn15,
    rn.UDFN16 rg_udfn16,
    rn.UDFN17 rg_udfn17,
    rn.UDFN18 rg_udfn18,
    rn.UDFN19 rg_udfn19,
    rn.UDFN20 rg_udfn20,
    rn.UDFN21 rg_udfn21,
    rn.UDFN22 rg_udfn22,
    rn.UDFN23 rg_udfn23,
    rn.UDFN24 rg_udfn24,
    rn.UDFN25 rg_udfn25,
    rn.UDFN26 rg_udfn26,
    rn.UDFN27 rg_udfn27,
    rn.UDFN28 rg_udfn28,
    rn.UDFN29 rg_udfn29,
    rn.UDFN30 rg_udfn30,
    rn.UDFN31 rg_udfn31,
    rn.UDFN32 rg_udfn32,
    rn.UDFN33 rg_udfn33,
    rn.UDFN34 rg_udfn34,
    rn.UDFN35 rg_udfn35,
    rn.UDFN36 rg_udfn36,
    rn.UDFN37 rg_udfn37,
    rn.UDFN38 rg_udfn38,
    rn.UDFN39 rg_udfn39,
    rn.UDFN40 rg_udfn40,
    rn.res_insert_source,
    rn.res_insert_source_type,
    rn.master_share,
    rn.registration_card_no,
    rn.tiad,
    dn.adults_tax_free,
    dn.children_tax_free,
    rn.purpose_of_stay,
    'N' maintain_room_features,
    e.physical_quantity,
    rn.reinstate_date,
    reservation_ref.is_multiple_cribs_yn(rn.resort, rn.resv_name_id) multiple_cribs_yn,
    reservation_ref.is_multiple_xbeds_yn(rn.resort, rn.resv_name_id) multiple_xbeds_yn,
    reservation_ref.get_card_usage(rn.credit_card_id) card_usage,
    rn.purge_date,
    rn.last_settle_date last_direct_bill_batch_date,
    rn.last_periodic_folio_date,
    rn.periodic_folio_freq,
    rn.confirmation_leg_no,
    n.name_id,
    n.name_type,
    name_resv_cr.get_nc_descrp(n.name_type)                         name_type_desc,
    NVL(n.contact_yn,'N')                        contact_yn,
    NVL(n.last,n.company)                        name,
    NVL(n.last,n.company)||decode(n.first,NULL,'',', '||n.first) display_name,
    n.first,
    n.middle,
    n.name2,
    n.name3,
    n.sname,
    CASE WHEN nvl(name_ref.is_prof_encryption_active_yn,'N') = 'Y' THEN
      opds_main.id_no_str(nvl(name_ref.get_name_document_passport_no(rn.resort, n.name_id), n.passport))
    ELSE
      opds_main.id_no(nvl(name_ref.get_name_document_passport_no(rn.resort, n.name_id),n.passport))
    END AS passport,
    CASE WHEN nvl(name_ref.is_prof_encryption_active_yn,'N') = 'Y' THEN
           NULL
         WHEN n.birth_date_str IS NOT NULL THEN
           opds_main.dob(n.birth_date_str)
         ELSE
           n.birth_date
    END AS birth_date,
    n.title,
    NAME_REF.get_title_name(n.title) title_name,
    reservation_ref.get_title_desc(n.title) title_desc,
    n.language,
    NAME_REF.get_language_name(n.language) language_name,
    reservation_ref.get_language_desc(n.language) language_desc,
    n.nationality,
    NAME_REF.get_nationality_name(n.nationality) nationality_desc,
    n.salutation,    -- n.letter_greeting,
    n.salutation letter_greeting,
    name_resv_cr.get_address_type(n.name_id) address_type,
    name_resv_cr.get_address_id(n.name_id) name_address_id,
    name_resv_cr.get_address1(n.name_id)  address1,
    name_resv_cr.get_address2(n.name_id)  address2,
    name_resv_cr.get_address3(n.name_id)  address3,
    name_resv_cr.get_address4(n.name_id) address4,
    name_resv_cr.get_city(n.name_id) city,
    name_resv_cr.get_state(n.name_id) state,
    NAME_REF.get_state_name(name_resv_cr.get_state(n.name_id), name_resv_cr.get_country(n.name_id)) state_desc,
    name_resv_cr.get_country(n.name_id) country,
    NAME_REF.get_country_name(name_resv_cr.get_country(n.name_id))      country_desc,
    name_resv_cr.get_zip_code(n.name_id) zip_code,
    name_resv_cr.get_city_ext(n.name_id) city_ext,
    n.dept_id,
    n.department,
    NAME_REF.get_phone_id(n.name_id,'PHONE')   name_phone_id,
    NAME_REF.get_phone_no(n.name_id,'PHONE')   phone_no,
    NAME_REF.get_phone_type(n.name_id,'PHONE') phone_type,
    NAME_REF.get_phone_id(n.name_id,'FAX' )    fax_id,
    NAME_REF.get_phone_no(n.name_id,'FAX' )    fax_no,
    NAME_REF.get_phone_id(n.name_id,'EMAIL' )  email_id,
    NAME_REF.get_phone_no(n.name_id,'EMAIL' )  email,
    NVL(n.active_yn,'Y')                       active_yn,
    n.history_yn,
    n.acct_contact,
    NVL(n.cash_bl_ind,'N')                     cbl_ind,
    n.bl_msg,
    n.vip_status,
    name_ref.get_vip_name(n.vip_status)       vip_name,
    reservation_ref.get_vip_desc(n.vip_status) vip_desc,
    n.business_title,
    NAME_REF.get_primary_rate(n.name_id)      name_rate_code,
    NAME_REF.get_arNumber(n.name_id)          ar_no,
    nvl(n.mail_list, decode(fin_trx_i.get_parameter('PRIVACY'), 'Y', fin_trx_i.get_parameter('PRIVACY_DEFAULT_OPTED_IN'))) mail_list,
    n.mail_type,
    n.availability_override,
    n.interest,
    NAME_REF.get_ownerinfo(n.name_id,'SREPNAME')     salesrep,
    NAME_REF.get_ownerinfo(n.name_id,'SREPCODE')     srep_code,
    NAME_REF.get_ownerinfo(n.name_id,'SREPID')       srep_id,
    NAME_REF.get_comment(n.name_id)                  name_comment,
    NAME_REF.get_billing_instr(n.name_id)                     billing_instr,  --SCR 91120
    NAME_REF.get_membership_number(n.name_id)        name_membership_number,
    NAME_REF.get_membership_type(n.name_id)          name_membership_type,
    NAME_REF.get_membership_level(n.name_id)         name_membership_level,
    NAME_REF.get_comm_code(n.name_id)                name_commission_code,
    NAME_REF.get_comm_currency_code(n.name_id)       name_currency_code,
    n.comm_pay_central,
    n.name_code                                      iata_corp_no,
    n.iata_comp_type,
    n.summ_ref_cc,
    n.crs_nameid,
    NAME_REF.get_PotentialInfo(n.name_id,'REVENUE')  potential_revenue,
    NAME_REF.get_PotentialInfo(n.name_id,'NIGHTS' )  potential_nights,
    n.influence,
    n.udfc01 name_udfc01,
    n.udfc02 name_udfc02,
    n.udfc03 name_udfc03,
    n.udfc04 name_udfc04,
    n.udfc05 name_udfc05,
    n.udfc06 name_udfc06,
    n.udfc07 name_udfc07,
    n.udfc08 name_udfc08,
    n.udfc09 name_udfc09,
    n.udfc10 name_udfc10,
    n.udfc11 name_udfc11,
    n.udfc12 name_udfc12,
    n.udfc13 name_udfc13,
    n.udfc14 name_udfc14,
    n.udfc15 name_udfc15,
    n.udfc16 name_udfc16,
    n.udfc17 name_udfc17,
    n.udfc18 name_udfc18,
    n.udfc19 name_udfc19,
    n.udfc20 name_udfc20,
    n.udfc21 name_udfc21,
    n.udfc22 name_udfc22,
    n.udfc23 name_udfc23,
    n.udfc24 name_udfc24,
    n.udfc25 name_udfc25,
    n.udfc26 name_udfc26,
    n.udfc27 name_udfc27,
    n.udfc28 name_udfc28,
    n.udfc29 name_udfc29,
    n.udfc30 name_udfc30,
    n.udfc31 name_udfc31,
    n.udfc32 name_udfc32,
    n.udfc33 name_udfc33,
    n.udfc34 name_udfc34,
    n.udfc35 name_udfc35,
    n.udfc36 name_udfc36,
    n.udfc37 name_udfc37,
    n.udfc38 name_udfc38,
    n.udfc39 name_udfc39,
    n.udfc40 name_udfc40,
    n.udfn01 name_udfn01,
    n.udfn02 name_udfn02,
    n.udfn03 name_udfn03,
    n.udfn04 name_udfn04,
    n.udfn05 name_udfn05,
    n.udfn06 name_udfn06,
    n.udfn07 name_udfn07,
    n.udfn08 name_udfn08,
    n.udfn09 name_udfn09,
    n.udfn10 name_udfn10,
    n.udfn11 name_udfn11,
    n.udfn12 name_udfn12,
    n.udfn13 name_udfn13,
    n.udfn14 name_udfn14,
    n.udfn15 name_udfn15,
    n.udfn16 name_udfn16,
    n.udfn17 name_udfn17,
    n.udfn18 name_udfn18,
    n.udfn19 name_udfn19,
    n.udfn20 name_udfn20,
    n.udfn21 name_udfn21,
    n.udfn22 name_udfn22,
    n.udfn23 name_udfn23,
    n.udfn24 name_udfn24,
    n.udfn25 name_udfn25,
    n.udfn26 name_udfn26,
    n.udfn27 name_udfn27,
    n.udfn28 name_udfn28,
    n.udfn29 name_udfn29,
    n.udfn30 name_udfn30,
    n.udfn31 name_udfn31,
    n.udfn32 name_udfn32,
    n.udfn33 name_udfn33,
    n.udfn34 name_udfn34,
    n.udfn35 name_udfn35,
    n.udfn36 name_udfn36,
    n.udfn37 name_udfn37,
    n.udfn38 name_udfn38,
    n.udfn39 name_udfn39,
    n.udfn40 name_udfn40,
    n.udfd01 name_udfd01,
    n.udfd02 name_udfd02,
    n.udfd03 name_udfd03,
    n.udfd04 name_udfd04,
    n.udfd05 name_udfd05,
    n.udfd06 name_udfd06,
    n.udfd07 name_udfd07,
    n.udfd08 name_udfd08,
    n.udfd09 name_udfd09,
    n.udfd10 name_udfd10,
    n.udfd11 name_udfd11,
    n.udfd12 name_udfd12,
    n.udfd13 name_udfd13,
    n.udfd14 name_udfd14,
    n.udfd15 name_udfd15,
    n.udfd16 name_udfd16,
    n.udfd17 name_udfd17,
    n.udfd18 name_udfd18,
    n.udfd19 name_udfd19,
    n.udfd20 name_udfd20,
    n.account_type,
    n.tracecode,
    n.priority,
    n.rooms_potential,
    n.industry_code,
    n.competition_code,
    n.scope,
    n.scope_city,
    n.territory,
    n.actioncode,
    NAME_REF.get_default_keyword(n.name_id)        keyword,
    n.accountsource,
    n.markets,
    name_ref.get_name_preferences(n.name_id, pms_p.resort, 'INTERESTS') product_interest,
    n.download_resort,
    n.download_srep,
    n.download_date,
    n.upload_date,
    n.insert_date name_insert_date,
    n.update_date name_update_date,
    n.insert_user name_insert_user,
    n.update_user name_update_user,
    NAME_REF.get_UserName(n.insert_user)           insert_user_name,
    NAME_REF.get_UserName(n.update_user)           update_user_name,
    hold_code,
    NAME_REF.hasAttachments(n.name_id,n.name_type) hasAttachments,
    NAME_REF.hasNotes(n.name_id) hasNotes,
    profile_1.get_profile_last_rate(n.name_id)     last_rate,
    profile_1.get_last_room(n.name_id)             name_last_room,
    profile_1.get_profile_last_stay(n.name_id)     last_stay,
    NAME_REF.get_total_nights(n.name_id)           total_nights,
    NAME_REF.get_total_stays(n.name_id)            total_stay,
    NAME_REF.get_total_cancels(n.name_id)          total_cancels,
    NAME_REF.get_total_no_shows(n.name_id)         total_no_shows,
    NAME_REF.get_total_revenue(n.name_id)          name_total_revenue,
    NAME_REF.get_total_day_use(n.name_id)          total_day_use,
    NAME_REF.get_total_nights_lastyr(n.name_id)    total_nights_lastyr,
    NAME_REF.get_total_stays_lastyr(n.name_id)     total_stay_lastyr,
    NAME_REF.get_total_cancels_lastyr(n.name_id)   total_cancels_lastyr,
    NAME_REF.get_total_no_shows_lastyr(n.name_id)  total_no_shows_lastyr,
    NAME_REF.get_total_revenue_lastyr(n.name_id)   total_revenue_lastyr,
    NAME_REF.get_total_day_use_lastyr(n.name_id)   total_day_use_lastyr,
    NAME_REF.check_multi_add(n.name_id)            multiple_address_yn,
    NAME_REF.check_multi_phone(n.name_id)          multiple_phones_yn,
    NAME_REF.has_comments_yn(n.name_id)            multiple_name_comments_yn,
    n.tax1_no,
    n.tax2_no,
    NAME_REF.get_name_keywords(n.name_id) name_keywords,
    NAME_REF.get_comm_account_id(n.name_id) commission_account_id,
    NAME_REF.get_comm_account_name(n.name_id) commission_account_name,
    n.gender,
    n.birth_place,
    n.birth_country,
    n.profession,
    n.id_type,
    CASE WHEN nvl(name_ref.is_prof_encryption_active_yn,'N') = 'Y' THEN
      opds_main.id_no_str(nvl(name_ref.get_name_document_id_number(rn.resort, n.name_id), n.id_number))
    ELSE
      opds_main.id_no(nvl(name_ref.get_name_document_id_number(rn.resort, n.name_id),n.id_number))
    END  AS id_number,
    name_ref.get_name_document_id_date(rn.resort, n.name_id) id_date,
    name_ref.get_name_document_id_place(rn.resort, n.name_id) id_place,
    name_ref.get_name_document_id_country(rn.resort, n.name_id) id_country,
    NAME_REF.get_communications(n.name_id,'ID',1)      comm1_id,
    NAME_REF.get_communications(n.name_id,'TYPE',1)    comm1_type,
    NAME_REF.get_communications(n.name_id,'VALUE',1)   comm1_value,
    NAME_REF.get_communications(n.name_id,'ID',2)      comm2_id,
    NAME_REF.get_communications(n.name_id,'TYPE',2)    comm2_type,
    NAME_REF.get_communications(n.name_id,'VALUE',2)   comm2_value,
    NAME_REF.get_communications(n.name_id,'ID',3)      comm3_id,
    NAME_REF.get_communications(n.name_id,'TYPE',3)    comm3_type,
    NAME_REF.get_communications(n.name_id,'VALUE',3)   comm3_value,
    NAME_REF.get_membership_id(n.name_id)              name_membership_id,
    NAME_REF.get_mem_expiration_date(n.name_id)        membership_expiration_date,
    NAME_REF.get_mem_name_on_card(n.name_id)           membership_name_on_card,
    NAME_REF.get_credit_card_id(n.name_id)             name_credit_card_id,
    NAME_REF.get_credit_card_type(n.name_id)           name_credit_card_type,
    NAME_REF.get_credit_card_number(n.name_id)         name_credit_card_number,
    NAME_REF.get_credit_card_name(n.name_id)           credit_card_name,
    NAME_REF.get_credit_card_exp_date(n.name_id)       credit_card_expiration_date,
    n.payment_due_days,
    n.sfirst,
    profile_1.get_last_company( n.name_id,n.name_type) company,
    profile_1.get_last_group(n.name_id)                last_group,
    profile_1.get_last_source(n.name_id)               last_source,
    profile_1.get_next_resvnameid(n.name_id)           next_resvnameid,
    profile_1.get_next_stay(n.name_id)                 next_stay,
    name_resv_cr.get_name_of_tax_type(n.name_id) name_of_tax_type,
    NAME_REF.has_CIS_History(n.name_id, n.name_type)   cis_history_yn,
    nvl(n.xLast_name, n.xCompany_name) xname,
    n.xfirst_name   ,
    n.xtitle        ,
    n.xsalutation   ,
    n.sxname        ,
    n.sxfirst_name  ,
    NVL(n.xlast_name, n.xCompany_name)||decode(n.xfirst_name,NULL,'',', '||n.xfirst_name) xDisplay_name,
    n.xcompany_name,
    n.inactive_date,
    n.envelope_greeting,
    n.xenvelope_greeting,
    n.contract_no,
    n.contract_recv_date,
    n.guest_priv_yn,
    n.email_yn,
    n.mail_yn,
    n.direct_bill_batch_type,
    name_resv_cr.get_tax_perc1(n.name_id) tax_perc1,
    name_resv_cr.get_tax_perc2(n.name_id) tax_perc2,
    name_resv_cr.get_tax_perc3(n.name_id) tax_perc3,
    name_resv_cr.get_tax_perc4(n.name_id) tax_perc4,
    name_resv_cr.get_tax_perc5(n.name_id) tax_perc5,
    n.legal_company,
    n.xLanguage,
    NAME_REF.get_language_name(n.xlanguage) xlanguage_desc,
    name_api.get_preferences(rn.name_id,'SPECIALS') profile_special_requests,
    name_api.get_preferences(rn.name_id,'ROOM FEATURES') profile_room_features,
    n.profile_privacy_flg,
    nvl(n.market_research_yn,   decode(fin_trx_i.get_parameter('PRIVACY'), 'Y', fin_trx_i.get_parameter('PRIVACY_DEFAULT_OPTED_IN'))) market_research_yn,
    nvl(n.third_party_yn,       decode(fin_trx_i.get_parameter('PRIVACY'), 'Y', fin_trx_i.get_parameter('PRIVACY_DEFAULT_OPTED_IN'))) third_party_yn,
    nvl(n.autoenroll_member_yn, decode(fin_trx_i.get_parameter('PRIVACY'), 'Y', fin_trx_i.get_parameter('PRIVACY_DEFAULT_OPTED_IN'))) autoenroll_member_yn,
    (SELECT rm.parent_market_code FROM resort_markets rm WHERE rm.resort = e.resort AND rm.market_code = e.market_code AND rm.inactive_date IS null) parent_market_code,
    reservation_ref.getResvMembershipTypes(rn.resort,rn.resv_name_id) all_membership_types,
    rn.key_valid_until,
    decode(awards_pkg.ShowAwardsLampYN(rn.resv_name_id,rn.resort),'Y','Y',null) award_number,
    emp_package.get_srepcode() logged_srep_code,
    decode(pms_p.get_parameter('CROSS_BRAND_RECOGNITION'), 'Y', membership_api.get_enrollment_source(n.name_id), NULL) enrollment_source,
    profile_1.is_first_stay_yn(n.name_id) first_stay_yn,
    pms_p.business_date business_date,
    CASE WHEN n.birth_date_str IS NOT NULL THEN
           CAST(pms_prform01.dob_str(n.birth_date_str) AS VARCHAR2(80))
         WHEN n.birth_date IS NOT NULL THEN
           CASE WHEN nvl(name_ref.is_prof_encryption_active_yn,'N') = 'Y' THEN
                  CAST(opds_main.masked_date() AS VARCHAR2(80))
                ELSE
                  CAST(to_char(n.birth_date, pms_p.date_format()) AS VARCHAR2(80))
           END
         ELSE
           NULL
    END AS birth_date_str,
    CAST(pms_prform01.id_no_str(nvl(name_ref.get_name_document_passport_no(rn.resort, n.name_id),n.passport)) AS VARCHAR2(200)) passport_str,
    CAST(pms_prform01.id_no_str(nvl(name_ref.get_name_document_id_number(rn.resort, n.name_id),n.id_number)) AS VARCHAR2(200)) id_number_str,
    rn.resv_contact_id AS rn_resv_contact_id,
    rn.billing_contact_id AS rn_billing_contact_id,
    dn.resv_contact_id AS rden_resv_contact_id,
    dn.billing_contact_id AS rden_billing_contact_id,
    reservation_ref.inv_item_codes(rn.resort,rn.resv_name_id) inv_item_codes,
    reservation_ref.get_turndown_yn(rn.resort, e.resv_daily_el_seq, e.reservation_date, e.room_category, e.market_code) turndown_yn,
    reservation_ref.get_resv_preferences(rn.resort,rn.resv_name_id) reservation_preferences,
    dn.do_not_move_yn,
    dn.points_eligibility_code,
    to_char(rn.departure_date_time,pms_p.time_format) drop_off_time,
    calc_member.points_to_expire(rn.membership_id,to_date('3112'||to_char(sysdate,'YYYY'),'DDMMYYYY')) points_expiring_this_year,
    mailing_aux.isFirstMembershipUpgradeYN(rn.resort,rn.name_id,rn.resv_name_id,rn.membership_id) first_membership_upgrade_yn,
    mailing_aux.getMembershipJoinDate(rn.membership_id) membership_join_date,
    calc_member.guest_total_stay_nights(rn.name_id,pms_p.business_date-365,pms_p.business_date,'END_DT') number_of_nights_last_365_days,
    calc_member.guest_total_stay_nights(rn.name_id,pms_p.business_date-999999,pms_p.business_date,'END_DT',rn.resort) number_of_nights_at_property,
    calc_member.total_points_available(rn.membership_id) total_number_of_avail_points,
   	reservation_ref.get_checkin_alerts_yn(rn.resort, rn.resv_name_id)  checkin_alerts_yn,
    reservation_ref.get_checkout_alerts_yn(rn.resort, rn.resv_name_id) checkout_alerts_yn,
		reservation_ref.get_inhouse_alerts_yn(rn.resort, rn.resv_name_id)  inhouse_alerts_yn,
  	reservation_ref.get_reservation_alerts_yn(rn.resort, rn.resv_name_id) reservation_alerts_yn,
    reservation_rates.get_resv_rates_str(rn.resort, rn.resv_name_id) all_rate_codes
FROM reservation_name rn,
     name n,
     reservation_daily_elements e,
     reservation_daily_element_name dn
 WHERE rn.resort = DECODE(SYS_CONTEXT('CLIENTCONTEXT','SEARCH_IN_ALL_PROPERTY'),'N',SYS_CONTEXT('CLIENTCONTEXT','RESORT'),rn.resort)
   AND (n.name_id = rn.name_id)
   AND (dn.resort = rn.resort
   AND dn.resv_name_id = rn.resv_name_id
   AND dn.reservation_date = DECODE(SIGN(rn.trunc_end_date -COALESCE(TO_DATE(SYS_CONTEXT('CLIENTCONTEXT','BUSINESS_DATE'),'RRRRMMDD'),TRUNC(SYSTIMESTAMP AT TIME ZONE COALESCE(SYS_CONTEXT('CLIENTCONTEXT','RESORT_TIME_ZONE'),DBTIMEZONE)))),
                                    1,greatest(COALESCE(TO_DATE(SYS_CONTEXT('CLIENTCONTEXT','BUSINESS_DATE'),'RRRRMMDD'),TRUNC(SYSTIMESTAMP AT TIME ZONE COALESCE(SYS_CONTEXT('CLIENTCONTEXT','RESORT_TIME_ZONE'),DBTIMEZONE))), rn.trunc_begin_date ),
                                    rn.trunc_end_date))
   AND (e.resort = dn.resort AND
        e.reservation_date = dn.reservation_date AND
        e.resv_daily_el_seq = dn.resv_daily_el_seq )
   AND (rn.event_id IS NULL OR (rn.event_id IS NOT NULL AND e.room_category NOT LIKE '-%') OR
       (rn.event_id IS NOT NULL AND e.room_category LIKE '-%' AND SYS_CONTEXT('CLIENTCONTE