-- Login: VIEJAS\jchau
CREATE LOGIN [VIEJAS\jchau] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: VIEJAS\dbhardwaj
CREATE LOGIN [VIEJAS\dbhardwaj] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: VIEJAS\APPSWB01DV$
CREATE LOGIN [VIEJAS\APPSWB01DV$] FROM WINDOWS WITH DEFAULT_DATABASE = [COMMON_SECURITY]
 
-- Login: VIEJAS\APPSWB02DV$
CREATE LOGIN [VIEJAS\APPSWB02DV$] FROM WINDOWS WITH DEFAULT_DATABASE = [COMMON_SECURITY]
 
-- Login: VIEJAS\SQuagmire
CREATE LOGIN [VIEJAS\SQuagmire] FROM WINDOWS WITH DEFAULT_DATABASE = [COMMON_SECURITY]
 
-- Login: VIEJAS\swey
CREATE LOGIN [VIEJAS\swey] FROM WINDOWS WITH DEFAULT_DATABASE = [EXCEPTION]
 
-- Login: VIEJAS\DEVTEST06$
CREATE LOGIN [VIEJAS\DEVTEST06$] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: VIEJAS\DEVTEST05$
CREATE LOGIN [VIEJAS\DEVTEST05$] FROM WINDOWS WITH DEFAULT_DATABASE = [COMMON_SECURITY]
 
-- Login: VIEJAS\Outsource_Developers
CREATE LOGIN [VIEJAS\Outsource_Developers] FROM WINDOWS WITH DEFAULT_DATABASE = [EXCEPTION]
 
-- Login: VIEJAS\nbrown
CREATE LOGIN [VIEJAS\nbrown] FROM WINDOWS WITH DEFAULT_DATABASE = [Prod]
 
-- Login: VIEJAS\frxuser
CREATE LOGIN [VIEJAS\frxuser] FROM WINDOWS WITH DEFAULT_DATABASE = [Prod]; ALTER LOGIN [VIEJAS\frxuser] DISABLE
 
-- Login: VIEJAS\APPSWB01PR$
CREATE LOGIN [VIEJAS\APPSWB01PR$] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: VIEJAS\APPSWB02PR$
CREATE LOGIN [VIEJAS\APPSWB02PR$] FROM WINDOWS WITH DEFAULT_DATABASE = [master]

-- Login: VIEJAS\DEVAPS01DV$
CREATE LOGIN [VIEJAS\DEVAPS01DV$] FROM WINDOWS WITH DEFAULT_DATABASE = [COMMON_SECURITY]
 
-- Login: NT AUTHORITY\NETWORK SERVICE
CREATE LOGIN [NT AUTHORITY\NETWORK SERVICE] FROM WINDOWS WITH DEFAULT_DATABASE = [SQL_TRACKING]
 
-- Login: VIEJAS\jchautest
CREATE LOGIN [VIEJAS\jchautest] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: VIEJAS\ITD084SW$
CREATE LOGIN [VIEJAS\ITD084SW$] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: VIEJAS\DEVAPS03Dv$
CREATE LOGIN [VIEJAS\DEVAPS03Dv$] FROM WINDOWS WITH DEFAULT_DATABASE = [KIOSK]
 
-- Login: VIEJAS\DEVAPS04DV$
CREATE LOGIN [VIEJAS\DEVAPS04DV$] FROM WINDOWS WITH DEFAULT_DATABASE = [KIOSK]
 
-- Login: VIEJAS\PKIVWB01PR$
CREATE LOGIN [VIEJAS\PKIVWB01PR$] FROM WINDOWS WITH DEFAULT_DATABASE = [POKER_IVIEW]
 
-- Login: VIEJAS\CASIVC07PR$
CREATE LOGIN [VIEJAS\CASIVC07PR$] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: casivc07user
--CREATE LOGIN [casivc07user] WITH PASSWORD = 0x0100DCAEAB4CB415A3BC7C94BD2740AF1988C48C69BD17A92D99 HASHED, SID = 0x4EB666420D0C08448DB57C55DDF20C02, DEFAULT_DATABASE = [master], CHECK_POLICY = OFF, CHECK_EXPIRATION = OFF
 
-- Login: kioskReport
--CREATE LOGIN [kioskReport] WITH PASSWORD = 0x0100A9253052F27BAF40F7934C18A777DAE269399DD48716D88C HASHED, SID = 0xC4836D8492DA24489094FFB1DCD69501, DEFAULT_DATABASE = [KIOSK], CHECK_POLICY = OFF, CHECK_EXPIRATION = OFF
 
-- Login: VIEJAS\msosis
CREATE LOGIN [VIEJAS\msosis] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: cage_inventory_user
--CREATE LOGIN [cage_inventory_user] WITH PASSWORD = 0x01001FF9AE2860009449EE458C18DE4A5BB74738D49DCD9381AD HASHED, SID = 0x756366F1A2BECA45BA149FF5CF20D2AF, DEFAULT_DATABASE = [CASH_VARIANCE], CHECK_POLICY = OFF, CHECK_EXPIRATION = OFF

-- Login: VIEJAS\ITD012SW$
CREATE LOGIN [VIEJAS\ITD012SW$] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: VIEJAS\tkhanna
CREATE LOGIN [VIEJAS\tkhanna] FROM WINDOWS WITH DEFAULT_DATABASE = [NCOA]
 
-- Login: VIEJAS\gstott
CREATE LOGIN [VIEJAS\gstott] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: VIEJAS\HPlayer
CREATE LOGIN [VIEJAS\HPlayer] FROM WINDOWS WITH DEFAULT_DATABASE = [SLOT_SERVICE]
 
-- Login: JunketUser
--CREATE LOGIN [JunketUser] WITH PASSWORD = 0x01007376B9A3B0170DF6AB5C1FDE4614F6A8DAF67667857075B3 HASHED, SID = 0x8715F7A8BBB51F44A1500ECC757ADE8D, DEFAULT_DATABASE = [SLOT_SERVICE], CHECK_POLICY = OFF, CHECK_EXPIRATION = OFF
 
-- Login: VIEJAS\wifiuser
CREATE LOGIN [VIEJAS\wifiuser] FROM WINDOWS WITH DEFAULT_DATABASE = [SLOT_SERVICE]
 
-- Login: dbamdb02_user
--CREATE LOGIN [dbamdb02_user] WITH PASSWORD = 0x01004872C7B8A535931E7DA9CA9B3C4CFDBA2E8026FD07675143 HASHED, SID = 0xFD69E1516B61874F8EF89CBDE36D7A92, DEFAULT_DATABASE = [master], CHECK_POLICY = OFF, CHECK_EXPIRATION = OFF
 
-- Login: VIEJAS\IVWeb01QA$
CREATE LOGIN [VIEJAS\IVWeb01QA$] FROM WINDOWS WITH DEFAULT_DATABASE = [IVIEW_ORDERING]

-- Login: VIEJAS\DEVAPS02Dv$
CREATE LOGIN [VIEJAS\DEVAPS02Dv$] FROM WINDOWS WITH DEFAULT_DATABASE = [master]

-- Login: VIEJAS\IVWEB01PR$
CREATE LOGIN [VIEJAS\IVWEB01PR$] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: VIEJAS\ORDERWB01QA$
CREATE LOGIN [VIEJAS\ORDERWB01QA$] FROM WINDOWS WITH DEFAULT_DATABASE = [IVIEW_ORDERING]
 
-- Login: VIEJAS\ITD065SW$
CREATE LOGIN [VIEJAS\ITD065SW$] FROM WINDOWS WITH DEFAULT_DATABASE = [COMMON_SECURITY]
 
-- Login: vNotify
CREATE LOGIN [vNotify] WITH PASSWORD = 0x01003B6A5F4FD7DFFF00E2ECEFEADA49BCBAD9C2B8BB9BE829A3 HASHED, SID = 0xC2DCE4321F230B4DAEFE2939080B6B1C, DEFAULT_DATABASE = [SLOT_SERVICE], CHECK_POLICY = OFF, CHECK_EXPIRATION = OFF
 
-- Login: installCMP13
--CREATE LOGIN [installCMP13] WITH PASSWORD = 0x01001469ECE9B5EDBC0DC99ED68EBEF678548A814E874D9B9AEC HASHED, SID = 0x5176BB7A04D35842A85714170A364AF0, DEFAULT_DATABASE = [master], CHECK_POLICY = OFF, CHECK_EXPIRATION = OFF
 
-- Login: viejas\dkhandelwal
CREATE LOGIN [viejas\dkhandelwal] FROM WINDOWS WITH DEFAULT_DATABASE = [master]; REVOKE CONNECT SQL TO [viejas\dkhandelwal]
 
-- Login: VIEJAS\APPSWB04DV$
CREATE LOGIN [VIEJAS\APPSWB04DV$] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: VIEJAS\APPSWB21DV$
CREATE LOGIN [VIEJAS\APPSWB21DV$] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: VIEJAS\APPSWB21QA$
CREATE LOGIN [VIEJAS\APPSWB21QA$] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: VIEJAS\ITAdmin
CREATE LOGIN [VIEJAS\ITAdmin] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: VIEJAS\BCCSWB13QA$
CREATE LOGIN [VIEJAS\BCCSWB13QA$] FROM WINDOWS WITH DEFAULT_DATABASE = [SLOT_SERVICE]
 
-- Login: vService
--CREATE LOGIN [vService] WITH PASSWORD = 0x010097FA751B7AE365F459AAD2D684A76DB618181170291FB5A5 HASHED, SID = 0x89DCBBBBA6C868408E2AB6FAEFBF8187, DEFAULT_DATABASE = [SLOT_SERVICE_PR_TEST], CHECK_POLICY = OFF, CHECK_EXPIRATION = OFF
 
-- Login: VIEJAS\APPSWB22DV$
CREATE LOGIN [VIEJAS\APPSWB22DV$] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: VIEJAS\APPSWB22QA$
CREATE LOGIN [VIEJAS\APPSWB22QA$] FROM WINDOWS WITH DEFAULT_DATABASE = [master]
 
-- Login: VIEJAS\ITAppsSQLadmin
CREATE LOGIN [VIEJAS\ITAppsSQLadmin] FROM WINDOWS WITH DEFAULT_DATABASE = [master]