EXEC sp_resetstatus 'CMP13';
ALTER DATABASE CMP13 SET EMERGENCY
--DBCC checkdb('CMP13')
ALTER DATABASE CMP13 SET SINGLE_USER WITH ROLLBACK IMMEDIATE
DBCC CheckDB ('CMP13', REPAIR_ALLOW_DATA_LOSS)
ALTER DATABASE DBA SET MULTI_USER
ALTER DATABASE DBA SET ONLINE

ALTER DATABASE CMP13 SET RECOVERY SIMPLE