--USE [master]
--RESTORE DATABASE [VIEJAS_OLAP_PROPHIX_FactDb] 
--FROM  DISK = N'\\DBAMBK01PR\SQLBackup02\PRPXDB01PR\VIEJAS_OLAP_PROPHIX_FactDb\FULL\PRPXDB01PR_VIEJAS_OLAP_PROPHIX_FactDb_FULL_20180426_000241.bak' 
--WITH  
--  FILE = 1
--, REPLACE
--, NOUNLOAD
--, STATS = 5
--, RECOVERY
--GO

USE [master]
ALTER DATABASE [PROPHIX_MetadataDb] 
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO

USE [master]
RESTORE DATABASE [PROPHIX_MetadataDb] 
FROM  DISK = N'\\DBAMBK01PR\SQLBackup02\PRPXDB01PR\PROPHIX_MetadataDb\FULL\PRPXDB01PR_PROPHIX_MetadataDb_FULL_20180426_000058.bak' 
WITH  
  FILE = 1
, REPLACE
, NOUNLOAD
, STATS = 5
, RECOVERY
GO

USE [master]
ALTER DATABASE [PROPHIX_MetadataDb] 
SET MULTI_USER;
GO

USE [master]
ALTER DATABASE [ProphixTenant] 
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO

USE [master]
RESTORE DATABASE [ProphixTenant] 
FROM  DISK = N'\\DBAMBK01PR\SQLBackup02\PRPXDB01PR\ProphixTenant\FULL\PRPXDB01PR_ProphixTenant_FULL_20180426_000206.bak' 
WITH  
  FILE = 1
, REPLACE
, NOUNLOAD
, STATS = 5
, RECOVERY
GO

USE [master]
ALTER DATABASE [ProphixTenant] 
SET MULTI_USER;
GO