USE master;
GO

--\\DBAMBK01pr\SQLBACKUP01\Fin_Data_WH.BAK

--RESTORE DATABASE Fin_Data_WH 
--FROM  DISK = N'\\DBAMBK01pr\SQLBACKUP01\Fin_Data_WH.BAK' 
--WITH  
--  FILE = 1
--, MOVE N'Fin_Data_WH_Data' TO N'K:\UserDBdata\Fin_Data_WH_Data.mdf'
--, MOVE N'Fin_Data_WH_Log'  TO N'L:\UserDBlog\Fin_Data_WH_Log.1df'
--, NOUNLOAD
--, REPLACE
--, STATS = 5
--, RECOVERY
--GO

--\\DBAMBK01pr\SQLBACKUP01\LAWSON_EXTRACT.BAK

--RESTORE DATABASE LAWSON_EXTRACT 
--FROM  DISK = N'\\DBAMBK01pr\SQLBACKUP01\LAWSON_EXTRACT.BAK' 
--WITH  
--  FILE = 1
--, MOVE N'LAWSON_EXTRACT_dat' TO N'K:\UserDBdata\LAWSON_EXTRACT_Data.mdf'
--, MOVE N'LAWSON_EXTRACT_log'  TO N'L:\UserDBlog\LAWSON_EXTRACT_Log.1df'
--, NOUNLOAD
--, REPLACE
--, STATS = 5
--, RECOVERY
--GO

--\\DBAMBK01pr\SQLBACKUP01\Logan.BAK

ALTER DATABASE Logan
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO

RESTORE DATABASE Logan 
FROM  DISK = N'\\DBAMBK01pr\SQLBACKUP01\Logan.BAK' 
WITH  
  FILE = 1
, MOVE N'Logan'     TO N'K:\UserDBdata\Logan_Data.mdf'
, MOVE N'Logan_log' TO N'L:\UserDBlog\Logan_Log.1df'
, NOUNLOAD
, REPLACE
, STATS = 5
, RECOVERY
GO

ALTER DATABASE Logan
SET MULTI_USER;
GO

--\\DBAMBK01pr\SQLBACKUP01\PR_Data_DW.BAK

RESTORE DATABASE PR_Data_DW 
FROM  DISK = N'\\DBAMBK01pr\SQLBACKUP01\PR_Data_DW.BAK' 
WITH  
  FILE = 1
, MOVE N'PR_DWData' TO N'K:\UserDBdata\PR_Data_DW_Data.mdf'
, MOVE N'PR_DWLog'  TO N'L:\UserDBlog\PR_Data_DW_Log.1df'
, NOUNLOAD
, REPLACE
, STATS = 5
, RECOVERY
GO

