USE master;
GO

ALTER DATABASE [airwatch]
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO

RESTORE DATABASE [airwatch] 
FROM  DISK = N'\\DBAMBK01PR\SQLBackup02\AIRWDB01PR\airwatch\AIRWDB01PR_airwatch_FULL_20170519_110855.bak' 
WITH  
FILE = 1,  
NOUNLOAD,  
REPLACE,  
STATS = 5
GO

ALTER DATABASE [airwatch]
SET MULTI_USER;
GO

