
USE [master]

ALTER DATABASE [ReportServer]
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE
GO

RESTORE DATABASE [ReportServer] FROM  DISK = N'\\DBAMBK01PR\SQLBackup02\CASIVC08PR$CASIVC08PR\ReportServer\FULL\CASIVC08PR$CASIVC08PR_ReportServer_FULL_20180619_074206.bak' WITH  FILE = 1,  NOUNLOAD,  REPLACE,  STATS = 5

GO


USE [master]

ALTER DATABASE [ReportServerTempDB]
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE
GO

RESTORE DATABASE [ReportServerTempDB] FROM  DISK = N'\\DBAMBK01PR\SQLBackup02\CASIVC08PR$CASIVC08PR\ReportServerTempDB\FULL\CASIVC08PR$CASIVC08PR_ReportServerTempDB_FULL_20180619_074229.bak' WITH  FILE = 1,  NOUNLOAD,  REPLACE,  STATS = 5

GO



