USE [master]
RESTORE DATABASE [CMKTCRYPTO] 
FROM  DISK = N'\\DBAMBK01PR\SQLBackup01\CMKTDB13APR\CMKTCRYPTO\FULL\CMKTDB13APR_CMKTCRYPTO_FULL_20170514_023202.bak' 
WITH  
  FILE = 1
, MOVE N'CMktCrypto' TO N'F:\UserDBdata\CMKTCRYPTO_data.mdf'
, MOVE N'CMktCrypto_log' TO N'G:\UserDBlog\CMKTCRYPTO_log.1df'
, NOUNLOAD
, STATS = 5
, NORECOVERY
GO

USE [master]
RESTORE DATABASE [CMKTCRYPTO] 
FROM  DISK = N'\\DBAMBK01PR\SQLBackup01\CMKTDB13APR\CMKTCRYPTO\DIFF\CMKTDB13APR_CMKTCRYPTO_DIFF_20170515_063002.bak' 
WITH  
  FILE = 1
, MOVE N'CMktCrypto' TO N'F:\UserDBdata\CMKTCRYPTO_data.mdf'
, MOVE N'CMktCrypto_log' TO N'G:\UserDBlog\CMKTCRYPTO_log.1df'
, NOUNLOAD
, STATS = 5
, RECOVERY
GO


USE [master]
RESTORE DATABASE [CMPAPI] 
FROM  DISK = N'\\DBAMBK01PR\SQLBackup01\CMKTMC13PR$CMKTAG13pr\CMPAPI\FULL\CMKTMC13PR$CMKTAG13pr_CMPAPI_FULL_20170514_062921.bak' 
WITH  
  FILE = 1
, MOVE N'CMPAPI' TO N'F:\UserDBdata\CMPAPI_data.mdf'
, MOVE N'CMPAPI_Log' TO N'G:\UserDBlog\CMPAPI_log.1df'
, NOUNLOAD
, STATS = 5
, NORECOVERY
GO

USE [master]
RESTORE DATABASE [CMPAPI] 
FROM  DISK = N'\\DBAMBK01PR\SQLBackup01\CMKTMC13PR$CMKTAG13pr\CMPAPI\DIFF\CMKTMC13PR$CMKTAG13pr_CMPAPI_DIFF_20170515_064134.bak' 
WITH  
  FILE = 1
, MOVE N'CMPAPI' TO N'F:\UserDBdata\CMPAPI_data.mdf'
, MOVE N'CMPAPI_log' TO N'G:\UserDBlog\CMPAPI_log.1df'
, NOUNLOAD
, STATS = 5
, RECOVERY
GO


USE [master]
RESTORE DATABASE [CMPSDS] 
FROM  DISK = N'\\DBAMBK01PR\SQLBackup01\CMKTMC13PR$CMKTAG13pr\CMPSDS\FULL\CMKTMC13PR$CMKTAG13pr_CMPSDS_FULL_20170514_062931.bak' 
WITH  
  FILE = 1
, MOVE N'CMPSDS_data' TO N'F:\UserDBdata\CMPSDS_data.mdf'
, MOVE N'CMPSDS_log' TO N'G:\UserDBlog\CMPSDS_log.1df'
, NOUNLOAD
, STATS = 5
, NORECOVERY
GO

USE [master]
RESTORE DATABASE [CMPSDS] 
FROM  DISK = N'\\DBAMBK01PR\SQLBackup01\CMKTMC13PR$CMKTAG13pr\CMPSDS\DIFF\CMKTMC13PR$CMKTAG13pr_CMPSDS_DIFF_20170515_064136.bak' 
WITH  
  FILE = 1
, MOVE N'CMPSDS_data' TO N'F:\UserDBdata\CMPSDS_data.mdf'
, MOVE N'CMPSDS_log' TO N'G:\UserDBlog\CMPSDS_log.1df'
, NOUNLOAD
, STATS = 5
, RECOVERY
GO


USE [master]
RESTORE DATABASE [dbInfogenesis] 
FROM  DISK = N'\\DBAMBK01PR\SQLBackup01\CMKTMC13PR$CMKTAG13pr\dbInfogenesis\FULL\CMKTMC13PR$CMKTAG13pr_dbInfogenesis_FULL_20170514_063105.bak' 
WITH  
  FILE = 1
, MOVE N'dbInfogenesis_data' TO N'F:\UserDBdata\dbInfogenesis_data.mdf'
, MOVE N'dbInfogenesis_log' TO N'G:\UserDBlog\dbInfogenesis_log.1df'
, NOUNLOAD
, STATS = 5
, NORECOVERY
GO

USE [master]
RESTORE DATABASE [dbInfogenesis] 
FROM  DISK = N'\\DBAMBK01PR\SQLBackup01\CMKTMC13PR$CMKTAG13pr\dbInfogenesis\DIFF\CMKTMC13PR$CMKTAG13pr_dbInfogenesis_DIFF_20170515_064148.bak' 
WITH  
  FILE = 1
, MOVE N'dbInfogenesis_data' TO N'F:\UserDBdata\dbInfogenesis_data.mdf'
, MOVE N'dbInfogenesis_log' TO N'G:\UserDBlog\dbInfogenesis_log.1df'
, NOUNLOAD
, STATS = 5
, RECOVERY
GO


USE [master]
RESTORE DATABASE [PrintManager] 
FROM  DISK = N'\\DBAMBK01PR\SQLBackup01\CMKTMC13PR$CMKTAG13pr\PrintManager\FULL\CMKTMC13PR$CMKTAG13pr_PrintManager_FULL_20170514_063220.bak' 
WITH  
  FILE = 1
, MOVE N'PrintManager_data' TO N'F:\UserDBdata\PrintManager_data.mdf'
, MOVE N'PrintManager_log' TO N'G:\UserDBlog\PrintManager_log.1df'
, NOUNLOAD
, STATS = 5
, NORECOVERY
GO


USE [master]
RESTORE DATABASE [PrintManager] 
FROM  DISK = N'\\DBAMBK01PR\SQLBackup01\CMKTMC13PR$CMKTAG13pr\PrintManager\DIFF\CMKTMC13PR$CMKTAG13pr_PrintManager_DIFF_20170515_064158.bak' 
WITH  
  FILE = 1
, MOVE N'PrintManager_data' TO N'F:\UserDBdata\PrintManager_data.mdf'
, MOVE N'PrintManager_log' TO N'G:\UserDBlog\PrintManager_log.1df'
, NOUNLOAD
, STATS = 5
, RECOVERY
GO


USE [master]
RESTORE DATABASE [TV13] 
FROM  DISK = N'\\DBAMBK01PR\SQLBackup01\CMKTMC13PR$CMKTAG13pr\TV13\FULL\CMKTMC13PR$CMKTAG13pr_TV13_FULL_20170514_063235.bak' 
WITH  
  FILE = 1
, MOVE N'TV13_data' TO N'F:\UserDBdata\TV13_data.mdf'
, MOVE N'TV13_log' TO N'G:\UserDBlog\TV13_log.1df'
, NOUNLOAD
, STATS = 5
, NORECOVERY
GO

USE [master]
RESTORE DATABASE [TV13] 
FROM  DISK = N'\\DBAMBK01PR\SQLBackup01\CMKTMC13PR$CMKTAG13pr\TV13\DIFF\CMKTMC13PR$CMKTAG13pr_TV13_DIFF_20170515_064200.bak' 
WITH  
  FILE = 1
, MOVE N'TV13_data' TO N'F:\UserDBdata\TV13_data.mdf'
, MOVE N'TV13_log' TO N'G:\UserDBlog\TV13_log.1df'
, NOUNLOAD
, STATS = 5
, RECOVERY
GO


USE [master]
RESTORE DATABASE [TVAlert13] 
FROM  DISK = N'\\DBAMBK01PR\SQLBackup01\CMKTMC13PR$CMKTAG13pr\TVAlert13\FULL\CMKTMC13PR$CMKTAG13pr_TVAlert13_FULL_20170514_063238.bak' 
WITH  
  FILE = 1
, MOVE N'TVAlert13_data' TO N'F:\UserDBdata\TVAlert13_data.mdf'
, MOVE N'TVAlert13_log' TO N'G:\UserDBlog\TVAlert13_log.1df'
, NOUNLOAD
, STATS = 5
, NORECOVERY
GO

USE [master]
RESTORE DATABASE [TVAlert13] 
FROM  DISK = N'\\DBAMBK01PR\SQLBackup01\CMKTMC13PR$CMKTAG13pr\TVAlert13\DIFF\CMKTMC13PR$CMKTAG13pr_TVAlert13_DIFF_20170515_064202.bak' 
WITH  
  FILE = 1
, MOVE N'TVAlert13_data' TO N'F:\UserDBdata\TVAlert13_data.mdf'
, MOVE N'TVAlert13_log' TO N'G:\UserDBlog\TVAlert13_log.1df'
, NOUNLOAD
, STATS = 5
, RECOVERY
GO


USE [master]
RESTORE DATABASE [vCMSUpdate] FROM  DISK = N'R:\vCMSUpdate.BAK' WITH  FILE = 1,  MOVE N'vCMSUpdate_data' TO N'F:\UserDBdata\vCMSUpdate_data.mdf',  NOUNLOAD,  STATS = 5
GO

USE [master]
RESTORE DATABASE [CMPAPI] FROM  DISK = N'R:\CMPAPI.BAK' WITH  FILE = 1,  MOVE N'CMPAPI' TO N'F:\UserDBdata\CMPAPI_data.mdf',  NOUNLOAD,  STATS = 5
GO

USE [master]
RESTORE DATABASE [CMP13] 
FROM  DISK = N'\\DBAMBK01PR\SQLBackup01\CMKTMC13PR$CMKTAG13pr\CMP13\FULL\CMKTMC13PR$CMKTAG13pr_CMP13_FULL_20170514_023204.bak' 
WITH  
  FILE = 1
, MOVE N'CMKTDB13_Data' TO N'F:\UserDBdata\CMP13_data.mdf'
, MOVE N'CMKTDB13_Data2' TO N'F:\UserDBdata\CMP13_data2.ndf'
, MOVE N'CMKTDB13_Log' TO N'G:\UserDBlog\CMP13_log.1df'
, NOUNLOAD
, STATS = 5
, NORECOVERY
GO

USE [master]
RESTORE DATABASE [CMP13] 
FROM  DISK = N'\\DBAMBK01PR\SQLBackup01\CMKTMC13PR$CMKTAG13pr\CMP13\DIFF\CMKTMC13PR$CMKTAG13pr_CMP13_DIFF_20170515_063003.bak' 
WITH  
  FILE = 1
, MOVE N'CMKTDB13_Data' TO N'F:\UserDBdata\CMP13_data.mdf'
, MOVE N'CMKTDB13_Data2' TO N'F:\UserDBdata\CMP13_data2.ndf'
, MOVE N'CMKTDB13_Log' TO N'G:\UserDBlog\CMP13_log.1df'
, NOUNLOAD
, STATS = 5
, RECOVERY
GO