USE master
GO

ALTER DATABASE SQLdmRepository SET SINGLE_USER 
WITH ROLLBACK IMMEDIATE;
GO

DBCC CHECKDB ([SQLdmRepository], REPAIR_ALLOW_DATA_LOSS) WITH ALL_ERRORMSGS; --, NO_INFOMSGS; 
GO

ALTER DATABASE SQLdmRepository SET MULTI_USER ;
GO