USE [iQ-Gaming]
GO

/****** Object:  Table [deprecated].[awards_bonus]    Script Date: 5/31/2024 2:45:11 PM ******/
--IF  EXISTS (SELECT * FROM sys.objects WHERE type in (N'U') AND schema_id =21
--DROP TABLE [deprecated].[awards_bonus]
--GO

--SELECT * FROM sys.schemas
--ORDER BY [name]


--SELECT * 
--FROM sys.objects
--WHERE schema_id = 35
----  AND type in (N'D')
----  AND object_id = 246396047

 -----------------------------------------------------------------------
 -- Drop All Objects
 -----------------------------------------------------------------------

DROP TABLE IF EXISTS #DeleteObjects_TBL
GO

SELECT object_id, [name], [type]
INTO #DeleteObjects_TBL
FROM sys.objects
WHERE schema_id = 35

DECLARE @DeleteObjects_CR CURSOR;
DECLARE @TheObjectName varchar(128) ;
DECLARE @TheObjectType char(1) ; 
BEGIN
	SET @DeleteObjects_CR =
	CURSOR FOR
		SELECT cast([name] as varchar(128)), [type] FROM #DeleteObjects_TBL

	OPEN @DeleteObjects_CR 
    FETCH NEXT FROM @DeleteObjects_CR 
    INTO @TheObjectName, @TheObjectType

    WHILE @@FETCH_STATUS = 0
    BEGIN
 
         IF @TheObjectType = 'U'
		 PRINT 'DROP TABLE IF EXISTS [STAY].[' + @TheObjectName + ']'

         IF @TheObjectType = 'D'
		 PRINT 'DROP DEFAULT IF EXISTS [STAY].[' + @TheObjectName + ']'

		 IF @TheObjectType = 'V'
		 PRINT 'DROP VIEW IF EXISTS [STAY].[' + @TheObjectName + ']'

		 IF @TheObjectType = 'P'
		 PRINT 'DROP PROCEDURE IF EXISTS [STAY].[' + @TheObjectName + ']'

      FETCH NEXT FROM @DeleteObjects_CR  
      INTO @TheObjectName, @TheObjectType
    END; 

    CLOSE @DeleteObjects_CR  ;
    DEALLOCATE @DeleteObjects_CR ;
END;

--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__table__002C8B0E]
--DROP PROCEDURE IF EXISTS [deprecated].[PK_player_tab_aggregate_3month_LGD]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_IQC_Rebuild_Player_Daily_Totals_GameDay_TripNumber]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_Push_IQC_Offers_live]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__table__0120AF47]
--DROP TABLE IF EXISTS [deprecated].[tab_aggregate_3month_LGD_players]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_Update_IQC_Player_ID]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__table__0214D380]
--DROP PROCEDURE IF EXISTS [deprecated].[PK_player_tab_aggregate_3month_LGD_players]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_Update_IQC_Player_Trips_AcctDay]
--DROP VIEW IF EXISTS [deprecated].[v_PlayerBalances]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__table__0308F7B9]
--DROP TABLE IF EXISTS [deprecated].[tab_aggregate_6month]
--DROP TABLE IF EXISTS [deprecated].[IQC_Player_Trips_AcctDay]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_Update_IQC_Player_Trips_GameDay]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__table__03FD1BF2]
--DROP PROCEDURE IF EXISTS [deprecated].[PK_player_tab_aggregate_6month]
--DROP PROCEDURE IF EXISTS [deprecated].[PK_IQC_Player_Trips_AccountingDay]
--DROP TABLE IF EXISTS [deprecated].[IQC_Slot_Machines_20220302]
--DROP VIEW IF EXISTS [deprecated].[v_IQC_BUS_Player_Daily_Totals_AcctDay_old]
--DROP VIEW IF EXISTS [deprecated].[v_IQC_Slot_CoinIn_Summary_PerDay]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__table__04F1402B]
--DROP TABLE IF EXISTS [deprecated].[tab_aggregate_12month]
--DROP TABLE IF EXISTS [deprecated].[IQC_Player_Trips_GameDay]
--DROP VIEW IF EXISTS [deprecated].[v_IQH_Hotel_Guests_PerDay]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__other__05E56464]
--DROP PROCEDURE IF EXISTS [deprecated].[PK_player_tab_aggregate_12month]
--DROP PROCEDURE IF EXISTS [deprecated].[PK_IQC_Player_Trips_GamingDay]
--DROP VIEW IF EXISTS [deprecated].[v_IQH_Hotel_Posting_PerDay]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__other__06D9889D]
--DROP TABLE IF EXISTS [deprecated].[tab_merge_dim]
--DROP TABLE IF EXISTS [deprecated].[IQC_Player_ID]
--DROP VIEW IF EXISTS [deprecated].[v_IQB_Transactions_PerDay]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__other__07CDACD6]
--DROP TABLE IF EXISTS [deprecated].[IQC_Player_Ticketstub_20220405]
--DROP PROCEDURE IF EXISTS [deprecated].[PK_player_tab_merge_dim]
--DROP VIEW IF EXISTS [deprecated].[v_IQB_Transaction_Detail_PerDay]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__other__08C1D10F]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_CMP_Update_IQC_Player_ID]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_Opera_Update_IQH_Hotel_Guests_05/09/2022]
--DROP VIEW IF EXISTS [deprecated].[v_IQP_Sales]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__other__09B5F548]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__other__0AAA1981]
--DROP TABLE IF EXISTS [deprecated].[IQC_Slot_Accounting]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_IG_Business_Custom_Update_Tender_PlayerID]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__other__0B9E3DBA]
--DROP PROCEDURE IF EXISTS [deprecated].[PK_IQC_Slot_Accounting]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_Extract_Awards_Data2]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__other__0C9261F3]
--DROP TABLE IF EXISTS [deprecated].[IQC_Slot_Accounting_EXT]
--DROP TABLE IF EXISTS [deprecated].[IQC_Player_Points_20220406]
--DROP TABLE IF EXISTS [deprecated].[tab_award_fact]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__other__0D86862C]
--DROP PROCEDURE IF EXISTS [deprecated].[PK_IQC_Slot_Accounting_EXT]
--DROP VIEW IF EXISTS [deprecated].[v_IQC_Player]
--DROP PROCEDURE IF EXISTS [deprecated].[PK_player_tab_award_fact]
--DROP TABLE IF EXISTS [deprecated].[OfferDetail]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__other__0E7AAA65]
--DROP TABLE IF EXISTS [deprecated].[tab_monthly_fact]
--DROP PROCEDURE IF EXISTS [deprecated].[PK_OfferDetail_TagCode]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__other__0F6ECE9E]
--DROP PROCEDURE IF EXISTS [deprecated].[PK_player_tab_monthly_fact]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__point__1062F2D7]
--DROP TABLE IF EXISTS [deprecated].[tab_offer_fact]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__bonus__11571710]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_CMP_Update_IQC_Player_PointsBal]
--DROP PROCEDURE IF EXISTS [deprecated].[PK_player_tab_offer_fact]
--DROP PROCEDURE IF EXISTS [deprecated].[proc_general_dates_update]
--DROP TABLE IF EXISTS [deprecated].[IQC_Table_Accounting_20220627]
--DROP TABLE IF EXISTS [deprecated].[iQC_Awards_20220125]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__comps__124B3B49]
--DROP VIEW IF EXISTS [deprecated].[V_IQC_Player_Tiers]
--DROP PROCEDURE IF EXISTS [deprecated].[proc_etl_award_fact_PRIZE_BC_C]
--DROP TABLE IF EXISTS [deprecated].[IQC_Table_Accounting_ext_20220627]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__comps__133F5F82]
--DROP VIEW IF EXISTS [deprecated].[V_IQC_Player_Balances]
--DROP VIEW IF EXISTS [deprecated].[v_iQC_Offers_Gaming]
--DROP PROCEDURE IF EXISTS [deprecated].[proc_etl_award_fact_PRIZE_FB_I]
--DROP TABLE IF EXISTS [deprecated].[IQC_slot_Accounting_ext_20220627]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__offer__143383BB]
--DROP VIEW IF EXISTS [deprecated].[v_iqc_player_address]
--DROP PROCEDURE IF EXISTS [deprecated].[proc_etl_award_fact_PRIZE_FP_P]
--DROP TABLE IF EXISTS [deprecated].[IQC_slot_Accounting_20220627]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__offer__1527A7F4]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_Opera_Update_IQH_Hotel_Guests_05/10/2022]
--DROP PROCEDURE IF EXISTS [deprecated].[proc_etl_award_fact_PRIZE_PC_V]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_SDS_Update_IQC_Slot_Accounting_20220627]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__offer__161BCC2D]
--DROP TABLE IF EXISTS [deprecated].[tab_offer_fact_redeem]
--DROP PROCEDURE IF EXISTS [deprecated].[proc_etl_tab_award_fact_read]
--DROP TABLE IF EXISTS [deprecated].[IQC_Slot_Machines_20211109]
--DROP TABLE IF EXISTS [deprecated].[IQC_Awards]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__offer__170FF066]
--DROP TABLE IF EXISTS [deprecated].[tab_offer_dim]
--DROP PROCEDURE IF EXISTS [deprecated].[proc_etl_tab_award_fact_read_old]
--DROP PROCEDURE IF EXISTS [deprecated].[PK_IQC_Awards_RecordID]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__offer__1804149F]
--DROP PROCEDURE IF EXISTS [deprecated].[PK_player_tab_offer_dim]
--DROP TABLE IF EXISTS [deprecated].[IQC_Player_Ratings]
--DROP PROCEDURE IF EXISTS [deprecated].[proc_etl_tab_monthly_fact_read]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_Extract_Awards_Data_20211215]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__award__18F838D8]
--DROP PROCEDURE IF EXISTS [deprecated].[PK_IQC_Player_Ratings]
--DROP PROCEDURE IF EXISTS [deprecated].[proc_maint_award_to_daily_fact]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__award__19EC5D11]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_Extract_Slot_Rating_Data_20220511]
--DROP TABLE IF EXISTS [deprecated].[IQC_Player_Daily_Totals_GameDay]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_Extract_Slot_Accounting_Data_20220126]
--DROP PROCEDURE IF EXISTS [deprecated].[proc_maint_offer_to_daily_fact]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__award__1AE0814A]
--DROP TABLE IF EXISTS [deprecated].[tab_machine_dim]
--DROP TABLE IF EXISTS [deprecated].[IQC_Player_Ratings_20220511]
--DROP PROCEDURE IF EXISTS [deprecated].[PK_IQC_Player_Daily_Totals_GameDay]
--DROP TABLE IF EXISTS [deprecated].[IQC_Slot_Accounting_20220427]
--DROP PROCEDURE IF EXISTS [deprecated].[proc_maint_rating_to_daily_fact]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__award__1BD4A583]
--DROP PROCEDURE IF EXISTS [deprecated].[PK_slot_tab_machine_dim]
--DROP TABLE IF EXISTS [deprecated].[IQC_Player_Daily_Totals_AcctDay_20220511]
--DROP TABLE IF EXISTS [deprecated].[IQC_Player_Daily_Totals_GameDay_EXT]
--DROP TABLE IF EXISTS [deprecated].[IQC_Slot_Accounting_EXT_20220427]
--DROP PROCEDURE IF EXISTS [deprecated].[proc_update_tab_rating_fact_MACHINE_KEY]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__award__1CC8C9BC]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_CMP_Update_IQC_Offers_Live]
--DROP VIEW IF EXISTS [deprecated].[v_iQC_Offers_Live]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_Extract_Awards_Data_20211207]
--DROP TABLE IF EXISTS [deprecated].[IQC_Player_Daily_Totals_AcctDay_EXT_20220511]
--DROP TABLE IF EXISTS [deprecated].[IQC_Awards_20220217]
--DROP PROCEDURE IF EXISTS [deprecated].[PK_IQC_Player_Daily_Totals_GameDay_EXT]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_CMP_Update_IQC_Comp_Dimensions]
--DROP TABLE IF EXISTS [deprecated].[Historical_Slot_Fix_20220427]
--DROP PROCEDURE IF EXISTS [deprecated].[proc_comparison_daily_fact]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__award__1DBCEDF5]
--DROP TABLE IF EXISTS [deprecated].[iQC_Offer_Detail_old]
--DROP VIEW IF EXISTS [deprecated].[v_agg_theo_days_by_type]
--DROP TABLE IF EXISTS [deprecated].[IQC_Player_Daily_Totals_GameDay_20220511]
--DROP TABLE IF EXISTS [deprecated].[IQC_Player_Daily_Totals_AcctDay]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_CMP_Update_IQC_Comps]
--DROP PROCEDURE IF EXISTS [deprecated].[proc_comparison_daily_fact_nick]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__award__1EB1122E]
--DROP VIEW IF EXISTS [deprecated].[v_age_category]
--DROP TABLE IF EXISTS [deprecated].[IQC_Player_Daily_Totals_GameDay_EXT_20220511]
--DROP TABLE IF EXISTS [deprecated].[iQC_Offers_Live_20220719]
--DROP PROCEDURE IF EXISTS [deprecated].[PK_IQC_Player_Daily_Totals_AcctDay]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_CMP_Update_IQC_Player]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__award__1FA53667]
--DROP VIEW IF EXISTS [deprecated].[v_ADT_category]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_Extract_Table_Rating_Data_20220511]
--DROP TABLE IF EXISTS [deprecated].[IQC_Player_Daily_Totals_AcctDay_EXT]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_CMP_Update_IQC_Player_Address]
--DROP TABLE IF EXISTS [deprecated].[IQC_Slot_Accounting_20220428]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__award__20995AA0]
--DROP VIEW IF EXISTS [deprecated].[v_agg_days_frequency]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_Opera_Update_IQH_Hotel_Guests_20220608]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_Extract_Sports_Rating_Data_20220511]
--DROP PROCEDURE IF EXISTS [deprecated].[PK_IQC_Player_Daily_Totals_AcctDay_EXT]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_CMP_Update_IQC_Player_Host]
--DROP TABLE IF EXISTS [deprecated].[IQC_Slot_Accounting_EXT_20220428]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__award__218D7ED9]
--DROP VIEW IF EXISTS [deprecated].[v_frequency]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_CMP_Update_IQC_Player_Ratings]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__award__2281A312]
--DROP TABLE IF EXISTS [deprecated].[IQC_Player_20220413]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_offer__dw_ti__22B6AD3C]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_CMP_Update_IQC_Player_Ratings_EXT]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__award__2375C74B]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_CMP_Update_IQC_Offer_Detail]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_CMP_Update_IQC_Players_Club]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__award__2469EB84]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_datet__dw_ti__249EF5AE]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_SDS_Update_IQC_Slot_Accounting_20220126]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__award__255E0FBD]
--DROP TABLE IF EXISTS [deprecated].[IQ_Marketing_Metrics]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_merge__dws_t__259319E7]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_Opera_Update_IQH_Hotel_Posting_2022/02/18]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__award__265233F6]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_CMP_Update_IQC_Offer_History]
--DROP PROCEDURE IF EXISTS [deprecated].[PK_IQ_Marketing_Metrics]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_Opera_Update_IQH_Hotel_Guests_2022/02/18]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__award__2746582F]
--DROP TABLE IF EXISTS [deprecated].[IQC_Player_Points]
--DROP VIEW IF EXISTS [deprecated].[v_IQC_BUS_Player_Daily_Totals_AcctDay _PerDay]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__award__283A7C68]
--DROP PROCEDURE IF EXISTS [deprecated].[PK_IQC_PLAYER_POINTS]
--DROP VIEW IF EXISTS [deprecated].[v_IQC_BUS_Player_Daily_Totals_GameDay _PerDay]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__award__292EA0A1]
--DROP VIEW IF EXISTS [deprecated].[vw_IQH_Revenue_Postings_test2]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_Opera_Update_IQH_Hotel_Posting_EXT_2022/02/18]
--DROP VIEW IF EXISTS [deprecated].[v_IQC_Comps]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__award__2A22C4DA]
--DROP TABLE IF EXISTS [deprecated].[FINANCIAL_TRANSACTIONS]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__award__2B16E913]
--DROP PROCEDURE IF EXISTS [deprecated].[PK_FINANCIAL_TRANSACTIONS_TRX_NO]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_Extract_Awards_Data_20220117]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__award__2C0B0D4C]
--DROP TABLE IF EXISTS [deprecated].[NAME_RESERVATION]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__award__2CFF3185]
--DROP PROCEDURE IF EXISTS [deprecated].[PK_NAME_RESERVATION_RESV_NAME_ID]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__award__2DF355BE]
--DROP TABLE IF EXISTS [deprecated].[IQC_Player_dbo]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__award__2EE779F7]
--DROP VIEW IF EXISTS [deprecated].[v_PlayerOffers]
--DROP TABLE IF EXISTS [deprecated].[iq_marketing_metrics_20220125]
--DROP PROCEDURE IF EXISTS [deprecated].[PK_IQC_Player]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__award__2FDB9E30]
--DROP TABLE IF EXISTS [deprecated].[iq_marketing_metrics_ext_20220125]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__award__30CFC269]
--DROP TABLE IF EXISTS [deprecated].[IQC_Player_Host]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__award__31C3E6A2]
--DROP TABLE IF EXISTS [deprecated].[iq_marketing_metrics_tmp_AwardsSum2]
--DROP PROCEDURE IF EXISTS [deprecated].[PK_IQC_Player_Host]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__award__32B80ADB]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_CMP_Update_IQC_Player_Tier_Match]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__award__33AC2F14]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__award__34A0534D]
--DROP TABLE IF EXISTS [deprecated].[IQC_Comp_Group]
--DROP TABLE IF EXISTS [deprecated].[TRX_CODES]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__award__35947786]
--DROP PROCEDURE IF EXISTS [deprecated].[PK_IQC_Comp_Group]
--DROP PROCEDURE IF EXISTS [deprecated].[PK_TRX_CODES_RESORT_AND_TRX_CODE]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__dw_ti__36889BBF]
--DROP TABLE IF EXISTS [deprecated].[IQC_Comp_Item]
--DROP TABLE IF EXISTS [deprecated].[IQC_Player_Ratings_20220516]
--DROP PROCEDURE IF EXISTS [deprecated].[PK_IQC_Comp_Item_1]
--DROP TABLE IF EXISTS [deprecated].[IQC_Player_Daily_Totals_AcctDay_20220516]
--DROP TABLE IF EXISTS [deprecated].[IQC_Player_Daily_Totals_AcctDay_EXT_20220516]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_gener__dw_ti__3965086A]
--DROP TABLE IF EXISTS [deprecated].[IQC_Awards_New]
--DROP TABLE IF EXISTS [deprecated].[IQC_Player_Daily_Totals_GameDay_20220516]
--DROP TABLE IF EXISTS [deprecated].[JL_SASCI_TEST]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_machi__dw_ti__3A592CA3]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_CMP_Update_IQC_Comps_EXT]
--DROP TABLE IF EXISTS [deprecated].[IQC_Player_Daily_Totals_GameDay_EXT_20220516]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_offer__DATE___3B4D50DC]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_offer__offer__3C417515]
--DROP TABLE IF EXISTS [deprecated].[IQC_Comps]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_Extract_Awards_Data_DEVWITHREVISIONS_MANUAL]
--DROP TABLE IF EXISTS [deprecated].[IQ_Marketing_Metrics_EXT]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_offer__offer__3D35994E]
--DROP PROCEDURE IF EXISTS [deprecated].[PK_IQC_Comps]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_CMP_Update_IQC_Awards_Dev_MANUAL]
--DROP PROCEDURE IF EXISTS [deprecated].[PK_IQ_Marketing_Metrics_EXT]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_offer__is_re__3E29BD87]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_offer__offer__3F1DE1C0]
--DROP TABLE IF EXISTS [deprecated].[IQC_BUS_Player_Details_20220112]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_offer__dw_ti__401205F9]
--DROP PROCEDURE IF EXISTS [deprecated].[PK_IQC_PLAYER_ID]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_offer__prize__41062A32]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_Extract_Awards_Data_20220104]
--DROP TABLE IF EXISTS [deprecated].[IQC_Slot_Accounting_20220315]
--DROP VIEW IF EXISTS [deprecated].[v_IQC_Comps1]
--DROP PROCEDURE IF EXISTS [deprecated].[PK_IQC_PLAYERS_CLUB]
--DROP TABLE IF EXISTS [deprecated].[JL_Test_CI]
--DROP TABLE IF EXISTS [deprecated].[IQC_Slot_Accounting_EXT_20220315]
--DROP TABLE IF EXISTS [deprecated].[iQC_tPlayer_ClubState_Repl]
--DROP TABLE IF EXISTS [deprecated].[IQC_Players_Club_dbo]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_aggre__Slot___4417A107]
--DROP PROCEDURE IF EXISTS [deprecated].[PK_tPlayerClubStat]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_aggre__Table__450BC540]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_aggre__Other__45FFE979]
--DROP TABLE IF EXISTS [deprecated].[IQC_Awards_20220208]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_aggre__SlotN__46F40DB2]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_Extract_Awards_Data_20220208]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_aggre__Table__47E831EB]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_aggre__Other__48DC5624]
--DROP TABLE IF EXISTS [deprecated].[IQC_Awards_20220224]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_aggre__CompU__49D07A5D]
--DROP TABLE IF EXISTS [deprecated].[IQC_Slot_Machines_20220419]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_iQC_tPlayer_ClubState_Delta_Load]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_award__IsVoi__4F8953B3]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_CMP_Update_IQC_Player_Groups]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_award__award__507D77EC]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_Extract_Awards_Data_DEVWITHREVISIONS_20220115]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_award__award__51719C25]
--DROP TABLE IF EXISTS [deprecated].[IQC_Player_Address_dbo]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_IG_Business_Update_Discounts_Renamed]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_award__award__5265C05E]
--DROP VIEW IF EXISTS [deprecated].[v_iQC_tPlayer_ClubState]
--DROP PROCEDURE IF EXISTS [deprecated].[PK_IQC_Player_Address]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_award__award__5359E497]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_award__award__544E08D0]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_award__award__55422D09]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_award__award__56365142]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_award__award__572A757B]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_award__award__581E99B4]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_award__award__5912BDED]
--DROP TABLE IF EXISTS [deprecated].[IQC_Awards_20220504]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_award__award__5A06E226]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_award__award__5AFB065F]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_award__award__5BEF2A98]
--DROP TABLE IF EXISTS [deprecated].[IQC_Slot_Accounting_20220228]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_Opera_Update_IQH_Hotel_Guests_20220212]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_award__award__5CE34ED1]
--DROP TABLE IF EXISTS [deprecated].[IQC_Slot_Accounting_EXT_20220228]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_award__award__5DD7730A]
--DROP VIEW IF EXISTS [deprecated].[V_IQC_Player_TierPoints]
--DROP TABLE IF EXISTS [deprecated].[IQC_Player]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_award__award__5ECB9743]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_CMP_Update_IQC_Player_Points]
--DROP PROCEDURE IF EXISTS [deprecated].[PK__IQC_Play__4A4E74A8B862A416]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_award__award__5FBFBB7C]
--DROP TABLE IF EXISTS [deprecated].[iQC_Offers_Live_Repl]
--DROP TABLE IF EXISTS [deprecated].[IQC_Player_Address]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_award__award__60B3DFB5]
--DROP PROCEDURE IF EXISTS [deprecated].[PK_IQC_OFFERS_LIVE_REPL]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_award__award__61A803EE]
--DROP VIEW IF EXISTS [deprecated].[vw_IQH_Revenue_Postings_test]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_award__award__629C2827]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_MERGE_iQC_Offers_Live_to_REPL_Table]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_award__award__63904C60]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_award__award__64847099]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_award__award__657894D2]
--DROP TABLE IF EXISTS [deprecated].[IQC_Players_Club]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_Extract_Awards_Data_Dev]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_award__award__666CB90B]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_award__award__6760DD44]
--DROP TABLE IF EXISTS [deprecated].[IQC_Awards_Dev]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_award__award__6855017D]
--DROP TABLE IF EXISTS [deprecated].[IQC_Slot_Machines_20220301]
--DROP PROCEDURE IF EXISTS [deprecated].[PK_IQC_Awards_Dev]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_award__award__694925B6]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_CMP_Update_IQC_Awards_Dev]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_award__award__6A3D49EF]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_award__award__6B316E28]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_award__dw_ti__6C259261]
--DROP VIEW IF EXISTS [deprecated].[V_iQC_Awards_by_month_Dev]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_award__AuthA__6D19B69A]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_award__Award__6E0DDAD3]
--DROP TABLE IF EXISTS [deprecated].[IQC_Awards2]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__gamin__6F01FF0C]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__slot___6FF62345]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__slot___70EA477E]
--DROP TABLE IF EXISTS [deprecated].[IQH_HOTEL_Posting_20222601]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_CMP_Update_IQC_Player_Ticketstubs]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_Extract_Awards_Data_DEVWITHREVISIONS]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__slot___71DE6BB7]
--DROP PROCEDURE IF EXISTS [deprecated].[usp_Snapshot_Refresh_RESERVATIONS]
--DROP TABLE IF EXISTS [deprecated].[IQH_HOTEL_Posting_EXT_20222601]
--DROP TABLE IF EXISTS [deprecated].[IQC_Player_20211108]
--DROP TABLE IF EXISTS [deprecated].[iQ_Campaign_Prize_History1]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__slot___72D28FF0]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_Opera_Update_IQH_Hotel_Posting_20222601]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_Push_IQC_Player]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_Extract_Awards_Data_20211109]
--DROP TABLE IF EXISTS [deprecated].[iQ_Campaign_Prize_History-20220105]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__slot___73C6B429]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_CMP_Update_IQC_Awards]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__slot___74BAD862]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_Extract_Awards_Data_New]
--DROP TABLE IF EXISTS [deprecated].[IQH_Hotel_Guests_20211109]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_Extract_Awards_Data_20220105]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__slot___75AEFC9B]
--DROP TABLE IF EXISTS [deprecated].[tab_datetime_tracker]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__slot___76A320D4]
--DROP TABLE IF EXISTS [deprecated].[iQ_Campaign_Prize_History_20220104]
--DROP PROCEDURE IF EXISTS [deprecated].[PK_config_tab_datetime_tracker]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_Extract_Awards_Data_20220124]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__slot___7797450D]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_CMP_Extract_IQC_Awards_To_delete]
--DROP TABLE IF EXISTS [deprecated].[tab_player_id_pull]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_IQ_Marketing_Metrics_Update]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_Push_IQC_Player_Balances]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__slot___788B6946]
--DROP TABLE IF EXISTS [deprecated].[tab_general_dates]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_IQ_Marketing_Metrics_Update_EXT]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_Push_IQC_Player_Address]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__slot___797F8D7F]
--DROP PROCEDURE IF EXISTS [deprecated].[PK_config_tab_general_dates]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_IQC_Player_Daily_Totals_AcctDay_Update]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__slot___7A73B1B8]
--DROP TABLE IF EXISTS [deprecated].[awards_view]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_IQC_Player_Daily_Totals_AcctDay_Update_EXT]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__table__7B67D5F1]
--DROP TABLE IF EXISTS [deprecated].[awards_bonus]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_IQC_Player_Daily_Totals_GameDay_Update]
--DROP TABLE IF EXISTS [deprecated].[IQC_Awards_Dev_20220106]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__table__7C5BFA2A]
--DROP TABLE IF EXISTS [deprecated].[offer_removal]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_IQC_Player_Daily_Totals_GameDay_Update_EXT]
--DROP TABLE IF EXISTS [deprecated].[IQC_Awards_20220106]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__table__7D501E63]
--DROP TABLE IF EXISTS [deprecated].[T0910000000BEHDNUTEA3DQTC5I]
--DROP TABLE IF EXISTS [deprecated].[tab_aggregate_3month]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_IQC_Player_Trips_AcctDay_Update]
--DROP VIEW IF EXISTS [deprecated].[V_iQC_Awards_by_month_20220106]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__table__7E44429C]
--DROP PROCEDURE IF EXISTS [deprecated].[PK_player_tab_aggregate_3month]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_IQC_Player_Trips_GameDay_Update]
--DROP VIEW IF EXISTS [deprecated].[V_iQC_Awards_by_month_Dev_20220106]
--DROP DEFAULT IF EXISTS [deprecated].[DF__tab_month__table__7F3866D5]
--DROP TABLE IF EXISTS [deprecated].[tab_aggregate_3month_LGD]
--DROP PROCEDURE IF EXISTS [deprecated].[sp_IQC_Rebuild_Player_Daily_Totals_AcctDay_TripNumber]

-- handle system_versioned tables which cannot be dropped
-- below code converts them to basic user tables so they can be dropped

--USE [iQ-Gaming] ;
--GO

--SELECT * 
----[name] 
--FROM sys.tables 
--WHERE [temporal_type_desc] = 'SYSTEM_VERSIONED_TEMPORAL_TABLE'
--  AND [schema_id] = 21

--DECLARE @temporalTableName varchar(max) = (SELECT TOP 1 [name] FROM sys.tables WHERE [temporal_type_desc] = 'SYSTEM_VERSIONED_TEMPORAL_TABLE' AND [schema_id] = 21)
--WHILE @temporalTableName IS NOT NULL
--BEGIN
--    EXEC('ALTER TABLE [deprecated].[' + @temporalTableName + '] SET (SYSTEM_VERSIONING = OFF)')
--    SET @temporalTableName = (SELECT TOP 1 [name] FROM sys.tables WHERE [temporal_type_desc] = 'SYSTEM_VERSIONED_TEMPORAL_TABLE')
--END
--DECLARE @tableName varchar(max) = (SELECT TOP 1 [name] FROM sys.tables)
--WHILE @tableName IS NOT NULL
--BEGIN
--    EXEC('DROP TABLE [deprecated].[' + @tableName + ']')
--    SET @tableName = (SELECT TOP 1 [name] FROM sys.tables)
--END

--DROP TABLE IF EXISTS [deprecated].[OfferDetail]
--DROP PROCEDURE IF EXISTS [deprecated].[PK_OfferDetail_TagCode]
--DROP TABLE IF EXISTS [deprecated].[IQC_Player_dbo]
--DROP PROCEDURE IF EXISTS [deprecated].[PK_IQC_Player]
--DROP TABLE IF EXISTS [deprecated].[IQC_Player_Host]
--DROP PROCEDURE IF EXISTS [deprecated].[PK_IQC_Player_Host]

DROP TABLE IF EXISTS [STAY].[accounting_dates]
DROP TABLE IF EXISTS [STAY].[availability]
DROP PROCEDURE IF EXISTS [STAY].[PK_accounting_dates_id]
DROP PROCEDURE IF EXISTS [STAY].[PK_Stay_Reservations_id]
DROP PROCEDURE IF EXISTS [STAY].[PK_Stay_Reservations_STAGE_id]
DROP TABLE IF EXISTS [STAY].[properties]
DROP TABLE IF EXISTS [STAY].[rate_plans]
DROP TABLE IF EXISTS [STAY].[rate_snapshots]
DROP TABLE IF EXISTS [STAY].[reservations]
DROP TABLE IF EXISTS [STAY].[reservations_STAGE]
DROP TABLE IF EXISTS [STAY].[room_types]
DROP TABLE IF EXISTS [STAY].[rooms]
DROP TABLE IF EXISTS [STAY].[Stay_accounting_dates_TEST]
DROP PROCEDURE IF EXISTS [STAY].[usp_Load_Delta_Stay_Reservations]

