USE [tempdb]
GO
DBCC SHRINKFILE (N'templog' , 0, TRUNCATEONLY)
GO

USE [tempdb]
GO
DBCC SHRINKFILE (N'tempdev' , 0, TRUNCATEONLY)
GO

USE [tempdb]
GO
DBCC SHRINKFILE (N'temp2' , 0, TRUNCATEONLY)
GO

USE [tempdb]
GO
DBCC SHRINKFILE (N'temp3' , 0, TRUNCATEONLY)
GO

USE [tempdb]
GO
DBCC SHRINKFILE (N'temp4' , 0, TRUNCATEONLY)
GO

USE [tempdb]
GO
DBCC SHRINKFILE (N'temp5' , 0, TRUNCATEONLY)
GO

USE [tempdb]
GO
DBCC SHRINKFILE (N'temp6' , 0, TRUNCATEONLY)
GO

USE [tempdb]
GO
DBCC SHRINKFILE (N'temp7' , 0, TRUNCATEONLY)
GO

USE [tempdb]
GO
DBCC SHRINKFILE (N'temp8' , 0, TRUNCATEONLY)
GO

USE [tempdb]
GO
DBCC SHRINKFILE (N'temp9' , 0, TRUNCATEONLY)
GO
