
USE master;
GO

ALTER DATABASE [LepideAD Audit_Aug2021]
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO

USE [LepideAD Audit_Aug2021]
GO
DBCC SHRINKFILE (N'LepideAD Audit_Aug2021_log' , 0, TRUNCATEONLY)
GO


USE master;
GO

ALTER DATABASE [LepideAD Audit_Aug2021]
SET MULTI_USER;
GO

------LepideFSA DB_TRBFS01PR_Aug2021_log

USE master;
GO

ALTER DATABASE [LepideFSA DB_TRBFS01PR_Aug2021]
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO

USE [LepideFSA DB_TRBFS01PR_Aug2021]
GO
DBCC SHRINKFILE (N'LepideFSA DB_TRBFS01PR_Aug2021_log' , 0, TRUNCATEONLY)
GO


USE master;
GO

ALTER DATABASE [LepideFSA DB_TRBFS01PR_Aug2021]
SET MULTI_USER;
GO

------Lepide_OD_Teams_Aug2021_log

USE master;
GO

ALTER DATABASE [Lepide_OD_Teams_Aug2021]
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO

USE [Lepide_OD_Teams_Aug2021]
GO
DBCC SHRINKFILE (N'Lepide_OD_Teams_Aug2021_log' , 0, TRUNCATEONLY)
GO


USE master;
GO

ALTER DATABASE [Lepide_OD_Teams_Aug2021]
SET MULTI_USER;
GO

----LepideAD Audit_Feb2022_log

USE master;
GO

ALTER DATABASE [LepideAD Audit_Feb2022]
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO

USE [LepideAD Audit_Feb2022]
GO
DBCC SHRINKFILE (N'LepideAD Audit_Feb2022_log' , 0, TRUNCATEONLY)
GO


USE master;
GO

ALTER DATABASE [LepideAD Audit_Feb2022]
SET MULTI_USER;
GO

--------------- LepideFSA DB_ENTEFS02BPR_Aug2021_log

USE master;
GO

ALTER DATABASE [LepideFSA DB_ENTEFS02BPR_Aug2021]
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO

USE [LepideFSA DB_ENTEFS02BPR_Aug2021]
GO
DBCC SHRINKFILE (N'LepideFSA DB_ENTEFS02BPR_Aug2021_log' , 0, TRUNCATEONLY)
GO


USE master;
GO

ALTER DATABASE [LepideFSA DB_ENTEFS02BPR_Aug2021]
SET MULTI_USER;
GO

------------------ LepideFSA DB_ENTEFS02APR_Aug2021_log

USE master;
GO

ALTER DATABASE [LepideFSA DB_ENTEFS02APR_Aug2021]
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO

USE [LepideFSA DB_ENTEFS02APR_Aug2021]
GO
DBCC SHRINKFILE (N'LepideFSA DB_ENTEFS02APR_Aug2021_log' , 0, TRUNCATEONLY)
GO


USE master;
GO

ALTER DATABASE [LepideFSA DB_ENTEFS02APR_Aug2021]
SET MULTI_USER;
GO

------------------- LepideFSA DB_GCFILE01_Aug2021_log


USE master;
GO

ALTER DATABASE [LepideFSA DB_GCFILE01_Aug2021]
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO

USE [LepideFSA DB_GCFILE01_Aug2021]
GO
DBCC SHRINKFILE (N'LepideFSA DB_GCFILE01_Aug2021_log' , 0, TRUNCATEONLY)
GO
