USE master;
GO

ALTER DATABASE [Bally_DCM_Core]
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO

ALTER DATABASE [Bally_DCM_Core] SET RECOVERY SIMPLE WITH NO_WAIT;
GO

USE [Bally_DCM_Core];
GO
DBCC SHRINKFILE (N'Bally_DCM_Core_log' , 0, TRUNCATEONLY);
GO

USE [master]
GO
ALTER DATABASE [Bally_DCM_Core] SET RECOVERY FULL WITH NO_WAIT
GO

ALTER DATABASE [Bally_DCM_Core]
SET MULTI_USER;
GO
