DECLARE @CUTOFFDATE DATETIME = DATEADD(DAY,-2,CURRENT_TIMESTAMP);

BEGIN TRAN
INSERT INTO KIOSK..PLAYERS_PROMOTION_LOG_ARCHIVE
SELECT 
  PLAYER_PROMO_ID
, PLAYING_DT
, ACCT_NUM
, PROMOTION_ID
, PRIZE_ID
, LAST_NAME
, FIRST_NAME

FROM KIOSK..PLAYERS_PROMOTION_LOG

WHERE PLAYING_DT < @CUTOFFDATE 

ORDER BY
PLAYING_DT DESC
COMMIT

--EXECUTE DBA.[dbo].[DatabaseBackup] @Databases = 'KIOSK', @Directory = N'\\DBAMBK01pr\SQLBackup01', @BackupType = 'LOG', @CleanupTime = 72, @BackupSoftware = NULL, @Compress  = 'Y', @CopyOnly = 'N', @Verify = 'N', @CheckSum = 'Y', @BufferCount = NULL, @MaxTransferSize = NULL, @BlockSize = NULL, @LogToTable = 'Y'

BEGIN TRAN
DELETE FROM KIOSK..PLAYERS_PROMOTION_LOG
WHERE PLAYING_DT < @CUTOFFDATE
COMMIT