SELECT MAX(ARRIVAL_TS)
FROM [vBus].[dbo].[JUNKET_COMMISSIONS_ARCHIVE]

--SELECT DATEADD(s,1,MAX(ARRIVAL_TS)), DATEADD(day,-1,GETDATE()) FROM JUNKET_COMMISSIONS_ARCHIVE

DECLARE
@StartDate datetime,
@EndDate datetime

SELECT 
  @StartDate = DATEADD(s,1,MAX(ARRIVAL_TS))
, @EndDate = DATEADD(day,-1,GETDATE()) 
FROM dbo.JUNKET_COMMISSIONS_ARCHIVE

PRINT @StartDate

PRINT @EndDate
 
SELECT ARRIVAL_TS
FROM dbo.EVENTS
WHERE ARRIVAL_TS BETWEEN @StartDate AND @EndDate
  AND EVENT_ID NOT IN(SELECT EVENT_ID FROM JUNKET_COMMISSIONS_ARCHIVE WHERE ARRIVAL_TS BETWEEN  @StartDate AND @EndDate)
ORDER BY ARRIVAL_TS