/****** Script for SelectTopNRows command from SSMS  ******/
SELECT [PlayerId]
      ,[ContactTypeId]
      ,[EmailAddress]
      ,[IsEmailSend]
      ,[IsInactive]
      ,[CreatedDtm]
      ,[CreatedBy]
      ,[ModifiedDtm]
      ,[ModifiedBy]
      ,[DataRowVersion]
      ,[email_bounce_dttm]
      ,[recipient_domain_nm]
      ,[reason_txt]
  FROM [CMP13_PLAYER_EMAIL_DEV].[dbo].[tPlayerEmail_HardBounce_Deletes]