/****** CASH_VARIANCE ******/

USE master;
GO

RESTORE DATABASE [CASH_VARIANCE] 
FROM  DISK = N'\\CMKTDB13BPR\SQLBackup\CASIIVC07PR_Migration_To_New_VM_Server\CASH_VARIANCE_full.bak' 
WITH
  MOVE N'CASH_VARIANCE_data' TO N'K:\UserDBdata\CASH_VARIANCE.mdf'
, MOVE N'CASH_VARIANCE_log' TO N'L:\UserDBlog\CASH_VARIANCE_log.ldf'
, REPLACE
, NORECOVERY  
, STATS = 5
GO


/****** COMMON_SECURITY ******/

RESTORE DATABASE [COMMON_SECURITY] 
FROM  DISK = N'\\CMKTDB13BPR\SQLBackup\CASIIVC07PR_Migration_To_New_VM_Server\COMMON_SECURITY_full.bak' 
WITH
  NORECOVERY 
, REPLACE 
, STATS = 5
GO


/****** FLOORVIZ ******/

RESTORE DATABASE [FLOORVIZ] 
FROM  DISK = N'\\CMKTDB13BPR\SQLBackup\CASIIVC07PR_Migration_To_New_VM_Server\FLOORVIZ_full.bak' 
WITH
  MOVE N'FLOORVIZ' TO N'K:\UserDBdata\FLOORVIZ_RESTORE.mdf'
, MOVE N'FLOORVIZ_log' TO N'L:\UserDBlog\FLOORVIZ_RESTORE_1.ldf'
, REPLACE
, NORECOVERY  
, STATS = 5
GO


/****** GUEST_MOBILE ******/

RESTORE DATABASE [GUEST_MOBILE] 
FROM  DISK = N'\\CMKTDB13BPR\SQLBackup\CASIIVC07PR_Migration_To_New_VM_Server\GUEST_MOBILE_full.bak' 
WITH
  MOVE N'GUEST_MOBILE' TO N'K:\UserDBdata\GUEST_MOBILE_RESTORE.mdf'
, MOVE N'GUEST_MOBILE_log' TO N'L:\UserDBlog\GUEST_MOBILE_RESTORE_1.ldf'
, REPLACE
, NORECOVERY  
, STATS = 5
GO


/****** ICBWebReports ******/

RESTORE DATABASE [ICBWebReports] 
FROM  DISK = N'\\CMKTDB13BPR\SQLBackup\CASIIVC07PR_Migration_To_New_VM_Server\ICBWebReports_full.bak' 
WITH
  MOVE N'ICBReports_Data' TO N'K:\UserDBdata\ICBWebReports_RESTORE.mdf'
, MOVE N'ICBReports_log' TO N'L:\UserDBlog\ICBWebReports_RESTORE_1.ldf'
, REPLACE
, NORECOVERY  
, STATS = 5
GO


/****** SLOT_PARTICIPATION ******/

RESTORE DATABASE [SLOT_PARTICIPATION] 
FROM  DISK = N'\\CMKTDB13BPR\SQLBackup\CASIIVC07PR_Migration_To_New_VM_Server\SLOT_PARTICIPATION_full.bak' 
WITH
  MOVE N'SLOT_PARTICIPATION' TO N'K:\UserDBdata\SLOT_PARTICIPATION_RESTORE.mdf'
, MOVE N'SLOT_PARTICIPATION_log' TO N'L:\UserDBlog\SLOT_PARTICIPATION_RESTORE_1.ldf'
, REPLACE
, NORECOVERY  
, STATS = 5
GO


/****** SLOT_SERVICE ******/

RESTORE DATABASE [SLOT_SERVICE] 
FROM  DISK = N'\\CMKTDB13BPR\SQLBackup\CASIIVC07PR_Migration_To_New_VM_Server\SLOT_SERVICE_full.bak' 
WITH
  MOVE N'SLOT_SERVICE_data' TO N'K:\UserDBdata\SLOT_SERVICE_RESTORE.mdf'
, MOVE N'SLOT_SERVICE_log' TO N'L:\UserDBlog\SLOT_SERVICE_RESTORE_1.ldf'
, REPLACE
, NORECOVERY  
, STATS = 5
GO

