USE master;
GO

ALTER DATABASE [CASH_VARIANCE]
SET ONLINE;
ALTER DATABASE [COMMON_SECURITY]
SET ONLINE;
ALTER DATABASE [FLOORVIZ]
SET ONLINE;
ALTER DATABASE [GUEST_MOBILE]
SET ONLINE;
ALTER DATABASE [ICBWebReports]
SET ONLINE;
ALTER DATABASE [SLOT_PARTICIPATION]
SET ONLINE;
ALTER DATABASE [SLOT_SERVICE]
SET ONLINE;