USE [master]
GO
ALTER DATABASE [PartitionThis] MODIFY FILE ( NAME = N'PartitionThis', MAXSIZE = UNLIMITED)
GO
ALTER DATABASE [PartitionThis] MODIFY FILE ( NAME = N'PartitionThis_log', MAXSIZE = UNLIMITED)
GO

ALTER DATABASE [PartitionThis] ADD FILE ( NAME = N'QuarterlyF01', FILENAME = N'E:\SQL_DB_files\QuarterlyF01.ndf' , SIZE = 524288KB , FILEGROWTH = 262144KB ) TO FILEGROUP [QuarterlyFG01]
GO
ALTER DATABASE [PartitionThis] ADD FILE ( NAME = N'QuarterlyF02', FILENAME = N'E:\SQL_DB_files\QuarterlyF02.ndf' , SIZE = 524288KB , FILEGROWTH = 262144KB ) TO FILEGROUP [QuarterlyFG02]
GO
ALTER DATABASE [PartitionThis] ADD FILE ( NAME = N'QuarterlyF03', FILENAME = N'E:\SQL_DB_files\QuarterlyF03.ndf' , SIZE = 524288KB , FILEGROWTH = 262144KB ) TO FILEGROUP [QuarterlyFG03]
GO
ALTER DATABASE [PartitionThis] ADD FILE ( NAME = N'QuarterlyF04', FILENAME = N'E:\SQL_DB_files\QuarterlyF04.ndf' , SIZE = 524288KB , FILEGROWTH = 262144KB ) TO FILEGROUP [QuarterlyFG04]
GO
ALTER DATABASE [PartitionThis] ADD FILE ( NAME = N'QuarterlyF05', FILENAME = N'E:\SQL_DB_files\QuarterlyF05.ndf' , SIZE = 524288KB , FILEGROWTH = 262144KB ) TO FILEGROUP [QuarterlyFG05]
GO
ALTER DATABASE [PartitionThis] ADD FILE ( NAME = N'QuarterlyF06', FILENAME = N'E:\SQL_DB_files\QuarterlyF06.ndf' , SIZE = 524288KB , FILEGROWTH = 262144KB ) TO FILEGROUP [QuarterlyFG06]
GO
ALTER DATABASE [PartitionThis] ADD FILE ( NAME = N'QuarterlyF07', FILENAME = N'E:\SQL_DB_files\QuarterlyF07.ndf' , SIZE = 524288KB , FILEGROWTH = 262144KB ) TO FILEGROUP [QuarterlyFG07]
GO
ALTER DATABASE [PartitionThis] ADD FILE ( NAME = N'QuarterlyF08', FILENAME = N'E:\SQL_DB_files\QuarterlyF08.ndf' , SIZE = 524288KB , FILEGROWTH = 262144KB ) TO FILEGROUP [QuarterlyFG08]
GO
ALTER DATABASE [PartitionThis] ADD FILE ( NAME = N'QuarterlyF09', FILENAME = N'E:\SQL_DB_files\QuarterlyF09.ndf' , SIZE = 524288KB , FILEGROWTH = 262144KB ) TO FILEGROUP [QuarterlyFG09]
GO

ALTER DATABASE [PartitionThis] ADD FILE ( NAME = N'QuarterlyF10', FILENAME = N'E:\SQL_DB_files\QuarterlyF10.ndf' , SIZE = 524288KB , FILEGROWTH = 262144KB ) TO FILEGROUP [QuarterlyFG10]
GO
ALTER DATABASE [PartitionThis] ADD FILE ( NAME = N'QuarterlyF11', FILENAME = N'E:\SQL_DB_files\QuarterlyF11.ndf' , SIZE = 524288KB , FILEGROWTH = 262144KB ) TO FILEGROUP [QuarterlyFG11]
GO
ALTER DATABASE [PartitionThis] ADD FILE ( NAME = N'QuarterlyF12', FILENAME = N'E:\SQL_DB_files\QuarterlyF12.ndf' , SIZE = 524288KB , FILEGROWTH = 262144KB ) TO FILEGROUP [QuarterlyFG12]
GO
ALTER DATABASE [PartitionThis] ADD FILE ( NAME = N'QuarterlyF13', FILENAME = N'E:\SQL_DB_files\QuarterlyF13.ndf' , SIZE = 524288KB , FILEGROWTH = 262144KB ) TO FILEGROUP [QuarterlyFG13]
GO
