SELECT TOP (1000) [RowNumber]
      ,[EventClass]
      ,[EndTime]
      ,[CPU]
      ,[Duration]
      ,[Reads]
      ,[Writes]
      ,[RowCounts]
      ,[HostName]
      ,[LoginName]
      ,[DatabaseName]
      ,[ApplicationName]
      ,[TextData]
      ,[IsSystem]
      ,[SPID]
      ,[BinaryData]
FROM [DBA].[dbo].[CPIDB01Apr_Trc_03]

SELECT COUNT(*)
FROM [DBA].[dbo].[CPIDB01Apr_Trc_03]