USE [master]
RESTORE DATABASE [EasitraxEmailService] 
FROM  DISK = N'\\CMKTDB13BPR\SQLBackup\CPI\EasitraxEmailService.bak' 
   WITH  FILE = 1
,  REPLACE
,  STATS = 5
GO

USE [master]
RESTORE DATABASE [XXX] 
FROM  DISK = N'\\CMKTDB13BPR\SQLBackup\CPI\XXX.bak' 
   WITH  FILE = 1
,  REPLACE
,  STATS = 5
GO

USE [master]
RESTORE DATABASE [XXX] 
FROM  DISK = N'\\CMKTDB13BPR\SQLBackup\CPI\XXX.bak' 
   WITH  FILE = 1
,  REPLACE
,  STATS = 5
GO

USE [master]
RESTORE DATABASE [XXX] 
FROM  DISK = N'\\CMKTDB13BPR\SQLBackup\CPI\XXX.bak' 
   WITH  FILE = 1
,  REPLACE
,  STATS = 5
GO

USE [master]
RESTORE DATABASE [XXX] 
FROM  DISK = N'\\CMKTDB13BPR\SQLBackup\CPI\XXX.bak' 
   WITH  FILE = 1
,  REPLACE
,  STATS = 5
GO

USE [master]
RESTORE DATABASE [XXX] 
FROM  DISK = N'\\CMKTDB13BPR\SQLBackup\CPI\XXX.bak' 
   WITH  FILE = 1
,  REPLACE
,  STATS = 5
GO

USE [master]
RESTORE DATABASE [XXX] 
FROM  DISK = N'\\CMKTDB13BPR\SQLBackup\CPI\XXX.bak' 
   WITH  FILE = 1
,  REPLACE
,  STATS = 5
GO

USE [master]
RESTORE DATABASE [XXX] 
FROM  DISK = N'\\CMKTDB13BPR\SQLBackup\CPI\XXX.bak' 
   WITH  FILE = 1
,  REPLACE
,  STATS = 5
GO

USE [master]
RESTORE DATABASE [XXX] 
FROM  DISK = N'\\CMKTDB13BPR\SQLBackup\CPI\XXX.bak' 
   WITH  FILE = 1
,  REPLACE
,  STATS = 5
GO

USE [master]
RESTORE DATABASE [XXX] 
FROM  DISK = N'\\CMKTDB13BPR\SQLBackup\CPI\XXX.bak' 
   WITH  FILE = 1
,  REPLACE
,  STATS = 5
GO