USE master
GO

--SLOT_PARTICIPATION

ALTER DATABASE[SLOT_PARTICIPATION]
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO

BACKUP DATABASE [SLOT_PARTICIPATION] 
TO  DISK = N'\\CMKTDB13BPR\SQLBackup\CASIIVC07PR_Migration_To_CASI23_AAG\SLOT_PARTICIPATION_FULL.bak' 
WITH
  NOFORMAT
, INIT
, STATS = 5
GO

ALTER DATABASE[SLOT_PARTICIPATION]
SET MULTI_USER;
GO

ALTER DATABASE [SLOT_PARTICIPATION]
SET READ_ONLY
WITH ROLLBACK IMMEDIATE;
GO