USE master
GO

/****** SLOT_PARTICIPATION ******/

RESTORE DATABASE [SLOT_PARTICIPATION] 
FROM  DISK = N'\\CMKTDB13BPR\SQLBackup\CASIIVC07PR_Migration_To_CASI23_AAG\SLOT_PARTICIPATION_FULL.bak' 
WITH
  MOVE N'SLOT_PARTICIPATION' TO N'K:\UserDBdata\SLOT_PARTICIPATION_data.mdf'
, MOVE N'SLOT_PARTICIPATION_log' TO N'L:\UserDBlog\SLOT_PARTICIPATION_log.ldf'
, REPLACE
, RECOVERY  
, STATS = 5
GO

ALTER DATABASE[SLOT_PARTICIPATION]
SET MULTI_USER;
GO