/****** CASH_VARIANCE ******/

USE master;
GO

RESTORE DATABASE [CASH_VARIANCE] 
--FROM  DISK = N'\\CMKTDB13BPR\SQLBackup\CASIIVC07PR_Migration_To_CASI23_AAG\CASIVC07PR_CASH_VARIANCE_FULL_20180115_073000.bak' 
FROM  DISK = N'\\DBAMBK01PR\SQLBackup02\CASIVC07PR\CASH_VARIANCE\FULL\CASIVC07PR_CASH_VARIANCE_FULL_20180115_073000.bak'
WITH
  MOVE N'CASH_VARIANCE_data' TO N'K:\UserDBdata\CASH_VARIANCE.mdf'
, MOVE N'CASH_VARIANCE_log' TO N'L:\UserDBlog\CASH_VARIANCE_log.ldf'
, REPLACE
, NORECOVERY  
, STATS = 5
GO


/****** FLOORVIZ ******/

RESTORE DATABASE [FLOORVIZ] 
--FROM  DISK = N'\\CMKTDB13BPR\SQLBackup\CASIIVC07PR_Migration_To_CASI23_AAG\FLOORVIZ_full.bak' 
FROM  DISK = N'\\DBAMBK01PR\SQLBackup02\CASIVC07PR\FLOORVIZ\FULL\CASIVC07PR_FLOORVIZ_FULL_20180115_073245.bak'
WITH
  MOVE N'FLOORVIZ' TO N'K:\UserDBdata\FLOORVIZ_RESTORE.mdf'
, MOVE N'FLOORVIZ_log' TO N'L:\UserDBlog\FLOORVIZ_RESTORE_1.ldf'
, REPLACE
, NORECOVERY  
, STATS = 5
GO


/****** GUEST_MOBILE ******/

RESTORE DATABASE [GUEST_MOBILE] 
--FROM  DISK = N'\\CMKTDB13BPR\SQLBackup\CASIIVC07PR_Migration_To_CASI23_AAG\GUEST_MOBILE_full.bak' 
FROM  DISK = N'\\DBAMBK01PR\SQLBackup02\CASIVC07PR\GUEST_MOBILE\FULL\CASIVC07PR_GUEST_MOBILE_FULL_20180115_073252.bak'
WITH
  MOVE N'GUEST_MOBILE' TO N'K:\UserDBdata\GUEST_MOBILE_RESTORE.mdf'
, MOVE N'GUEST_MOBILE_log' TO N'L:\UserDBlog\GUEST_MOBILE_RESTORE_1.ldf'
, REPLACE
, NORECOVERY  
, STATS = 5
GO


/****** ICBWebReports ******/

RESTORE DATABASE [ICBWebReports] 
--FROM  DISK = N'\\CMKTDB13BPR\SQLBackup\CASIIVC07PR_Migration_To_CASI23_AAG\ICBWebReports_full.bak' 
FROM  DISK = N'\\DBAMBK01PR\SQLBackup02\CASIVC07PR\ICBWebReports\FULL\CASIVC07PR_ICBWebReports_FULL_20180115_073254.bak'
WITH
  MOVE N'ICBReports_Data' TO N'K:\UserDBdata\ICBWebReports_RESTORE.mdf'
, MOVE N'ICBReports_log' TO N'L:\UserDBlog\ICBWebReports_RESTORE_1.ldf'
, REPLACE
, NORECOVERY  
, STATS = 5
GO



/****** SLOT_SERVICE ******/

RESTORE DATABASE [SLOT_SERVICE] 
--FROM  DISK = N'\\CMKTDB13BPR\SQLBackup\CASIIVC07PR_Migration_To_CASI23_AAG\SLOT_SERVICE_full.bak' 
FROM  DISK = N'\\DBAMBK01PR\SQLBackup02\CASIVC07PR\SLOT_SERVICE\FULL\CASIVC07PR_SLOT_SERVICE_FULL_20180115_092437.bak' 
WITH
  MOVE N'SLOT_SERVICE_data' TO N'K:\UserDBdata\SLOT_SERVICE_RESTORE.mdf'
, MOVE N'SLOT_SERVICE_log' TO N'L:\UserDBlog\SLOT_SERVICE_RESTORE_1.ldf'
, REPLACE
, NORECOVERY  
, STATS = 5
GO



/****** SLOT_PARTICIPATION ******/

RESTORE DATABASE [SLOT_PARTICIPATION] 
FROM  DISK = N'\\DBAMBK01PR\SQLBackup02\CASIVC07PR\SLOT_PARTICIPATION\FULL\CASIVC07PR_SLOT_PARTICIPATION_FULL_20180115_073445.bak' 
WITH
  MOVE N'SLOT_PARTICIPATION' TO N'K:\UserDBdata\SLOT_PARTICIPATION_RESTORE.mdf'
, MOVE N'SLOT_PARTICIPATION_log' TO N'L:\UserDBlog\SLOT_PARTICIPATION_RESTORE_1.ldf'
, REPLACE
, NORECOVERY  
, STATS = 5
GO