/****** CASH_VARIANCE ******/

USE master;
GO

RESTORE DATABASE [CASH_VARIANCE] 
FROM  DISK = N'\\CMKTDB13BPR\SQLBackup\CASIIVC07PR_Migration_To_CASI23_AAG\CASH_VARIANCE_full.bak' 
WITH
  MOVE N'CASH_VARIANCE_data' TO N'K:\UserDBdata\CASH_VARIANCE.mdf'
, MOVE N'CASH_VARIANCE_log' TO N'L:\UserDBlog\CASH_VARIANCE_log.ldf'
, REPLACE
, RECOVERY  
, STATS = 5
GO

ALTER DATABASE [CASH_VARIANCE] 
SET MULTI_USER;
GO



/****** COMMON_SECURITY ******/

USE master;
GO

RESTORE DATABASE [COMMON_SECURITY] 
FROM  DISK = N'\\CMKTDB13BPR\SQLBackup\CASIIVC07PR_Migration_To_CASI23_AAG\COMMON_SECURITY_full.bak' 
WITH
  MOVE N'COMMON_SECURITY_data' TO N'K:\UserDBdata\COMMON_SECURITY_data.mdf'
, MOVE N'COMMON_SECURITY_log' TO N'L:\UserDBlog\COMMON_SECURITY_log.ldf'
, REPLACE
, RECOVERY  
, STATS = 5
GO

ALTER DATABASE [COMMON_SECURITY] 
SET MULTI_USER;
GO


------/****** FLOORVIZ ******/

------RESTORE DATABASE [FLOORVIZ] 
--------FROM  DISK = N'\\CMKTDB13BPR\SQLBackup\CASIIVC07PR_Migration_To_CASI23_AAG\FLOORVIZ_full.bak' 
------FROM  DISK = N'\\DBAMBK01PR\SQLBackup02\CASIVC07PR\FLOORVIZ\FULL\CASIVC07PR_FLOORVIZ_FULL_20180115_073245.bak'
------WITH
------  MOVE N'FLOORVIZ' TO N'K:\UserDBdata\FLOORVIZ_RESTORE.mdf'
------, MOVE N'FLOORVIZ_log' TO N'L:\UserDBlog\FLOORVIZ_RESTORE_1.ldf'
------, REPLACE
------, NORECOVERY  
------, STATS = 5
------GO


------/****** GUEST_MOBILE ******/

------RESTORE DATABASE [GUEST_MOBILE] 
--------FROM  DISK = N'\\CMKTDB13BPR\SQLBackup\CASIIVC07PR_Migration_To_CASI23_AAG\GUEST_MOBILE_full.bak' 
------FROM  DISK = N'\\DBAMBK01PR\SQLBackup02\CASIVC07PR\GUEST_MOBILE\FULL\CASIVC07PR_GUEST_MOBILE_FULL_20180115_073252.bak'
------WITH
------  MOVE N'GUEST_MOBILE' TO N'K:\UserDBdata\GUEST_MOBILE_RESTORE.mdf'
------, MOVE N'GUEST_MOBILE_log' TO N'L:\UserDBlog\GUEST_MOBILE_RESTORE_1.ldf'
------, REPLACE
------, NORECOVERY  
------, STATS = 5
------GO


/****** ICBWebReports ******/

RESTORE DATABASE [ICBWebReports] 
FROM  DISK = N'\\CMKTDB13BPR\SQLBackup\CASIIVC07PR_Migration_To_CASI23_AAG\ICBWebReports_full.bak'
WITH
  MOVE N'ICBReports_Data' TO N'K:\UserDBdata\ICBWebReports_data.mdf'
, MOVE N'ICBReports_log' TO N'L:\UserDBlog\ICBWebReports_log.ldf'
, REPLACE
, RECOVERY  
, STATS = 5
GO

ALTER DATABASE[ICBWebReports]
SET MULTI_USER;
GO



/****** SLOT_SERVICE ******/

----RESTORE DATABASE [SLOT_SERVICE] 
------FROM  DISK = N'\\CMKTDB13BPR\SQLBackup\CASIIVC07PR_Migration_To_CASI23_AAG\SLOT_SERVICE_full.bak' 
----FROM  DISK = N'\\DBAMBK01PR\SQLBackup02\CASIVC07PR\SLOT_SERVICE\FULL\CASIVC07PR_SLOT_SERVICE_FULL_20180115_092437.bak' 
----WITH
----  MOVE N'SLOT_SERVICE_data' TO N'K:\UserDBdata\SLOT_SERVICE_RESTORE.mdf'
----, MOVE N'SLOT_SERVICE_log' TO N'L:\UserDBlog\SLOT_SERVICE_RESTORE_1.ldf'
----, REPLACE
----, NORECOVERY  
----, STATS = 5
----GO