EXECUTE DBA.[dbo].[DatabaseBackup] 
  @Databases = 'SLOT_PARTICIPATION'
, @Directory = N'\\DBAMBK01PR\SQLBackup02'
, @BackupType = 'DIFF'
, @CleanupTime = 180
, @BackupSoftware = NULL
, @Compress  = 'Y'
, @CopyOnly = 'N'
, @Verify = 'N'
, @CheckSum = 'Y'
, @BufferCount = 512
, @MaxTransferSize = 1048576
, @BlockSize = 8192
, @LogToTable = 'Y'
GO

EXECUTE DBA.[dbo].[DatabaseBackup] 
  @Databases = 'SLOT_PARTICIPATION'
, @Directory = N'\\DBAMBK01PR\SQLBackupLogs01'
, @BackupType = 'LOG'
, @CleanupTime = 180
, @BackupSoftware = NULL
, @Compress  = 'Y'
, @CopyOnly = 'N'
, @Verify = 'N'
, @CheckSum = 'Y'
, @BufferCount = 512
, @MaxTransferSize = 1048576
, @BlockSize = 8192
, @LogToTable = 'Y'
GO

USE [SLOT_PARTICIPATION]
GO

SELECT *
INTO SLOT_MASTER_LOAD_SAVE
FROM SLOT_MASTER_LOAD
GO

-- EMPTY THE TABLE
TRUNCATE TABLE [dbo].[SLOT_MASTER_LOAD]
GO


-- DROP INDEXES TO SPEED UP INSERT
ALTER TABLE [dbo].[SLOT_MASTER_LOAD] DROP CONSTRAINT [PKSML_SlotNumber]
GO

DROP INDEX [IDXSML_StandNum] ON [dbo].[SLOT_MASTER_LOAD]
GO

DROP INDEX [IDXSML_OrigStand] ON [dbo].[SLOT_MASTER_LOAD]
GO

DROP INDEX [IDXSML_FloorStatus] ON [dbo].[SLOT_MASTER_LOAD]
GO


-- REFILL TABLE FROM RESTORED DATABASE
INSERT INTO [dbo].[SLOT_MASTER_LOAD] WITH (TABLOCKX)
SELECT *
FROM [SLOT_PARTICIPATION_2018_01_15_730AM].[dbo].[SLOT_MASTER_LOAD]
ORDER BY SLOT_NUMBER ASC
GO


-- RECREATE INDEXES
ALTER TABLE [dbo].[SLOT_MASTER_LOAD] ADD  CONSTRAINT [PKSML_SlotNumber] PRIMARY KEY CLUSTERED 
(
	[SLOT_NUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IDXSML_StandNum] ON [dbo].[SLOT_MASTER_LOAD]
(
	[STAND_NUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IDXSML_OrigStand] ON [dbo].[SLOT_MASTER_LOAD]
(
	[ORIG_STAND] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IDXSML_FloorStatus] ON [dbo].[SLOT_MASTER_LOAD]
(
	[FLOOR_STATUS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO


