DECLARE @ARRIVAL_TS datetime
SET @ARRIVAL_TS = DATEADD(day,-90,getdate())

--	INSERT INTO JUNKET_ANALYSIS
	SELECT g.TIER_ID
		, tr.TIER_NM 
		,g.GROUP_TYPE_ID
		, e.GROUP_CD
		, g.GROUP_NM
		, e.EVENT_ID
		, e.CHARTER_GROUP_NM
		, e.ARRIVAL_TS
		, e.DEPARTURE_TS
		, e.HEAD_CNT
		, r.PLAYER_ID	
		, p.ACCT_NUM
		, p.LAST_NM
		, p.FIRST_NM
		, COUNT(DISTINCT r.PLAYER_ID) AS PLAYER_CNT
		, NULL
		, NULL
		, NULL
		, NULL
		, SUM(r.THEORETICAL_WIN_AMT) AS THEORETICAL_WIN_TOTAL
		, SUM(r.CASINO_WIN_AMT) AS CASINO_WIN_TOTAL
		-- Get subtotals for SLOT department
		, CASE r.DEPT_ID WHEN 11 THEN COUNT(DISTINCT r.PLAYER_ID) ELSE 0 END AS SLOT_PLAYERS
		, SUM(CASE r.DEPT_ID WHEN 11 THEN r.CASINO_WIN_AMT ELSE 0 END) AS SLOT_CASINO_WIN
		, SUM(CASE r.DEPT_ID WHEN 11 THEN r.THEORETICAL_WIN_AMT ELSE 0 END) AS SLOT_THEO_WIN
		-- Get subtotals for TABLE GAMES department
		, CASE r.DEPT_ID WHEN 13 THEN COUNT(DISTINCT r.PLAYER_ID) ELSE 0 END AS TABL_PLAYERS
		, SUM(CASE r.DEPT_ID WHEN 13 THEN r.CASINO_WIN_AMT ELSE 0 END) AS TABL_CASINO_WIN
		, SUM(CASE r.DEPT_ID WHEN 13 THEN r.THEORETICAL_WIN_AMT ELSE 0 END) AS TABL_THEO_WIN
		-- Get subtotals for BINGO department
		, CASE r.DEPT_ID WHEN 1 THEN COUNT(DISTINCT r.PLAYER_ID) ELSE 0 END AS BING_PLAYERS
		, SUM(CASE r.DEPT_ID WHEN 1 THEN r.CASINO_WIN_AMT ELSE 0 END) AS BING_CASINO_WIN
		, SUM(CASE r.DEPT_ID WHEN 1 THEN r.THEORETICAL_WIN_AMT ELSE 0 END) AS BING_THEO_WIN
		-- Get subtotals for POKER department
		, CASE r.DEPT_ID WHEN 10 THEN COUNT(DISTINCT r.PLAYER_ID) ELSE 0 END AS POKR_PLAYERS
		, SUM(CASE r.DEPT_ID WHEN 10 THEN r.CASINO_WIN_AMT ELSE 0 END) AS POKR_CASINO_WIN
		, SUM(CASE r.DEPT_ID WHEN 10 THEN r.THEORETICAL_WIN_AMT ELSE 0 END) AS POKR_THEO_WIN
	FROM vBUS.dbo.VRATINGS r WITH(NOLOCK)
	INNER JOIN vBUS.dbo.MANIFESTS m WITH(NOLOCK) ON m.PLAYER_ID = r.PLAYER_ID
	INNER JOIN vBUS.dbo.EVENTS e WITH(NOLOCK) ON m.EVENT_ID = e.EVENT_ID
	INNER JOIN vBUS.dbo.GROUPS g WITH(NOLOCK) ON g.GROUP_CD = e.GROUP_CD
	INNER JOIN vBUS.dbo.TIER_REF tr WITH(NOLOCK) ON tr.TIER_ID = g.TIER_ID	
	LEFT OUTER JOIN vBUS.dbo.v_PLAYERS p WITH(NOLOCK) ON p.PLAYER_ID = m.PLAYER_ID
	--LEFT OUTER JOIN dbo.CMP_PLAYERS p WITH(NOLOCK) ON p.PLAYER_ID = m.PLAYER_ID
	WHERE e.ARRIVAL_TS >=  @ARRIVAL_TS
		AND r.RATING_START_TS BETWEEN dbo.f_round_to_hour(e.ARRIVAL_TS) AND e.DEPARTURE_TS
	GROUP BY g.TIER_ID 
		, tr.TIER_NM
		, g.GROUP_TYPE_ID
		, e.GROUP_CD
		, g.GROUP_NM
		, e.EVENT_ID
		, e.CHARTER_GROUP_NM
		, e.ARRIVAL_TS
		, e.DEPARTURE_TS
		, e.HEAD_CNT
		, r.PLAYER_ID
		, p.ACCT_NUM
		, p.LAST_NM
		, p.FIRST_NM
		, r.DEPT_ID
	ORDER BY e.GROUP_CD, e.ARRIVAL_TS, e.EVENT_ID, r.PLAYER_ID