-- *******************************************************
-- This SQL doctor optimization script was created 
-- based on the recommendations you selected from 
-- the following analysis: 
-- 
-- SQLdoctor version: 3.5.0.62
-- Date: Sunday, July 10, 2016
-- Time: 12:21:14 PM
-- SQL Server Instance: CASIDB22APR
-- Analysis Type: General Health Check, Workload Analysis, Database Object Analysis
-- *******************************************************


--  Missing index on [SLOT_SERVICE].[dbo].[TEAM_MEMBER_NOTIFICATION_DEVICE_ASSOC]
USE [SLOT_SERVICE];
GO
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[TEAM_MEMBER_NOTIFICATION_DEVICE_ASSOC]') AND name = N'IX_TEAM_MEMBER_NOTIFICATION_DEVICE_ASSOC_LOCATION_CD_SIGN_OUT_TS_DEVICE_ID')
	CREATE INDEX [IX_TEAM_MEMBER_NOTIFICATION_DEVICE_ASSOC_LOCATION_CD_SIGN_OUT_TS_DEVICE_ID] 
	ON [dbo].[TEAM_MEMBER_NOTIFICATION_DEVICE_ASSOC] 
	( [LOCATION_CD], [SIGN_OUT_TS] )
	INCLUDE( [DEVICE_ID] )
USE [SLOT_SERVICE];
GO
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[TEAM_MEMBER_NOTIFICATION_DEVICE_ASSOC]') AND name = N'IX_TEAM_MEMBER_NOTIFICATION_DEVICE_ASSOC_SIGN_OUT_TS')
	CREATE INDEX [IX_TEAM_MEMBER_NOTIFICATION_DEVICE_ASSOC_SIGN_OUT_TS] 
	ON [dbo].[TEAM_MEMBER_NOTIFICATION_DEVICE_ASSOC] 
	( [SIGN_OUT_TS] )
	
USE [SLOT_SERVICE];
GO
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[TEAM_MEMBER_NOTIFICATION_DEVICE_ASSOC]') AND name = N'IX_TEAM_MEMBER_NOTIFICATION_DEVICE_ASSOC_TEAM_MEMBER_NUM_SIGN_OUT_TS')
	CREATE INDEX [IX_TEAM_MEMBER_NOTIFICATION_DEVICE_ASSOC_TEAM_MEMBER_NUM_SIGN_OUT_TS] 
	ON [dbo].[TEAM_MEMBER_NOTIFICATION_DEVICE_ASSOC] 
	( [TEAM_MEMBER_NUM], [SIGN_OUT_TS] )
	
USE [SLOT_SERVICE];
GO
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[TEAM_MEMBER_NOTIFICATION_DEVICE_ASSOC]') AND name = N'IX_TEAM_MEMBER_NOTIFICATION_DEVICE_ASSOC_TEAM_MEMBER_NUM_SIGN_OUT_TS_DEVICE_ID')
	CREATE INDEX [IX_TEAM_MEMBER_NOTIFICATION_DEVICE_ASSOC_TEAM_MEMBER_NUM_SIGN_OUT_TS_DEVICE_ID] 
	ON [dbo].[TEAM_MEMBER_NOTIFICATION_DEVICE_ASSOC] 
	( [TEAM_MEMBER_NUM], [SIGN_OUT_TS], [DEVICE_ID] )


-- *******************************************************
-- This SQL doctor optimization script was created 
-- based on the recommendations you selected from 
-- the following analysis: 
-- 
-- SQLdoctor version: 3.5.0.62
-- Date: Sunday, July 10, 2016
-- Time: 12:21:14 PM
-- SQL Server Instance: CASIDB22APR
-- Analysis Type: General Health Check, Workload Analysis, Database Object Analysis
-- *******************************************************


--  Undo script for: Missing index on [SLOT_SERVICE].[dbo].[TEAM_MEMBER_NOTIFICATION_DEVICE_ASSOC]
------USE [SLOT_SERVICE];
------GO
------IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[TEAM_MEMBER_NOTIFICATION_DEVICE_ASSOC]') AND name = N'IX_TEAM_MEMBER_NOTIFICATION_DEVICE_ASSOC_LOCATION_CD_SIGN_OUT_TS_DEVICE_ID')
------	DROP INDEX [IX_TEAM_MEMBER_NOTIFICATION_DEVICE_ASSOC_LOCATION_CD_SIGN_OUT_TS_DEVICE_ID] 
------	ON [dbo].[TEAM_MEMBER_NOTIFICATION_DEVICE_ASSOC]
------USE [SLOT_SERVICE];
------GO
------IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[TEAM_MEMBER_NOTIFICATION_DEVICE_ASSOC]') AND name = N'IX_TEAM_MEMBER_NOTIFICATION_DEVICE_ASSOC_SIGN_OUT_TS')
------	DROP INDEX [IX_TEAM_MEMBER_NOTIFICATION_DEVICE_ASSOC_SIGN_OUT_TS] 
------	ON [dbo].[TEAM_MEMBER_NOTIFICATION_DEVICE_ASSOC]
------USE [SLOT_SERVICE];
------GO
------IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[TEAM_MEMBER_NOTIFICATION_DEVICE_ASSOC]') AND name = N'IX_TEAM_MEMBER_NOTIFICATION_DEVICE_ASSOC_TEAM_MEMBER_NUM_SIGN_OUT_TS')
------	DROP INDEX [IX_TEAM_MEMBER_NOTIFICATION_DEVICE_ASSOC_TEAM_MEMBER_NUM_SIGN_OUT_TS] 
------	ON [dbo].[TEAM_MEMBER_NOTIFICATION_DEVICE_ASSOC]
------USE [SLOT_SERVICE];
------GO
------IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[TEAM_MEMBER_NOTIFICATION_DEVICE_ASSOC]') AND name = N'IX_TEAM_MEMBER_NOTIFICATION_DEVICE_ASSOC_TEAM_MEMBER_NUM_SIGN_OUT_TS_DEVICE_ID')
------	DROP INDEX [IX_TEAM_MEMBER_NOTIFICATION_DEVICE_ASSOC_TEAM_MEMBER_NUM_SIGN_OUT_TS_DEVICE_ID] 
------	ON [dbo].[TEAM_MEMBER_NOTIFICATION_DEVICE_ASSOC]




	



