-- *******************************************************
-- This SQL doctor optimization script was created 
-- based on the recommendations you selected from 
-- the following analysis: 
-- 
-- SQLdoctor version: 3.5.0.62
-- Date: Sunday, July 10, 2016
-- Time: 12:21:14 PM
-- SQL Server Instance: CASIDB22APR
-- Analysis Type: General Health Check, Workload Analysis, Database Object Analysis
-- *******************************************************


--  Missing index on [SLOT_SERVICE].[dbo].[Slot_Master_Load]
USE [SLOT_SERVICE];
GO
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[Slot_Master_Load]') AND name = N'IX_Slot_Master_Load_FLOOR_STATUS_SLOT_STATUS_STAND_NUMBER')
	CREATE INDEX [IX_Slot_Master_Load_FLOOR_STATUS_SLOT_STATUS_STAND_NUMBER] 
	ON [dbo].[Slot_Master_Load] 
	( [FLOOR_STATUS], [SLOT_STATUS], [STAND_NUMBER] )
	
USE [SLOT_SERVICE];
GO
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[Slot_Master_Load]') AND name = N'IX_Slot_Master_Load_FLOOR_STATUS_SLOT_STATUS_STAND_NUMBER')
	CREATE INDEX [IX_Slot_Master_Load_FLOOR_STATUS_SLOT_STATUS_STAND_NUMBER] 
	ON [dbo].[Slot_Master_Load] 
	( [FLOOR_STATUS], [SLOT_STATUS] )
	INCLUDE( [STAND_NUMBER] )
USE [SLOT_SERVICE];
GO
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[Slot_Master_Load]') AND name = N'IX_Slot_Master_Load_FLOOR_STATUS_SLOT_STATUS_STAND_NUMBER_TYPE_DESC')
	CREATE INDEX [IX_Slot_Master_Load_FLOOR_STATUS_SLOT_STATUS_STAND_NUMBER_TYPE_DESC] 
	ON [dbo].[Slot_Master_Load] 
	( [FLOOR_STATUS], [SLOT_STATUS], [STAND_NUMBER] )
	INCLUDE( [TYPE_DESC] )
USE [SLOT_SERVICE];
GO
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[Slot_Master_Load]') AND name = N'IX_Slot_Master_Load_FLOOR_STATUS_SLOT_STATUS_STAND_NUMBER_DENOMINATION_GAME_TYPE_MACHINE_MODEL_MANUFACTURER_TYPE_DESC')
	CREATE INDEX [IX_Slot_Master_Load_FLOOR_STATUS_SLOT_STATUS_STAND_NUMBER_DENOMINATION_GAME_TYPE_MACHINE_MODEL_MANUFACTURER_TYPE_DESC] 
	ON [dbo].[Slot_Master_Load] 
	( [FLOOR_STATUS], [SLOT_STATUS], [STAND_NUMBER] )
	INCLUDE( [DENOMINATION], [GAME_TYPE], [MACHINE_MODEL], [MANUFACTURER], [TYPE_DESC] )
USE [SLOT_SERVICE];
GO
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[Slot_Master_Load]') AND name = N'IX_Slot_Master_Load_FLOOR_STATUS_SLOT_STATUS_STAND_NUMBER_DENOMINATION_GAME_TYPE_MACHINE_MODEL_MANUFACTURER')
	CREATE INDEX [IX_Slot_Master_Load_FLOOR_STATUS_SLOT_STATUS_STAND_NUMBER_DENOMINATION_GAME_TYPE_MACHINE_MODEL_MANUFACTURER] 
	ON [dbo].[Slot_Master_Load] 
	( [FLOOR_STATUS], [SLOT_STATUS], [STAND_NUMBER] )
	INCLUDE( [DENOMINATION], [GAME_TYPE], [MACHINE_MODEL], [MANUFACTURER] )
USE [SLOT_SERVICE];
GO
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[Slot_Master_Load]') AND name = N'IX_Slot_Master_Load_FLOOR_STATUS_SLOT_STATUS_STAND_NUMBER_TYPE_DESC')
	CREATE INDEX [IX_Slot_Master_Load_FLOOR_STATUS_SLOT_STATUS_STAND_NUMBER_TYPE_DESC] 
	ON [dbo].[Slot_Master_Load] 
	( [FLOOR_STATUS], [SLOT_STATUS] )
	INCLUDE( [STAND_NUMBER], [TYPE_DESC] )
USE [SLOT_SERVICE];
GO
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[Slot_Master_Load]') AND name = N'IX_Slot_Master_Load_FLOOR_STATUS_SLOT_STATUS_DENOMINATION_GAME_TYPE_MACHINE_MODEL_MANUFACTURER_STAND_NUMBER')
	CREATE INDEX [IX_Slot_Master_Load_FLOOR_STATUS_SLOT_STATUS_DENOMINATION_GAME_TYPE_MACHINE_MODEL_MANUFACTURER_STAND_NUMBER] 
	ON [dbo].[Slot_Master_Load] 
	( [FLOOR_STATUS], [SLOT_STATUS] )
	INCLUDE( [DENOMINATION], [GAME_TYPE], [MACHINE_MODEL], [MANUFACTURER], [STAND_NUMBER] )
USE [SLOT_SERVICE];
GO
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[Slot_Master_Load]') AND name = N'IX_Slot_Master_Load_FLOOR_STATUS_SLOT_STATUS_DENOMINATION_GAME_TYPE_MACHINE_MODEL_MANUFACTURER_STAND_NUMBER_TYPE_DESC')
	CREATE INDEX [IX_Slot_Master_Load_FLOOR_STATUS_SLOT_STATUS_DENOMINATION_GAME_TYPE_MACHINE_MODEL_MANUFACTURER_STAND_NUMBER_TYPE_DESC] 
	ON [dbo].[Slot_Master_Load] 
	( [FLOOR_STATUS], [SLOT_STATUS] )
	INCLUDE( [DENOMINATION], [GAME_TYPE], [MACHINE_MODEL], [MANUFACTURER], [STAND_NUMBER], [TYPE_DESC] )
USE [SLOT_SERVICE];
GO
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[Slot_Master_Load]') AND name = N'IX_Slot_Master_Load_FLOOR_STATUS_SLOT_STATUS_STAND_NUMBER_DENOMINATION_GAME_TYPE_MACHINE_MODEL_MANUFACTURER_SERIAL_NO')
	CREATE INDEX [IX_Slot_Master_Load_FLOOR_STATUS_SLOT_STATUS_STAND_NUMBER_DENOMINATION_GAME_TYPE_MACHINE_MODEL_MANUFACTURER_SERIAL_NO] 
	ON [dbo].[Slot_Master_Load] 
	( [FLOOR_STATUS], [SLOT_STATUS], [STAND_NUMBER] )
	INCLUDE( [DENOMINATION], [GAME_TYPE], [MACHINE_MODEL], [MANUFACTURER], [SERIAL_NO] )
USE [SLOT_SERVICE];
GO
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[Slot_Master_Load]') AND name = N'IX_Slot_Master_Load_FLOOR_STATUS_SLOT_STATUS_DENOMINATION_GAME_TYPE_MACHINE_MODEL_MANUFACTURER_SERIAL_NO_STAND_NUMBER')
	CREATE INDEX [IX_Slot_Master_Load_FLOOR_STATUS_SLOT_STATUS_DENOMINATION_GAME_TYPE_MACHINE_MODEL_MANUFACTURER_SERIAL_NO_STAND_NUMBER] 
	ON [dbo].[Slot_Master_Load] 
	( [FLOOR_STATUS], [SLOT_STATUS] )
	INCLUDE( [DENOMINATION], [GAME_TYPE], [MACHINE_MODEL], [MANUFACTURER], [SERIAL_NO], [STAND_NUMBER] )



-- *******************************************************
-- This SQL doctor optimization script was created 
-- based on the recommendations you selected from 
-- the following analysis: 
-- 
-- SQLdoctor version: 3.5.0.62
-- Date: Sunday, July 10, 2016
-- Time: 12:21:14 PM
-- SQL Server Instance: CASIDB22APR
-- Analysis Type: General Health Check, Workload Analysis, Database Object Analysis
-- *******************************************************


--  Undo script for: Missing index on [SLOT_SERVICE].[dbo].[Slot_Master_Load]
------USE [SLOT_SERVICE];
------GO
------IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[Slot_Master_Load]') AND name = N'IX_Slot_Master_Load_FLOOR_STATUS_SLOT_STATUS_STAND_NUMBER')
------	DROP INDEX [IX_Slot_Master_Load_FLOOR_STATUS_SLOT_STATUS_STAND_NUMBER] 
------	ON [dbo].[Slot_Master_Load]
------USE [SLOT_SERVICE];
------GO
------IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[Slot_Master_Load]') AND name = N'IX_Slot_Master_Load_FLOOR_STATUS_SLOT_STATUS_STAND_NUMBER')
------	DROP INDEX [IX_Slot_Master_Load_FLOOR_STATUS_SLOT_STATUS_STAND_NUMBER] 
------	ON [dbo].[Slot_Master_Load]
------USE [SLOT_SERVICE];
------GO
------IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[Slot_Master_Load]') AND name = N'IX_Slot_Master_Load_FLOOR_STATUS_SLOT_STATUS_STAND_NUMBER_TYPE_DESC')
------	DROP INDEX [IX_Slot_Master_Load_FLOOR_STATUS_SLOT_STATUS_STAND_NUMBER_TYPE_DESC] 
------	ON [dbo].[Slot_Master_Load]
------USE [SLOT_SERVICE];
------GO
------IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[Slot_Master_Load]') AND name = N'IX_Slot_Master_Load_FLOOR_STATUS_SLOT_STATUS_STAND_NUMBER_DENOMINATION_GAME_TYPE_MACHINE_MODEL_MANUFACTURER_TYPE_DESC')
------	DROP INDEX [IX_Slot_Master_Load_FLOOR_STATUS_SLOT_STATUS_STAND_NUMBER_DENOMINATION_GAME_TYPE_MACHINE_MODEL_MANUFACTURER_TYPE_DESC] 
------	ON [dbo].[Slot_Master_Load]
------USE [SLOT_SERVICE];
------GO
------IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[Slot_Master_Load]') AND name = N'IX_Slot_Master_Load_FLOOR_STATUS_SLOT_STATUS_STAND_NUMBER_DENOMINATION_GAME_TYPE_MACHINE_MODEL_MANUFACTURER')
------	DROP INDEX [IX_Slot_Master_Load_FLOOR_STATUS_SLOT_STATUS_STAND_NUMBER_DENOMINATION_GAME_TYPE_MACHINE_MODEL_MANUFACTURER] 
------	ON [dbo].[Slot_Master_Load]
------USE [SLOT_SERVICE];
------GO
------IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[Slot_Master_Load]') AND name = N'IX_Slot_Master_Load_FLOOR_STATUS_SLOT_STATUS_STAND_NUMBER_TYPE_DESC')
------	DROP INDEX [IX_Slot_Master_Load_FLOOR_STATUS_SLOT_STATUS_STAND_NUMBER_TYPE_DESC] 
------	ON [dbo].[Slot_Master_Load]
------USE [SLOT_SERVICE];
------GO
------IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[Slot_Master_Load]') AND name = N'IX_Slot_Master_Load_FLOOR_STATUS_SLOT_STATUS_DENOMINATION_GAME_TYPE_MACHINE_MODEL_MANUFACTURER_STAND_NUMBER')
------	DROP INDEX [IX_Slot_Master_Load_FLOOR_STATUS_SLOT_STATUS_DENOMINATION_GAME_TYPE_MACHINE_MODEL_MANUFACTURER_STAND_NUMBER] 
------	ON [dbo].[Slot_Master_Load]
------USE [SLOT_SERVICE];
------GO
------IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[Slot_Master_Load]') AND name = N'IX_Slot_Master_Load_FLOOR_STATUS_SLOT_STATUS_DENOMINATION_GAME_TYPE_MACHINE_MODEL_MANUFACTURER_STAND_NUMBER_TYPE_DESC')
------	DROP INDEX [IX_Slot_Master_Load_FLOOR_STATUS_SLOT_STATUS_DENOMINATION_GAME_TYPE_MACHINE_MODEL_MANUFACTURER_STAND_NUMBER_TYPE_DESC] 
------	ON [dbo].[Slot_Master_Load]
------USE [SLOT_SERVICE];
------GO
------IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[Slot_Master_Load]') AND name = N'IX_Slot_Master_Load_FLOOR_STATUS_SLOT_STATUS_STAND_NUMBER_DENOMINATION_GAME_TYPE_MACHINE_MODEL_MANUFACTURER_SERIAL_NO')
------	DROP INDEX [IX_Slot_Master_Load_FLOOR_STATUS_SLOT_STATUS_STAND_NUMBER_DENOMINATION_GAME_TYPE_MACHINE_MODEL_MANUFACTURER_SERIAL_NO] 
------	ON [dbo].[Slot_Master_Load]
------USE [SLOT_SERVICE];
------GO
------IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[Slot_Master_Load]') AND name = N'IX_Slot_Master_Load_FLOOR_STATUS_SLOT_STATUS_DENOMINATION_GAME_TYPE_MACHINE_MODEL_MANUFACTURER_SERIAL_NO_STAND_NUMBER')
------	DROP INDEX [IX_Slot_Master_Load_FLOOR_STATUS_SLOT_STATUS_DENOMINATION_GAME_TYPE_MACHINE_MODEL_MANUFACTURER_SERIAL_NO_STAND_NUMBER] 
------	ON [dbo].[Slot_Master_Load]



