SELECT TOP (1000) 
            [Local_ETL_Inserted_TS]
			, [Local_ETL_Updated_TS]
, [id]
      ,[tenant_id]
      ,[property_id]
      ,[account_id]
      ,[amount]
      ,[category_id]
      ,[display_date]
      ,[folio_id]
      ,[accounting_item_id]
      ,[ledger_id]
      ,[quantity]
      ,[room_revenue]
      ,[subcategory_id]
      ,[user_id]
      ,[ledger_lines_ledger_transaction_id]
      ,[folio_lines_ledger_transaction_id]
      ,[tax_reference_id]
      ,[adjustment_reference_id]
      ,[call_type]
      ,[correction_reference_id]
      ,[description]
      ,[free_allowance_amount]
      ,[gateway_type]
      ,[gift_card]
      ,[invalid]
      ,[meal_period_id]
      ,[rate_change_comment]
      ,[reason]
      ,[recurring_charge_id]
      ,[reference]
      ,[refund_reference_id]
      ,[reservation_id]
      ,[reverse_tax_total_charge_amount]
      ,[reverse_tax]
      ,[room_charge_posting_type]
      ,[source_id]
      ,[transfer_reference_id]
      ,[pantry_item]
      ,[comp_id]
      ,[check_number]
      ,[exclude_tax]
      ,[reference_number]
      ,[comp_reference_id]
      ,[room_id]
      ,[routed]
      ,[source_folio_line_item_id]
      ,[payment_method_id]
      ,[posting_rule_id]
      ,[issuer]
      ,[last_four_digits]
      ,[payment_interface_id]
      ,[revised_adjustment_amount]
      ,[is_manage_dispute_adjustment]
      ,[corrected_or_adjusted_amount]
      ,[deposit_payment_at_booking]
      ,[auth_code]


  FROM [StayDWH].[dbo].[line_items_0201_PLUS]

order by [Local_ETL_Inserted_TS] desc
