SELECT TOP (1000) [SlotGatewayReceiveId]
      ,[InterfaceName]
      ,[RequestMessage]
      ,[ResponseMessage]
      ,[ReceivedDtm]
      ,[ProcessedDtm]
      ,[PostedBy]
      ,[IsProcessed]
      ,[ErrorMsg]
      ,[ErrorMsgDtl]
      ,[MsgChecksum2]
      ,[RelatedRecieveId]
      ,[AcctNo]
      ,[DataRowVersion]
      ,[AttemptsCount]
      ,[SDSMessageId]
  FROM CMPDBLIS01PR. [CMP13].[dbo].[tSlotGatewayReceive]

SELECT count(*)
FROM CMPDBLIS01PR.[CMP13].[dbo].[tSlotGatewayReceive]
