MERGE OperaData_Temp.dbo.NAME_RESERVATION AS TT -- Target Table
USING OperaData_Temp.dbo.NAME_RESERVATION_1 AS ST -- Source Table  
ON  TT.CONFIRMATION_NO = ST.CONFIRMATION_NO

-- WHEN MATCHED THEN IGNORE \ DO NOTHING

WHEN NOT MATCHED THEN INSERT 
  (
    ACTIVE_YN
  , ACTUAL_CHECK_IN_DATE
  , ACTUAL_CHECK_OUT_DATE
  , ARRIVAL
  , ARRIVAL_TIME
  , BLOCK_CODE
  , BLOCK_DESCRIPTION
  , CONFIRMATION_NO
  , DEPARTURE
  , DEPARTURE_TIME
  , EMAIL
  , EMAIL_YN
  , FB_REVENUE
  , GENDER
  , GUEST_COUNTRY
  , GUEST_COUNTRY_DESC
  , GUEST_FIRST_NAME
  , GUEST_NAME
  , INSERT_DATE
  , MAIL_YN
  , MARKET_CODE
  , MEMBERSHIP_EXPIRATION_DATE
  , MEMBERSHIP_LEVEL
  , MEMBERSHIP_NAME_ON_CARD
  , MEMBERSHIP_NUMBER
  , MEMBERSHIP_TYPE
  , NAME_MEMBERSHIP_ID
  , NAME_MEMBERSHIP_LEVEL
  , NAME_MEMBERSHIP_NUMBER
  , NAME_MEMBERSHIP_TYPE
  , NIGHTS
  , NO_OF_ROOMS
  , ORIGIN_OF_BOOKING
  , PROMOTIONS
  , RATE_CODE
  , RESERVATION_DATE
  , RESORT
  , RESV_STATUS
  , ROOM
  , ROOM_RESORT
  , ROOM_REVENUE
  , TOTAL_REVENUE
  , VIP_DESC
  , VIP_NAME
  , VIP_STATUS
  , TOTAL_NIGHTS
  , TOTAL_STAY
  , LAST_STAY
  , TOTAL_NIGHTS_LASTYR
  , TOTAL_STAY_LASTYR
  , FIRST_STAY_YN
  , ROOM_CATEGORY_LABEL
  , MY_ROOM_RATE
    ) 
  VALUES 
  (
    ST.ACTIVE_YN
  , ST.ACTUAL_CHECK_IN_DATE
  , ST.ACTUAL_CHECK_OUT_DATE
  , ST.ARRIVAL
  , ST.ARRIVAL_TIME
  , ST.BLOCK_CODE
  , ST.BLOCK_DESCRIPTION
  , ST.CONFIRMATION_NO
  , ST.DEPARTURE
  , ST.DEPARTURE_TIME
  , ST.EMAIL
  , ST.EMAIL_YN
  , ST.FB_REVENUE
  , ST.GENDER
  , ST.GUEST_COUNTRY
  , ST.GUEST_COUNTRY_DESC
  , ST.GUEST_FIRST_NAME
  , ST.GUEST_NAME
  , ST.INSERT_DATE
  , ST.MAIL_YN
  , ST.MARKET_CODE
  , ST.MEMBERSHIP_EXPIRATION_DATE
  , ST.MEMBERSHIP_LEVEL
  , ST.MEMBERSHIP_NAME_ON_CARD
  , ST.MEMBERSHIP_NUMBER
  , ST.MEMBERSHIP_TYPE
  , ST.NAME_MEMBERSHIP_ID
  , ST.NAME_MEMBERSHIP_LEVEL
  , ST.NAME_MEMBERSHIP_NUMBER
  , ST.NAME_MEMBERSHIP_TYPE
  , ST.NIGHTS
  , ST.NO_OF_ROOMS
  , ST.ORIGIN_OF_BOOKING
  , ST.PROMOTIONS
  , ST.RATE_CODE
  , ST.RESERVATION_DATE
  , ST.RESORT
  , ST.RESV_STATUS
  , ST.ROOM
  , ST.ROOM_RESORT
  , ST.ROOM_REVENUE
  , ST.TOTAL_REVENUE
  , ST.VIP_DESC
  , ST.VIP_NAME
  , ST.VIP_STATUS
  , ST.TOTAL_NIGHTS
  , ST.TOTAL_STAY
  , ST.LAST_STAY
  , ST.TOTAL_NIGHTS_LASTYR
  , ST.TOTAL_STAY_LASTYR
  , ST.FIRST_STAY_YN
  , ST.ROOM_CATEGORY_LABEL
  , ST.MY_ROOM_RATE
  );