SELECT 
  RESORT
, RESV_STATUS
, ARRIVAL
, ARRIVAL_TIME
, NIGHTS
, DEPARTURE
, DEPARTURE_TIME
, GUEST_NAME
, GUEST_FIRST_NAME
, ACTUAL_CHECK_IN_DATE
, ACTUAL_CHECK_OUT_DATE
, MEMBERSHIP_NUMBER
, MEMBERSHIP_TYPE
, MEMBERSHIP_LEVEL
, MARKET_CODE
, RATE_CODE
, RESERVATION_DATE
, ROOM_REVENUE
, TOTAL_REVENUE
, EMAIL
, ACTIVE_YN
, VIP_STATUS
, VIP_NAME
, VIP_DESC
, NAME_MEMBERSHIP_NUMBER
, NAME_MEMBERSHIP_TYPE
, NAME_MEMBERSHIP_LEVEL
, GENDER
, NAME_MEMBERSHIP_ID
, MEMBERSHIP_EXPIRATION_DATE
, MEMBERSHIP_NAME_ON_CARD
, EMAIL_YN
, MAIL_YN
, ROOM_RESORT
, CONFIRMATION_NO
, GUEST_COUNTRY
, GUEST_COUNTRY_DESC
, ROOM
, NO_OF_ROOMS

FROM Opera_Reporting.dbo.NAME_RESERVATION

WHERE ACTUAL_CHECK_OUT_DATE BETWEEN '01/01/2016' AND '03/03/2017'

ORDER BY 
  ACTUAL_CHECK_OUT_DATE
