 -----------------------------------------------------------------------------------------------------------------------------
 --  Created by: SPaylor
 --  Date: 5/18/2023
 --
 -- After initial load of the FINANCIAL_TRANSACTIONS table from the FINANCIAL_TRANSACTIONS_VIEW in the Opera Oracle database,
 -- this code run periodically to add any new transactions since the previous update.
 ------------------------------------------------------------------------------------------------------------------------------
 DROP TABLE IF EXISTS #NewTRX
 GO

-----------------------------------------------------------------------------------------------
-- Get and save the highest TRX_NO in the target table to a variable to be used later to select only new rows
-----------------------------------------------------------------------------------------------

DECLARE @MaxUpdateDate as datetime ;

SET @MaxUpdateDate = (SELECT MAX(UPDATE_DATE) FROM Opera_Extract.dbo.FINANCIAL_TRANSACTIONS)

PRINT @MaxUpdateDate

---------------------------------------------------------------------------------------
-- Dump the new rows (UPDATE_DATE > MAX(UPDATE_DATE) into a temp table
---------------------------------------------------------------------------------------

SELECT CAST(TRX_NO AS INT) AS TRX_NO
      ,TRX_DATE
      ,TRX_CODE
	  ,CAST(CAST(RESV_NAME_ID AS INT) AS VARCHAR(10)) AS RESV_NAME_ID
	  ,RESORT
      ,DEP_LED_DEBIT
      ,DEP_LED_CREDIT
      ,GUEST_ACCOUNT_DEBIT
      ,GUEST_ACCOUNT_CREDIT
      ,PACKAGE_DEBIT
      ,PACKAGE_CREDIT
      ,AR_LED_DEBIT
      ,INTERNAL_DB_PAYMENTS
      ,AR_LED_CREDIT
      ,REVENUE_AMT
      ,TRX_AMOUNT
      ,NET_AMOUNT
      ,GROSS_AMOUNT
      ,NON_REVENUE_AMOUNT
      ,INH_CREDIT
      ,INH_DEBIT
      ,CASHIER_DEBIT
      ,CASHIER_CREDIT
      ,POSTED_AMOUNT
      ,PRICE_PER_UNIT
      ,QUANTITY
      ,EXCHANGE_RATE
      ,EURO_EXCHANGE_RATE
      ,MARKET_CODE
      ,SOURCE_CODE
      ,ROOM_CLASS
      ,INVOICE_TYPE
      ,TAX_INCLUSIVE_YN
      ,RECPT_NO
      ,RECPT_TYPE
      ,CHEQUE_NUMBER
      ,AR_TRANSFER_DATE
      ,FT_SUBTYPE
      ,TC_GROUP
      ,TC_SUBGROUP
      ,TRX_NO_ADDED_BY
      ,TRX_NO_AGAINST_PACKAGE
      ,AR_NUMBER
      ,BUSINESS_DATE
      ,ROOM
	  ,CASHIER_ID
      ,FOLIO_VIEW
      ,REMARK
      ,REFERENCE
      ,CREDIT_CARD_ID
      ,NAME_ID
      ,RATE_CODE
      ,TRAN_ACTION_ID
      ,ROUTING_INSTRN_ID
      ,FROM_RESV_ID
      ,PRODUCT
      ,AR_STATE
      ,FOLIO_NO
      ,INVOICE_NO
      ,TRNS_ACTIVITY_DATE
      ,TRNS_FROM_ACCT
      ,TRNS_TO_ACCT
      ,BILL_NO
      ,REVISION_NO
      ,TARGET_RESORT
      ,FOLIO_TYPE
      ,COMPRESSED_YN
      ,ARRANGEMENT_ID
      ,ARRANGEMENT_CODE
      ,ARRANGEMENT_TYPE
      ,TRANSACTION_DESCRIPTION
      ,IND_ADJUSTMENT_YN
      ,REASON_CODE
      ,UPDATE_USER
      ,UPDATE_DATE
      ,INSERT_USER
      ,INSERT_DATE
      ,DEFERRED_YN
      ,TAX_GENERATED_YN
      ,TA_COMMISSIONABLE_YN
      ,FIXED_CHARGES_YN
      ,TAX_ELEMENTS
      ,INVOICE_CLOSE_DATE
      ,PASSERBY_NAME
      ,ROOM_TYPE
      ,CASHIER_NAME
      ,CC_CODE
      ,TC_TRANSACTION_TYPE
      ,TRX_CODE_TYPE
      ,TRX_TYPE
      ,TRX_TYPE_DESCRIPTION
      ,TRX_TYPE_SORT
      ,TB_AMOUNT_NET
      ,TB_AMOUNT_GROSS
      ,IS_DEBIT_01
      ,IS_CREDIT_01
      ,IS_INTERNAL_YN
      ,AUTHORIZER_ID
      ,APPROVAL_CODE
      ,APPROVAL_DATE
      ,APPROVAL_STATUS
      ,APPROVAL_STATUS_DESC
      ,APP_USER
      ,DISPLAY_YN
      ,LINK_TRX_NO
      ,SUMM_REF_CODE
      ,ACTUAL_POSTING_DATE_TIME
      ,FOREX_TYPE
      ,FOREX_COMM_PERC
      ,FOREX_COMM_AMOUNT
      ,ACTUAL_EXCHANGE_RATE
      ,ARTICLE_ID
      ,ARTICLE_CODE
      ,COMP_YN
      ,FIN_DML_SEQ_NO
      ,CC_TYPE
      ,COMP_LINK_TRX_NO
      ,COMP_LINK_TRX_CODE
      ,ACC_TYPE_FLAG
      ,FISCAL_BILL_NO
      ,PACKAGE_ALLOWANCE
      ,ORG_AR_LED_DEBIT
      ,SETTLEMENT_FLAG
      ,POSTING_DATE
      ,TRX_CODE_ADDED_BY
      ,ADV_GENERATE_ADJUSTMENT
      ,ADV_GENERATE_TRX_CODE
      ,MEMBERSHIP_ID
      ,PARALLEL_GUEST_CREDIT
      ,PARALLEL_GUEST_DEBIT
      ,PARALLEL_CURRENCY
      ,EXCHANGE_DIFFERENCE_YN
      ,INSTALLMENTS
      ,NUMBER_DIALED
      ,COVERS
      ,TZ_INSERT_DATE
      ,ASB_FLAG
      ,PROFIT_LOSS_FLAG
      ,IS_INTERNAL_PKG_TAX_YN
      ,IS_EXCL_PROFIT_LOSS_YN
      ,POSTIT_YN
      ,POSTIT_NO
      ,CHANGE_DUE
      ,AUTO_SETTLE_YN
      ,POSTING_TYPE
      ,IND_CASH
      ,DEP_TAX_TRANSFERED_YN
      ,ORIGINAL_RESV_NAME_ID
      ,DEFERRED_TAXES_YN
      ,POSTING_RHYTHM
      ,AUTO_CREDITBILL_YN
      ,BONUS_CHECK_ID
      ,FBA_CERTIFICATE_NUMBER
      ,OWNER_LED_DEBIT
      ,OWNER_LED_CREDIT
      ,ASB_TAX_FLAG
      ,ASB_ONLY_POST_TAXES_ONCE_YN
      ,CLOSURE_NO
      ,DEP_POSTING_FLAG
      ,PACKAGE_ARRANGEMENT_CODE
      ,CORRECTION_YN
      ,ROUTED_YN
      ,REVERSE_PAYMENT_TRX_NO
      ,ADVANCE_BILL_YN
      ,ADVANCE_BILL_REVERSED_YN
      ,GP_AWARD_CODE
      ,GP_AWARD_CANCEL_CODE
      ,ORG_POSTED_AMOUNT
      ,INC_TAX_DEDUCTED_YN
      ,DEP_NET_AMOUNT
      ,DEP_GROSS_AMOUNT
      ,INTERNAL_YN
      ,DEP_NET_TAX_AMT
      ,CC_REFUND_POSTING
      ,ELECTRONIC_VOUCHER_NO
      ,NAME_TAX_TYPE
      ,TRX_NO_ADJUST
      ,ROOM_NTS_EFFECTIVE
      ,THRESHOLD_DIVERSION_ID
      ,THRESHOLD_ENTITY_TYPE
      ,THRESHOLD_ENTITY_QTY
      ,THRESHOLD_TREATMENT_FLAG
      ,TRX_CODE_TYPE_ADDED_BY
      ,IS_ROOM_01
      ,IS_FOOD_01
      ,IS_OTHER_01
      ,IS_REVENUE_01
      ,IS_NON_REVENUE_01
      ,IS_PACKAGE_01
      ,IS_TAX_01
      ,IS_ROOM_GENERATE_01
      ,IS_FOOD_GENERATE_01
      ,IS_OTHER_GENERATE_01
      ,IS_NON_REVENUE_GENERATE_01
      ,ROOM_REVENUE
      ,FOOD_REVENUE
      ,OTHER_REVENUE
      ,TOTAL_REVENUE
      ,NON_REVENUE
      ,ROOM_REVENUE_TAX
      ,FOOD_REVENUE_TAX
      ,OTHER_REVENUE_TAX
      ,TOTAL_REVENUE_TAX
      ,NON_REVENUE_TAX
      ,PROPERTY_BILL_PREFIX
      ,DEPOSIT_TRANSACTION_ID
      ,ASSOCIATED_TRX_NO
      ,TRX_SERVICE_TYPE
      ,ACCOUNTING_CODE
      ,QUANTITY_CODE

INTO #NewTRX 

FROM OPERA_CCT..OPERA.FINANCIAL_TRANSACTIONS_VIEW

WHERE UPDATE_DATE >= @MaxUpdateDate 
  AND RESV_NAME_ID IS NOT NULL

--SELECT * FROM #NewTRX

-----------------------------------------------------------------------------------------
-- Delete any rows that might be duplicates on the insert (next step)
-----------------------------------------------------------------------------------------

DELETE FROM Opera_Extract.dbo.FINANCIAL_TRANSACTIONS
WHERE TRX_NO IN (SELECT TRX_NO FROM #NewTRX)

-----------------------------------------------------------------------------------------
-- Add new rows from the temp table to the final target table
-----------------------------------------------------------------------------------------

INSERT INTO Opera_Extract.dbo.FINANCIAL_TRANSACTIONS

SELECT TRX_NO
      ,TRX_DATE
      ,TRX_CODE
	  ,RESV_NAME_ID
	  ,RESORT
      ,DEP_LED_DEBIT
      ,DEP_LED_CREDIT
      ,GUEST_ACCOUNT_DEBIT
      ,GUEST_ACCOUNT_CREDIT
      ,PACKAGE_DEBIT
      ,PACKAGE_CREDIT
      ,AR_LED_DEBIT
      ,INTERNAL_DB_PAYMENTS
      ,AR_LED_CREDIT
      ,REVENUE_AMT
      ,TRX_AMOUNT
      ,NET_AMOUNT
      ,GROSS_AMOUNT
      ,NON_REVENUE_AMOUNT
      ,INH_CREDIT
      ,INH_DEBIT
      ,CASHIER_DEBIT
      ,CASHIER_CREDIT
      ,POSTED_AMOUNT
      ,PRICE_PER_UNIT
      ,QUANTITY
      ,EXCHANGE_RATE
      ,EURO_EXCHANGE_RATE
      ,MARKET_CODE
      ,SOURCE_CODE
      ,ROOM_CLASS
      ,INVOICE_TYPE
      ,TAX_INCLUSIVE_YN
      ,RECPT_NO
      ,RECPT_TYPE
      ,CHEQUE_NUMBER
      ,AR_TRANSFER_DATE
      ,FT_SUBTYPE
      ,TC_GROUP
      ,TC_SUBGROUP
      ,TRX_NO_ADDED_BY
      ,TRX_NO_AGAINST_PACKAGE
      ,AR_NUMBER
      ,BUSINESS_DATE
      ,ROOM
	  ,CASHIER_ID
      ,FOLIO_VIEW
      ,REMARK
      ,REFERENCE
      ,CREDIT_CARD_ID
      ,NAME_ID
      ,RATE_CODE
      ,TRAN_ACTION_ID
      ,ROUTING_INSTRN_ID
      ,FROM_RESV_ID
      ,PRODUCT
      ,AR_STATE
      ,FOLIO_NO
      ,INVOICE_NO
      ,TRNS_ACTIVITY_DATE
      ,TRNS_FROM_ACCT
      ,TRNS_TO_ACCT
      ,BILL_NO
      ,REVISION_NO
      ,TARGET_RESORT
      ,FOLIO_TYPE
      ,COMPRESSED_YN
      ,ARRANGEMENT_ID
      ,ARRANGEMENT_CODE
      ,ARRANGEMENT_TYPE
      ,TRANSACTION_DESCRIPTION
      ,IND_ADJUSTMENT_YN
      ,REASON_CODE
      ,UPDATE_USER
      ,UPDATE_DATE
      ,INSERT_USER
      ,INSERT_DATE
      ,DEFERRED_YN
      ,TAX_GENERATED_YN
      ,TA_COMMISSIONABLE_YN
      ,FIXED_CHARGES_YN
      ,TAX_ELEMENTS
      ,INVOICE_CLOSE_DATE
      ,PASSERBY_NAME
      ,ROOM_TYPE
      ,CASHIER_NAME
      ,CC_CODE
      ,TC_TRANSACTION_TYPE
      ,TRX_CODE_TYPE
      ,TRX_TYPE
      ,TRX_TYPE_DESCRIPTION
      ,TRX_TYPE_SORT
      ,TB_AMOUNT_NET
      ,TB_AMOUNT_GROSS
      ,IS_DEBIT_01
      ,IS_CREDIT_01
      ,IS_INTERNAL_YN
      ,AUTHORIZER_ID
      ,APPROVAL_CODE
      ,APPROVAL_DATE
      ,APPROVAL_STATUS
      ,APPROVAL_STATUS_DESC
      ,APP_USER
      ,DISPLAY_YN
      ,LINK_TRX_NO
      ,SUMM_REF_CODE
      ,ACTUAL_POSTING_DATE_TIME
      ,FOREX_TYPE
      ,FOREX_COMM_PERC
      ,FOREX_COMM_AMOUNT
      ,ACTUAL_EXCHANGE_RATE
      ,ARTICLE_ID
      ,ARTICLE_CODE
      ,COMP_YN
      ,FIN_DML_SEQ_NO
      ,CC_TYPE
      ,COMP_LINK_TRX_NO
      ,COMP_LINK_TRX_CODE
      ,ACC_TYPE_FLAG
      ,FISCAL_BILL_NO
      ,PACKAGE_ALLOWANCE
      ,ORG_AR_LED_DEBIT
      ,SETTLEMENT_FLAG
      ,POSTING_DATE
      ,TRX_CODE_ADDED_BY
      ,ADV_GENERATE_ADJUSTMENT
      ,ADV_GENERATE_TRX_CODE
      ,MEMBERSHIP_ID
      ,PARALLEL_GUEST_CREDIT
      ,PARALLEL_GUEST_DEBIT
      ,PARALLEL_CURRENCY
      ,EXCHANGE_DIFFERENCE_YN
      ,INSTALLMENTS
      ,NUMBER_DIALED
      ,COVERS
      ,TZ_INSERT_DATE
      ,ASB_FLAG
      ,PROFIT_LOSS_FLAG
      ,IS_INTERNAL_PKG_TAX_YN
      ,IS_EXCL_PROFIT_LOSS_YN
      ,POSTIT_YN
      ,POSTIT_NO
      ,CHANGE_DUE
      ,AUTO_SETTLE_YN
      ,POSTING_TYPE
      ,IND_CASH
      ,DEP_TAX_TRANSFERED_YN
      ,ORIGINAL_RESV_NAME_ID
      ,DEFERRED_TAXES_YN
      ,POSTING_RHYTHM
      ,AUTO_CREDITBILL_YN
      ,BONUS_CHECK_ID
      ,FBA_CERTIFICATE_NUMBER
      ,OWNER_LED_DEBIT
      ,OWNER_LED_CREDIT
      ,ASB_TAX_FLAG
      ,ASB_ONLY_POST_TAXES_ONCE_YN
      ,CLOSURE_NO
      ,DEP_POSTING_FLAG
      ,PACKAGE_ARRANGEMENT_CODE
      ,CORRECTION_YN
      ,ROUTED_YN
      ,REVERSE_PAYMENT_TRX_NO
      ,ADVANCE_BILL_YN
      ,ADVANCE_BILL_REVERSED_YN
      ,GP_AWARD_CODE
      ,GP_AWARD_CANCEL_CODE
      ,ORG_POSTED_AMOUNT
      ,INC_TAX_DEDUCTED_YN
      ,DEP_NET_AMOUNT
      ,DEP_GROSS_AMOUNT
      ,INTERNAL_YN
      ,DEP_NET_TAX_AMT
      ,CC_REFUND_POSTING
      ,ELECTRONIC_VOUCHER_NO
      ,NAME_TAX_TYPE
      ,TRX_NO_ADJUST
      ,ROOM_NTS_EFFECTIVE
      ,THRESHOLD_DIVERSION_ID
      ,THRESHOLD_ENTITY_TYPE
      ,THRESHOLD_ENTITY_QTY
      ,THRESHOLD_TREATMENT_FLAG
      ,TRX_CODE_TYPE_ADDED_BY
      ,IS_ROOM_01
      ,IS_FOOD_01
      ,IS_OTHER_01
      ,IS_REVENUE_01
      ,IS_NON_REVENUE_01
      ,IS_PACKAGE_01
      ,IS_TAX_01
      ,IS_ROOM_GENERATE_01
      ,IS_FOOD_GENERATE_01
      ,IS_OTHER_GENERATE_01
      ,IS_NON_REVENUE_GENERATE_01
      ,ROOM_REVENUE
      ,FOOD_REVENUE
      ,OTHER_REVENUE
      ,TOTAL_REVENUE
      ,NON_REVENUE
      ,ROOM_REVENUE_TAX
      ,FOOD_REVENUE_TAX
      ,OTHER_REVENUE_TAX
      ,TOTAL_REVENUE_TAX
      ,NON_REVENUE_TAX
      ,PROPERTY_BILL_PREFIX
      ,DEPOSIT_TRANSACTION_ID
      ,ASSOCIATED_TRX_NO
      ,TRX_SERVICE_TYPE
      ,ACCOUNTING_CODE
      ,QUANTITY_CODE

FROM #NewTRX

WHERE UPDATE_DATE > @MaxUpdateDate
