TRUNCATE TABLE Opera_Extract.dbo.TRX_CODES
GO

INSERT INTO Opera_Extract.dbo.TRX_CODES
SELECT 
       TAX_INCLUSIVE_YN
      ,RESORT
      ,FREQUENT_FLYER_YN
      ,TRX_CODE
      ,TC_GROUP
      ,TC_SUBGROUP
      ,[DESCRIPTION]
      ,TC_TRANSACTION_TYPE      
	  ,IS_MANUAL_POST_ALLOWED
      ,RESULT_INCLUDED_IN_SUM_ARRAY
      ,CC_TYPE
      ,COMMISSION
      ,CC_CODE
      ,IND_BILLING
      ,IND_AR
      ,IND_REVENUE_GP
      ,ADJ_TRX_CODE
      ,IND_CASH
      ,IND_DEPOSIT_YN
      ,DEFERRED_YN
      ,TRX_CODE_TYPE
      ,INSERT_USER 
      ,INSERT_DATE
      ,UPDATE_USER 
      ,UPDATE_DATE
      ,TRX_ACTION_ID
      ,INH_SALES_YN
      ,INH_PAY_YN
      ,INH_DEPOSIT_YN
      ,COMP_YN
      ,DEFAULT_PRICE
      ,INACTIVE_DATE
      ,PAYMENT_TAX_INVOICE_YN
      ,INTERNAL_YN
      ,FISCAL_PAYMENT_YN
      ,COMP_NIGHTS_YN
      ,CHECK_NO_MANDATORY_YN
      ,NON_TAXABLE_YN
      ,COMP_PAYMENT_YN
      ,TRX_CODE_DISPLAY
      ,INCLUDE_IN_DEPOSIT_RULE_YN
      ,GP_POINTS_REDEMPTION_YN

FROM OPERA_CCT..OPERA.TRX$_CODES