SELECT 
  CAST(TAX_INCLUSIVE_YN AS CHAR(1)) AS TAX_INCLUSIVE_YN
, CAST(RESORT AS VARCHAR(20)) AS RESORT 
, CAST(FREQUENT_FLYER_YN AS CHAR(1)) AS FREQUENT_FLYER_YN
, CAST(TRX_CODE AS VARCHAR(20)) AS TRX_CODE 
, CAST(TC_GROUP AS VARCHAR(20)) AS TC_GROUP
, CAST(TC_SUBGROUP AS VARCHAR(20)) AS TC_SUBGROUP
, CAST(TCL_CODE_DFLT_CL1 AS VARCHAR(20)) AS TCL_CODE_DFLT_CL1
, CAST(TCL_CODE_DFLT_CL2 AS VARCHAR(20)) AS TCL_CODE_DFLT_CL2 
, CAST(CLASS_1_MANDATORY_YN  AS CHAR(1)) AS CLASS_1_MANDATORY_YN
, CAST(CLASS_2_MANDATORY_YN AS CHAR(1)) AS CLASS_2_MANDATORY_YN
, CAST([DESCRIPTION] AS VARCHAR(2000)) AS [DESCRIPTION]
, CAST(TC_TRANSACTION_TYPE AS CHAR(5)) AS TC_TRANSACTION_TYPE
, CAST(IS_MANUAL_POST_ALLOWED AS VARCHAR(240)) AS IS_MANUAL_POST_ALLOWED 
, CAST(RESULT_INCLUDED_IN_SUM_ARRAY AS VARCHAR(5)) AS RESULT_INCLUDED_IN_SUM_ARRAY 
, CAST(CC_TYPE AS CHAR(2)) AS CC_TYPE
, CAST(COMMISSION AS NUMERIC(10,2)) AS COMMISSION
, CAST(CC_CODE AS VARCHAR(20)) AS CC_CODE
, CAST(IND_BILLING AS CHAR(1)) AS IND_BILLING
, CAST(IND_AR AS CHAR(1)) AS IND_AR
, CAST(CURRENCY AS VARCHAR(20)) AS CURRENCY
, CAST(IND_REVENUE_GP AS CHAR(1)) AS IND_REVENUE_GP
, CAST(ADJ_TRX_CODE AS VARCHAR(20)) AS ADJ_TRX_CODE
, CAST(EXPENSE_FOLIO AS FLOAT) AS EXPENSE_FOLIO
, CAST(GROUP_FOLIO AS FLOAT) AS GROUP_FOLIO
, CAST(REV_BUCKET_ID AS FLOAT) AS REV_BUCKET_ID
, CAST(REV_GP_ID AS FLOAT) AS REV_GP_ID
, CAST(IND_CASH AS CHAR(1)) AS IND_CASH
, CAST(IND_DEPOSIT_YN AS CHAR(1)) AS IND_DEPOSIT_YN
, CAST(DEFERRED_YN AS CHAR(1)) AS DEFERRED_YN
, CAST(AR_NAME_ID AS FLOAT) AS AR_NAME_ID 
, CAST(TRX_CODE_TYPE AS CHAR(2)) AS TRX_CODE_TYPE
, CAST(INSERT_USER AS FLOAT) AS INSERT_USER
, CAST(INSERT_DATE AS DATETIME) AS INSERT_DATE
, CAST(UPDATE_USER AS FLOAT) AS UPDATE_USER 
, CAST(UPDATE_DATE  AS DATETIME) AS UPDATE_DATE 
, CAST(TC_RESORT AS VARCHAR(20)) AS TC_RESORT
, CAST(TC_BOF_REF_CODE AS VARCHAR(240)) AS TC_BOF_REF_CODE
, CAST(TC_BOF_INTERFACE AS VARCHAR(240)) AS TC_BOF_INTERFACE
, CAST(TC_RESORT2 AS VARCHAR(20)) AS TC_RESORT2
, CAST(TC_BOF_REF_CODE2 AS VARCHAR(240)) AS TC_BOF_REF_CODE2 
, CAST(TC_BOF_INTERFACE2 AS VARCHAR(240)) AS TC_BOF_INTERFACE2
, CAST(CRS_TAX_DESC AS VARCHAR(15)) AS CRS_TAX_DESC
, CAST(TAX_CODE_NO AS FLOAT) AS AX_CODE_NO
, CAST(TRX_ACTION_ID AS FLOAT) AS TRX_ACTION_ID
, CAST(EXPORT_BUCKET AS FLOAT) AS EXPORT_BUCKET 
, CAST(INH_SALES_YN AS CHAR(1)) AS INH_SALES_YN
, CAST(INH_PAY_YN AS CHAR(1)) AS INH_PAY
, CAST(INH_DEPOSIT_YN AS CHAR(1)) AS INH_DEPOSIT_YN
, CAST(FISCAL_TRX_CODE_TYPE AS CHAR(1)) AS FISCAL_TRX_CODE_TYPE 
, CAST(COMP_YN AS CHAR(1)) AS COMP_YN
, CAST(DEFAULT_PRICE AS FLOAT) AS DEFAULT_PRICE
, CAST(INACTIVE_DATE  AS DATETIME) AS INACTIVE_DATE
, CAST(PAYMENT_TAX_INVOICE_YN AS CHAR(1)) AS PAYMENT_TAX_INVOICE_YN
, CAST(INTERNAL_YN AS CHAR(1)) AS INTERNAL_YN
, CAST(FISCAL_PAYMENT_YN AS CHAR(1)) AS FISCAL_PAYMENT_YN
, CAST(COMP_NIGHTS_YN AS CHAR(1)) AS COMP_NIGHTS_YN
, CAST(ROTATION_REV_YN AS CHAR(1)) AS ROTATION_REV_YN
, CAST(OWNER_REV_YN AS CHAR(1)) AS OWNER_REV_YN
, CAST(CHECK_NO_MANDATORY_YN AS CHAR(1)) AS CHECK_NO_MANDATORY_YN
, CAST(DED_OWNER_REV_YN AS CHAR(1)) AS DED_OWNER_REV_YN
, CAST(NON_TAXABLE_YN AS CHAR(1)) AS NON_TAXABLE_YN
, CAST(COMP_PAYMENT_YN AS CHAR(1)) AS COMP_PAYMENT_YN 
, CAST(MIN_AMT AS FLOAT) AS MIN_AMT
, CAST(MAX_AMT AS FLOAT) AS MAX_AMT
, CAST(TRX_SERVICE_TYPE AS VARCHAR(20)) AS TRX_SERVICE_TYPE
, CAST(DAILY_PLAN_FOLIO AS FLOAT) AS DAILY_PLAN_FOLIO
, CAST(TRX_CODE_DISPLAY AS VARCHAR(8)) AS TRX_CODE_DISPLAY 
, CAST(INCLUDE_IN_DEPOSIT_RULE_YN AS CHAR(1)) AS INCLUDE_IN_DEPOSIT_RULE_YN
, CAST(INCLUDE_IN_8300_YN AS CHAR(1)) AS INCLUDE_IN_8300_YN
, CAST(MANUAL_POST_COVERS_YN AS CHAR(1)) AS MANUAL_POST_COVERS_YN
, CAST(DEPOSIT_POSTING_ONLY_YN AS CHAR(1)) AS DEPOSIT_POSTING_ONLY_YN
, CAST(TRX_TAX_TYPE_CODE AS VARCHAR(20)) AS TRX_TAX_TYPE_CODE
, CAST(DEPOSIT_TYPE AS VARCHAR(20)) AS DEPOSIT_TYPE
, CAST(GP_POINTS_REDEMPTION_YN AS CHAR(1)) AS GP_POINTS_REDEMPTION_YN
, CAST(EXTERNAL_PAYMENT_CODE AS VARCHAR(20)) AS EXTERNAL_PAYMENT_CODE
, CAST(E_INVOICE_YN AS CHAR(1)) AS E_INVOICE_YN
, CAST(CORP_PROP_FLAG AS CHAR(1)) AS CORP_PROP_FLAG
, CAST(CORPORATE_DESCRIPTION AS VARCHAR(4000)) AS CORPORATE_DESCRIPTION
, CAST(PRINT_RECEIPT_YN AS CHAR(1)) AS PRINT_RECEIPT_YN
, CAST(SERVICE_RECOVERY_TRX_CODE AS VARCHAR(20)) AS SERVICE_RECOVERY_TRX_CODE
, CAST(ACCOUNTING_CODE AS VARCHAR(40)) AS ACCOUNTING_CODE
, CAST(QUANTITY_CODE AS VARCHAR(40)) AS QUANTITY_CODE

INTO Opera_Extract.dbo.TRX_CODES

FROM OPERA_CCT..OPERA.TRX$_CODES
GO


