SELECT COUNT(*)
FROM [Opera_Extract].[dbo].[FINANCIAL_TRANSACTIONS]

-- 121,871

SELECT
  TRX_NO
, COUNT(*)
FROM [Opera_Extract].[dbo].[FINANCIAL_TRANSACTIONS]

GROUP BY TRX_NO
HAVING COUNT(*) > 1


SELECT
  MIN(TRX_NO)
, MAX(TRX_NO)
, COUNT(*)
FROM [Opera_Extract].[dbo].[FINANCIAL_TRANSACTIONS]

SELECT (4332736 - 4206614)


SELECT TOP 1000
  TRX_NO
, COUNT(*)
FROM [Opera_Extract].[dbo].[FINANCIAL_TRANSACTIONS]
GROUP BY TRX_NO
