SELECT TOP 10 *
FROM [OPERA_CCT]..[OPERA].[FINANCIAL_TRANSACTIONS_VIEW]
GO

SELECT COUNT(*)
--SELECT TOP 10 *
FROM [OPERA_CCT]..[OPERA].[TRX$_CODES]
GO

INTO Opera_Extract.dbo.FINANCIAL_TRANSACTIONS_VIEW