SELECT --TOP (1000) 
      [RATE_DATE]
,[Reservation_id]
      --,[ACTUAL_CHECK_IN_DATE]
      --,[ACTUAL_CHECK_OUT_DATE]
      --,[ARRIVAL]
      --,[ARRIVAL_TIME]
      --,[BLOCK_CODE]
      --,[BLOCK_DESCRIPTION]
      --,[CONFIRMATION_NO]
      --,[DEPARTURE]
      --,[DEPARTURE_TIME]
      --,[EMAIL]
      --,[EMAIL_YN]
      --,[GENDER]
      --,[GUEST_COUNTRY]
      --,[GUEST_COUNTRY_DESC]
      --,[GUEST_FIRST_NAME]
      --,[GUEST_NAME]
      --,[INSERT_DATE]
      --,[MAIL_YN]
      --,[MARKET_CODE]
      --,[MEMBERSHIP_EXPIRATION_DATE]
      --,[MEMBERSHIP_LEVEL]
      --,[MEMBERSHIP_NAME_ON_CARD]
      --,[MEMBERSHIP_NUMBER]
      --,[MEMBERSHIP_TYPE]
      --,[NAME_MEMBERSHIP_ID]
      --,[NAME_MEMBERSHIP_LEVEL]
      --,[NAME_MEMBERSHIP_NUMBER]
      --,[NAME_MEMBERSHIP_TYPE]
      --,[NIGHTS]
      --,[NO_OF_ROOMS]
      --,[ORIGIN_OF_BOOKING]
      --,[OFFER_STATUS]
      --,[OFFER_TYPE]
      --,[PROMOTIONS]
      --,[RATE_CODE]
      --,[RESERVATION_DATE]
      --,[RESORT]
      --,[RESV_STATUS]
      --,[ROOM]
      --,[ROOM_RESORT]

      --,[Room_Revenue]
      --,[FB_Revenue]
      --,[Misc_Revenue]
      --,[Total_Revenue]
      ,[Room_Comp]
      ,[Food_Comp]
      ,[Misc_Comp]
      --,[Tier_Discount]
      --,[VIP_DESC]
      --,[VIP_NAME]
      --,[VIP_STATUS]
      --,[TOTAL_NIGHTS]
      --,[TOTAL_STAY]
      --,[LAST_STAY]
      --,[TOTAL_NIGHTS_LASTYR]
      --,[TOTAL_STAY_LASTYR]
      --,[FIRST_STAY_YN]
      --,[ROOM_CATEGORY_LABEL]
      --,[MY_ROOM_RATE]
      --,[RESV_NAME_ID]
      --,[ROOM_CLASS]
      --,[GUEST_PHONE]
      --,[PHONE_TYPE]
      --,[ADULTS]
      --,[CHILDREN]
      --,[ACCOMPANYING_YN]
      --,[ACCOMPANYING_NAMES]
  FROM [StayDWH].[dbo].[vw_Name_Reservation]

  WHERE 
  [RATE_DATE] >= '2025-08-25'
    AND 
 (ISNULL([Room_Comp],0) <> 0
       OR ISNULL([Food_Comp],0) <> 0
       OR ISNULL([Misc_Comp],0) <> 0)

  ORDER BY [RATE_DATE] DESC