BACKUP DATABASE SDSVJPRD 
TO  DISK = N'\\DBAMBK01PR\SQLBackup02\_PreUpgrade\SDSVJPRD_FULL.bak' 
WITH 
  NOFORMAT
, INIT
----, COPY_ONLY
,  STATS = 5
, COMPRESSION
, CHECKSUM


BACKUP DATABASE SDSVJPRD 
TO  DISK = N'\\DBAMBK01PR\SQLBackup02\_PreUpgrade\SDSVJPRD_DIFF.bak' 
WITH
  DIFFERENTIAL 
, NOFORMAT
, INIT
----, COPY_ONLY
,  STATS = 5
, COMPRESSION
, CHECKSUM