USE [master]
RESTORE DATABASE SDSVJPRD_NEW
FROM DISK = N'\\DBAMBK02PR\SQLBackup05\_PreUpgrade\SDSVJPRD_FULL.bak'  
WITH  
  FILE = 1
, MOVE N'SDS_DB' TO N'X:\UserDBdata\SDSVJPRD_NEW_data.mdf'
, MOVE N'SDS_DB_log'  TO 'X:\UserDBlog\SDSVJPRD_NEW_log.ldf'
, NOUNLOAD
--, REPLACE
, NORECOVERY
, STATS = 5
GO

--RESTORE DATABASE SDSVJPRD_NEW WITH RECOVERY

--USE [master]
--RESTORE DATABASE SDSVJPRD
--FROM DISK = N'\\DBAMBK01PR\SQLBackup02\_PreUpgrade\SDSVJPRD_DIFF.bak'   e
--WITH  
--  FILE = 1
--, MOVE N'SDS_DB' TO N'R:\UserDBdata\SDSVJPRD_data.mdf'
--, MOVE N'SDS_DB_log'  TO 'T:\UserDBlog\SDSVJPRD_log.ldf'
--, NOUNLOAD
--, RECOVERY
--, STATS = 5
--GO