USE [StayDWH]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER PROCEDURE usp_Load_flash_aggregate_History_Delta_From_Snapshot
AS 

INSERT INTO [StayDWH].[dbo].[flash_aggregate_History]
SELECT
  [date] as [date]
, isnull([tenant_id], 'NULL') as [tenant_id] 
, isnull([property_id], 'NULL') as [property_id] 
, isnull([building_name], 'NULL') as [building_name] 
, isnull([room_type_code], 'NULL') as [room_type_code] 
, isnull([rate_code], 'NULL') as [rate_code] 
, isnull([market_segment_code], 'NULL') as [market_segment_code] 
, [last_updated_at] as [last_updated_at] 

, MAX([total_rooms]) as [total_rooms] 
, MAX([off_the_market]) as [off_the_market] 
, MAX([total_available_rooms]) as [total_available_rooms] 
, MAX([out_of_order]) as [out_of_order] 
, MAX([rentable_rooms]) as [rentable_rooms] 
, MAX([hold]) as [hold] 
, MAX([departures_remaining_rooms]) as [departures_remaining_rooms] 
, MAX([departures_remaining_guests]) as [departures_remaining_guests] 
, MAX([departures_remaining_adults]) as [departures_remaining_adults] 
, MAX([departures_remaining_children]) as [departures_remaining_children] 
, MAX([departures_total_rooms]) as [departures_total_rooms] 
, MAX([departures_total_guests]) as [departures_total_guests] 
, MAX([departures_total_adults]) as [departures_total_adults] 
, MAX([departures_total_children]) as [departures_total_children] 
, MAX([arrivals_remaining_rooms]) as [arrivals_remaining_rooms] 
, MAX([arrivals_remaining_guests]) as [arrivals_remaining_guests] 
, MAX([arrivals_remaining_adults]) as [arrivals_remaining_adults] 
, MAX([arrivals_remaining_children]) as [arrivals_remaining_children] 
, MAX([arrivals_total_rooms]) as [arrivals_total_rooms] 
, MAX([arrivals_total_guests]) as [arrivals_total_guests] 
, MAX([arrivals_total_adults]) as [arrivals_total_adults] 
, MAX([arrivals_total_children]) as [arrivals_total_children] 
, MAX([stay_overs_rooms]) as [stay_overs_rooms] 
, MAX([stay_overs_guests]) as [stay_overs_guests] 
, MAX([stay_overs_adults]) as [stay_overs_adults] 
, MAX([stay_overs_children]) as [stay_overs_children] 
, MAX([no_show_rooms]) as [no_show_rooms] 
, MAX([no_show_guests]) as [no_show_guests] 
, MAX([no_show_adults]) as [no_show_adults] 
, MAX([no_show_children]) as [no_show_children] 
, MAX([totals_rooms]) as [totals_rooms] 
, MAX([totals_guests]) as [totals_guests] 
, MAX([totals_adults]) as [totals_adults] 
, MAX([totals_children]) as [totals_children] 
, MAX([same_day_rooms]) as [same_day_rooms] 
, MAX([same_day_guests]) as [same_day_guests] 
, MAX([same_day_adults]) as [same_day_adults] 
, MAX([same_day_children]) as [same_day_children] 
, MAX([walkin_rooms]) as [walkin_rooms] 
, MAX([walkin_guests]) as [walkin_guests] 
, MAX([walkin_adults]) as [walkin_adults] 
, MAX([walkin_children]) as [walkin_children] 
, MAX([reservations_no_rate_rooms]) as [reservations_no_rate_rooms] 
, MAX([no_rate_guests]) as [no_rate_guests] 
, MAX([no_rate_adults]) as [no_rate_adults] 
, MAX([no_rate_children]) as [no_rate_children] 
, MAX([rooms_vacant]) as [rooms_vacant] 
, MAX([rooms_sold]) as [rooms_sold] 
, MAX([rooms_sold_guests]) as [rooms_sold_guests] 
, MAX([rooms_comped]) as [rooms_comped] 
, MAX([rooms_comped_guests]) as [rooms_comped_guests] 
, MAX([rooms_occupied]) as [rooms_occupied] 
, MAX([rooms_occupied_guests]) as [rooms_occupied_guests] 
, MAX([transient_rooms_sold]) as [transient_rooms_sold] 
, MAX([transient_rooms_sold_guests]) as [transient_rooms_sold_guests] 
, MAX([group_rooms_sold]) as [group_rooms_sold] 
, MAX([group_rooms_sold_guests]) as [group_rooms_sold_guests] 
, MAX([room_type_sold]) as [room_type_sold] 
, MAX([groups_not_picked_up]) as [groups_not_picked_up] 
, MAX([availability_no_rate_rooms]) as [availability_no_rate_rooms] 
, MAX([room_revenue]) as [room_revenue] 
, MAX([room_revenue_transient]) as [room_revenue_transient] 
, MAX([room_revenue_group]) as [room_revenue_group] 
, MAX([historic]) as [historic] 
, MAX([room_revenue_total]) as [room_revenue_total] 
, MAX([room_revenue_tax]) as [room_revenue_tax] 
, MAX([room_revenue_transient_total]) as [room_revenue_transient_total] 
, MAX([room_revenue_transient_tax]) as [room_revenue_transient_tax] 
, MAX([room_revenue_group_total]) as [room_revenue_group_total] 
, MAX([room_revenue_group_tax]) as [room_revenue_group_tax] 
, MAX([room_type_name]) as [room_type_name] 
, MAX([rate_name]) as [rate_name] 
, MAX([market_segment_name]) as [market_segment_name] 
, MAX([originated_room_revenue]) as [originated_room_revenue] 
, MAX([originated_room_revenue_transient]) as [originated_room_revenue_transient] 
, MAX([originated_room_revenue_group]) as [originated_room_revenue_group] 
, MAX([originated_room_revenue_total]) as [originated_room_revenue_total] 
, MAX([originated_room_revenue_tax]) as [originated_room_revenue_tax] 
, MAX([originated_room_revenue_transient_total]) as [originated_room_revenue_transient_total] 
, MAX([originated_room_revenue_transient_tax]) as [originated_room_revenue_transient_tax] 
, MAX([originated_room_revenue_group_total]) as [originated_room_revenue_group_total] 
, MAX([originated_room_revenue_group_tax]) as [originated_room_revenue_group_tax] 
, MAX([redemption_stay]) as [redemption_stay] 
, COUNT(*) as [Local_ETL_Number_of_Original_Detail_Rows]
, MAX([Local_ETL_Inserted_TS]) as [Local_ETL_Inserted_TS]

FROM [StayDWH].[dbo].[flash_aggregate_Snapshot]

WHERE [last_updated_at] > (SELECT max([last_updated_at]) FROM [StayDWH].[dbo].[flash_aggregate_History])
 
GROUP BY
 [date]
,[tenant_id]
,[property_id]
,[building_name]
,[room_type_code]
,[rate_code]
,[market_segment_code]
,[last_updated_at]

ORDER BY
 [date]
,[tenant_id]
,[property_id]
,[building_name]
,[room_type_code]
,[rate_code]
,[market_segment_code]
,[last_updated_at] ;

GO

