SELECT 
  MAX(CONVERT(CHAR(16),RESV_DATE,120)) AS Farthest_Out_Reservation_Date
, COUNT(*)  AS Total_Number_of_Reservations

FROM [OperaDM].[dbo].[RESERVATIONS]

WHERE RESV_DATE = (SELECT MAX(CONVERT(CHAR(16),RESV_DATE,120)) FROM [OperaDM].[dbo].[RESERVATIONS])
GROUP BY
  CONVERT(CHAR(16),RESV_DATE,120)

ORDER BY
  CONVERT(CHAR(16),RESV_DATE,120) DESC;

DECLARE @ThisYear AS DATE

SET @ThisYear = CONVERT(CHAR(4),CURRENT_TIMESTAMP,120)

--PRINT @ThisYear

SELECT 
  CONVERT(CHAR(4),RESV_DATE,120)
--, COUNT(*)  AS Total_Number_of_Reservations_This_Year

FROM [OperaDM].[dbo].[RESERVATIONS]

WHERE RESV_DATE >= @ThisYear

--GROUP BY
--  CONVERT(CHAR(4),RESV_DATE,120)

--ORDER BY
--  CONVERT(CHAR(16),RESV_DATE,120) DESC;
