SELECT 
  RESV_NAME_ID
--, NAME_ID
, BUSINESS_DATE
--, BUSINESS_DATE_CREATED
--, RESV_STATUS
, COUNT(*) AS NUMBER_OF_ROWS
, SUM(ROOM_REVENUE)
, SUM(FOOD_REVENUE)
, SUM(TOTAL_REVENUE)

FROM OperaDm.dbo.OBI_RESERVATION_STAT_DAILY 

--WHERE RESV_NAME_ID='827957'

GROUP BY 
  RESV_NAME_ID
--, NAME_ID
, BUSINESS_DATE
--, BUSINESS_DATE_CREATED
--, RESV_STATUS

HAVING COUNT(*) > 1

ORDER BY 
  RESV_NAME_ID
--, NAME_ID
, BUSINESS_DATE
--, BUSINESS_DATE_CREATED
--, RESV_STATUS