SELECT 
  RESV_NAME_ID
, BUSINESS_DATE
, INSERT_DATE
, RESERVATION_DATE
, BUSINESS_DATE_CREATED
, NAME_ID

FROM OperaDm.dbo.OBI_RESERVATION_STAT_DAILY 

--WHERE RESV_NAME_ID='827957'

--WHERE INSERT_DATE <> BUSINESS_DATE_CREATED

--WHERE BUSINESS_DATE <> RESERVATION_DATE

ORDER BY 
  RESV_NAME_ID
, NAME_ID
, BUSINESS_DATE
, BUSINESS_DATE_CREATED