USE [Steve]
GO

CREATE TABLE [dbo].[OPERA_OBI_RESERVATION_STAT_DAILY](
  RESORT VARCHAR(20) NULL  
, BUSINESS_DATE DATE NULL  
, NAME_ID INT NULL  
, RATE_CODE VARCHAR(20) NULL  
, SOURCE_CODE VARCHAR(20) NULL  
, MARKET_CODE VARCHAR(20) NULL  
, ROOM_CATEGORY VARCHAR(20) NULL  
, ROOM_TYPE VARCHAR(20) NULL  
, COMPANY_ID INT NULL  
, AGENT_ID INT NULL  
, GROUP_ID INT NULL  
, SOURCE_PROF_ID INT NULL  
, RESV_STATUS VARCHAR(20) NULL  
, TRUNC_BEGIN_DATE DATE NULL  
, TRUNC_END_DATE DATE NULL  
, RESV_NAME_ID INT NULL  
, QUANTITY INT NULL  
, PHYSICAL_QUANTITY INT NULL  
, DUE_OUT_YN VARCHAR(1) NULL  
, ROOM_RESV_STATUS VARCHAR(20) NULL  
, ADULTS INT NULL  
, CHILDREN INT NULL  
, ROOM_ADULTS INT NULL  
, ROOM_CHILDREN INT NULL  
, PRIMARY_YN INT NULL  
, ALLOTMENT_HEADER_ID INT NULL  
, ROOM_REVENUE NUMERIC(38,12)  NULL  
, FOOD_REVENUE NUMERIC(38,12) NULL  
, PACKAGE_ROOM_REVENUE NUMERIC(38,12) NULL  
, PACKAGE_FOOD_REVENUE NUMERIC(38,12) NULL  
, TOTAL_ROOM_TAX NUMERIC(38,12) NULL  
, TOTAL_FOOD_TAX NUMERIC(38,12) NULL  
, TOTAL_PACKAGE_REVENUE NUMERIC(38,12) NULL  
, TOTAL_REVENUE NUMERIC(38,12) NULL  
, TOTAL_TAX NUMERIC(38,12) NULL  
, INSERT_DATE DATE NULL  
, ORIGINAL_END_DATE DATE NULL  
, WALKIN_YN VARCHAR(1) NULL  
, RESERVATION_DATE DATE NULL  
, ROOM_CLASS VARCHAR(20) NULL  
, VIP_STATUS VARCHAR(20) NULL  
, CANCELLATION_DATE DATE NULL  
, BIRTH_DATE DATE NULL  
, ROOM VARCHAR(20) NULL  
, MEMBERSHIP_ID INT NULL  
, CONTACT_ID INT NULL  
, RATE_CATEGORY VARCHAR(20) NULL  
, MARKET_MAIN_GROUP VARCHAR(20) NULL  
, SOURCE_MAIN_GROUP VARCHAR(20) NULL  
, CHANNEL VARCHAR(40) NULL  
, COUNTRY VARCHAR(20) NULL  
, REGION_CODE VARCHAR(20) NULL  
, NATIONALITY VARCHAR(20) NULL  
, PSUEDO_ROOM_YN VARCHAR(1) NULL  
, ADULTS_TAX_FREE INT NULL  
, CHILDREN_TAX_FREE INT NULL  
, STAY_ROOMS INT NULL  
, STAY_PERSONS INT NULL  
, STAY_ADULTS INT NULL  
, STAY_CHILDREN INT NULL  
, ARR_ROOMS INT NULL  
, ARR_PERSONS INT NULL  
, DEP_ROOMS INT NULL  
, DEP_PERSONS INT NULL  
, DAY_USE_ROOMS INT NULL  
, DAY_USE_PERSONS INT NULL  
, CANCELLED_ROOMS INT NULL  
, CANCELLED_PERSONS INT NULL  
, NO_SHOW_ROOMS INT NULL  
, NO_SHOW_PERSONS INT NULL  
, SINGLE_OCCUPANCY INT NULL  
, MULTIPLE_OCCUPANCY INT NULL  
, CRIBS INT NULL  
, EXTRA_BEDS INT NULL  
, OTHER_REVENUE NUMERIC(38,12) NULL  
, PACKAGE_OTHER_REVENUE NUMERIC(38,12) NULL  
, TOTAL_OTHER_TAX NUMERIC(38,12) NULL  
, COUNTRY_MAIN_GROUP VARCHAR(40) NULL  
, [STATE] VARCHAR(40) NULL  
, FISCAL_REGION_CODE VARCHAR(40) NULL  
, NON_REVENUE NUMERIC(38,12) NULL  
, PACKAGE_NON_REVENUE NUMERIC(38,12) NULL  
, TOTAL_NON_REVENUE_TAX NUMERIC(38,12) NULL  
, PR_ROOM_REVENUE NUMERIC(38,12) NULL  
, PR_FOOD_REVENUE NUMERIC(38,12) NULL  
, PR_PACKAGE_ROOM_REVENUE NUMERIC(38,12) NULL  
, PR_PACKAGE_FOOD_REVENUE NUMERIC(38,12) NULL  
, PR_TOTAL_ROOM_TAX NUMERIC(38,12) NULL  
, PR_TOTAL_FOOD_TAX NUMERIC(38,12) NULL  
, PR_TOTAL_PACKAGE_REVENUE NUMERIC(38,12) NULL  
, PR_TOTAL_REVENUE NUMERIC(38,12) NULL  
, PR_TOTAL_TAX NUMERIC(38,12) NULL  
, PR_OTHER_REVENUE NUMERIC(38,12) NULL  
, PR_PACKAGE_OTHER_REVENUE NUMERIC(38,12) NULL  
, PR_TOTAL_OTHER_TAX NUMERIC(38,12) NULL  
, PR_NON_REVENUE NUMERIC(38,12) NULL  
, PR_PACKAGE_NON_REVENUE NUMERIC(38,12) NULL  
, PR_TOTAL_NON_REVENUE_TAX NUMERIC(38,12) NULL  
, NIGHTS INT NULL  
, NO_OF_STAYS INT NULL  
, RESERVATION_NIGHTS INT NULL  
, RESERVATION_ARRIVALS INT NULL  
, RESERVATION_NO_OF_STAYS INT NULL  
, DAY_USE_RESERVATIONS INT NULL  
, CANCELLED_RESERVATIONS INT NULL  
, NO_SHOW_RESERVATIONS INT NULL  
, CITY VARCHAR(40) NULL  
, ZIP_CODE VARCHAR(15) NULL  
, DISTRICT VARCHAR(10) NULL  
, CASH_ROOM_NTS INT NULL  
, COMP_ROOM_NTS INT NULL  
, CASH_ROOM_REVENUE INT NULL  
, COMP_ROOM_REVENUE INT NULL  
, RES_INSERT_SOURCE VARCHAR(20) NULL  
, RES_INSERT_SOURCE_TYPE VARCHAR(40) NULL  
, CHILDREN1 INT NULL  
, CHILDREN2 INT NULL  
, CHILDREN3 INT NULL  
, CHILDREN4 INT NULL  
, CHILDREN5 INT NULL  
, FF_MEMBERSHIP_TYPE VARCHAR(20) NULL  
, FG_MEMBERSHIP_TYPE VARCHAR(20) NULL  
, PROMOTION_CODE VARCHAR(20) NULL  
, OWNER_FF_FLAG VARCHAR(1) NULL  
, OWNER_RENTAL_FLAG VARCHAR(1) NULL  
, CENTRAL_CURRENCY_CODE VARCHAR(20) NULL  
, BOOKED_ROOM_CATEGORY VARCHAR(20) NULL  
, BOOKED_ROOM_TYPE VARCHAR(20) NULL  
, ACTUAL_REVENUE INT NULL  
, ACTUAL_ROOMS INT NULL  
, ROOM_REVENUE_RES_IND_DED INT NULL  
, STAY_ROOMS_RES_IND_DED INT NULL  
, ROOM_REVENUE_RES_BLK_DED INT NULL  
, STAY_ROOMS_RES_BLK_DED INT NULL  
, RATE_AMOUNT INT NULL  
, CENTRAL_EXCH_RATE INT NULL  
, LEAD_DAYS INT NULL  
, LEAD_COUNT INT NULL  
, UPSOLD_AMOUNT INT NULL  
, C_ROOM_REVENUE INT NULL  
, C_FOOD_REVENUE INT NULL  
, C_PACKAGE_ROOM_REVENUE INT NULL  
, C_PACKAGE_FOOD_REVENUE INT NULL  
, C_TOTAL_ROOM_TAX INT NULL  
, C_TOTAL_FOOD_TAX INT NULL  
, C_TOTAL_PACKAGE_REVENUE INT NULL  
, C_TOTAL_REVENUE INT NULL  
, C_TOTAL_TAX INT NULL  
, C_OTHER_REVENUE INT NULL  
, C_PACKAGE_OTHER_REVENUE INT NULL  
, C_TOTAL_OTHER_TAX INT NULL  
, C_NON_REVENUE INT NULL  
, C_PACKAGE_NON_REVENUE INT NULL  
, C_TOTAL_NON_REVENUE_TAX INT NULL  
, C_PR_ROOM_REVENUE INT NULL  
, C_PR_FOOD_REVENUE INT NULL  
, C_PR_PACKAGE_ROOM_REVENUE INT NULL  
, C_PR_PACKAGE_FOOD_REVENUE INT NULL  
, C_PR_TOTAL_ROOM_TAX INT NULL  
, C_PR_TOTAL_FOOD_TAX INT NULL  
, C_PR_TOTAL_PACKAGE_REVENUE INT NULL  
, C_PR_TOTAL_REVENUE INT NULL  
, C_PR_TOTAL_TAX INT NULL  
, C_PR_OTHER_REVENUE INT NULL  
, C_PR_PACKAGE_OTHER_REVENUE INT NULL  
, C_PR_TOTAL_OTHER_TAX INT NULL  
, C_PR_NON_REVENUE INT NULL  
, C_PR_PACKAGE_NON_REVENUE INT NULL  
, C_PR_TOTAL_NON_REVENUE_TAX INT NULL  
, C_CASH_ROOM_REVENUE INT NULL  
, C_COMP_ROOM_REVENUE INT NULL  
, C_ACTUAL_REVENUE INT NULL  
, C_ROOM_REVENUE_RES_IND_DED INT NULL  
, C_ROOM_REVENUE_RES_BLK_DED INT NULL  
, C_RATE_AMOUNT INT NULL  
, C_UPSOLD_AMOUNT INT NULL  
, PARENT_COMPANY_ID INT NULL  
, COMPANY_ROOM INT NULL  
, TRAVEL_ROOM INT NULL  
, GROUP_ROOM INT NULL  
, SOURCE_ROOM INT NULL  
, GUEST_REVENUE INT NULL  
, COMPANY_REVENUE INT NULL  
, TRAVEL_REVENUE INT NULL  
, GROUP_REVENUE INT NULL  
, SOURCE_REVENUE INT NULL  
, GUEST_ROOM_REVENUE INT NULL  
, COMPANY_ROOM_REVENUE INT NULL  
, TRAVEL_ROOM_REVENUE INT NULL  
, GROUP_ROOM_REVENUE INT NULL  
, SOURCE_ROOM_REVENUE INT NULL  
, GUEST_FB_REVENUE INT NULL  
, COMPANY_FB_REVENUE INT NULL  
, TRAVEL_FB_REVENUE INT NULL  
, GROUP_FB_REVENUE INT NULL  
, SOURCE_FB_REVENUE INT NULL  
, UPSOLD_ROOM INT NULL  
, UPGRADE_ROOM INT NULL  
, REGULAR_ROOM INT NULL  
, STAY_MONTH VARCHAR(7) NULL  
, STAYS INT NULL  
, LOS INT NULL  
, LOS_A INT NULL  
, LOS_B INT NULL  
, LOS_C INT NULL  
, ARR_ADULTS INT NULL  
, ARR_CHILDREN INT NULL  
, BUSINESS_DATE_CREATED DATE NULL  
	
	------------[RESORT] [varchar](20) NULL,
	------------[BUSINESS_DATE] [date] NULL,
	------------[NAME_ID] [int] NULL,
	------------[RATE_CODE] [varchar](20) NULL,
	------------[SOURCE_CODE] [varchar](20) NULL,
	------------[MARKET_CODE] [varchar](20) NULL,
	------------[ROOM_CATEGORY] [varchar](20) NULL,
	------------[COMPANY_ID] [int] NULL,
	------------[AGENT_ID] [int] NULL,
	------------[GROUP_ID] [int] NULL,
	------------[SOURCE_PROF_ID] [int] NULL,
	------------[RESV_STATUS] [varchar](20) NULL,
	------------[TRUNC_BEGIN_DATE] [date] NULL,
	------------[TRUNC_END_DATE] [date] NULL,
	------------[RESV_NAME_ID] [int] NULL,
	------------[QUANTITY] [int] NULL,
	------------[PHYSICAL_QUANTITY] [int] NULL,
	------------[DUE_OUT_YN] [varchar](1) NULL,
	------------[ROOM_RESV_STATUS] [varchar](20) NULL,
	------------[ADULTS] [int] NULL,
	------------[CHILDREN] [int] NULL,
	------------[ROOM_ADULTS] [int] NULL,
	------------[ROOM_CHILDREN] [int] NULL,
	------------[PRIMARY_YN] [int] NULL,
	------------[ALLOTMENT_HEADER_ID] [int] NULL,
	------------[ROOM_REVENUE] [numeric](38, 12) NULL,
	------------[FOOD_REVENUE] [numeric](38, 12) NULL,
	------------[PACKAGE_ROOM_REVENUE] [numeric](38, 12) NULL,
	------------[PACKAGE_FOOD_REVENUE] [numeric](38, 12) NULL,
	------------[TOTAL_ROOM_TAX] [numeric](38, 12) NULL,
	------------[TOTAL_FOOD_TAX] [numeric](38, 12) NULL,
	------------[TOTAL_PACKAGE_REVENUE] [numeric](38, 12) NULL,
	------------[TOTAL_REVENUE] [numeric](38, 12) NULL,
	------------[TOTAL_TAX] [numeric](38, 12) NULL,
	------------[INSERT_DATE] [date] NULL,
	------------[ORIGINAL_END_DATE] [date] NULL,
	------------[WALKIN_YN] [varchar](1) NULL,
	------------[RESERVATION_DATE] [date] NULL,
	------------[ROOM_CLASS] [varchar](20) NULL,
	------------[VIP_STATUS] [varchar](20) NULL,
	------------[CANCELLATION_DATE] [date] NULL,
	------------[BIRTH_DATE] [date] NULL,
	------------[ROOM] [varchar](20) NULL,
	------------[MEMBERSHIP_ID] [int] NULL,
	------------[CONTACT_ID] [int] NULL,
	------------[RATE_CATEGORY] [varchar](20) NULL,
	------------[MARKET_MAIN_GROUP] [varchar](20) NULL,
	------------[SOURCE_MAIN_GROUP] [varchar](20) NULL,
	------------[CHANNEL] [varchar](40) NULL,
	------------[COUNTRY] [varchar](20) NULL,
	------------[REGION_CODE] [varchar](20) NULL,
	------------[NATIONALITY] [varchar](20) NULL,
	------------[PSUEDO_ROOM_YN] [varchar](1) NULL,
	------------[ADULTS_TAX_FREE] [int] NULL,
	------------[CHILDREN_TAX_FREE] [int] NULL,
	------------[STAY_ROOMS] [int] NULL,
	------------[STAY_PERSONS] [int] NULL,
	------------[STAY_ADULTS] [int] NULL,
	------------[STAY_CHILDREN] [int] NULL,
	------------[ARR_ROOMS] [int] NULL,
	------------[ARR_PERSONS] [int] NULL,
	------------[DEP_ROOMS] [int] NULL,
	------------[DEP_PERSONS] [int] NULL,
	------------[DAY_USE_ROOMS] [int] NULL,
	------------[DAY_USE_PERSONS] [int] NULL,
	------------[CANCELLED_ROOMS] [int] NULL,
	------------[CANCELLED_PERSONS] [int] NULL,
	------------[NO_SHOW_ROOMS] [int] NULL,
	------------[NO_SHOW_PERSONS] [int] NULL,
	------------[SINGLE_OCCUPANCY] [int] NULL,
	------------[MULTIPLE_OCCUPANCY] [int] NULL,
	------------[CRIBS] [int] NULL,
	------------[EXTRA_BEDS] [int] NULL,
	------------[OTHER_REVENUE] [numeric](38, 12) NULL,
	------------[PACKAGE_OTHER_REVENUE] [numeric](38, 12) NULL,
	------------[TOTAL_OTHER_TAX] [numeric](38, 12) NULL,
	------------[COUNTRY_MAIN_GROUP] [varchar](40) NULL,
	------------[STATE] [varchar](40) NULL,
	------------[FISCAL_REGION_CODE] [varchar](40) NULL,
	------------[NON_REVENUE] [numeric](38, 12) NULL,
	------------[PACKAGE_NON_REVENUE] [numeric](38, 12) NULL,
	------------[TOTAL_NON_REVENUE_TAX] [numeric](38, 12) NULL,
	------------[PR_ROOM_REVENUE] [numeric](38, 12) NULL,
	------------[PR_FOOD_REVENUE] [numeric](38, 12) NULL,
	------------[PR_PACKAGE_ROOM_REVENUE] [numeric](38, 12) NULL,
	------------[PR_PACKAGE_FOOD_REVENUE] [numeric](38, 12) NULL,
	------------[PR_TOTAL_ROOM_TAX] [numeric](38, 12) NULL,
	------------[PR_TOTAL_FOOD_TAX] [numeric](38, 12) NULL,
	------------[PR_TOTAL_PACKAGE_REVENUE] [numeric](38, 12) NULL,
	------------[PR_TOTAL_REVENUE] [numeric](38, 12) NULL,
	------------[PR_TOTAL_TAX] [numeric](38, 12) NULL,
	------------[PR_OTHER_REVENUE] [numeric](38, 12) NULL,
	------------[PR_PACKAGE_OTHER_REVENUE] [numeric](38, 12) NULL,
	------------[PR_TOTAL_OTHER_TAX] [numeric](38, 12) NULL,
	------------[PR_NON_REVENUE] [numeric](38, 12) NULL,
	------------[PR_PACKAGE_NON_REVENUE] [numeric](38, 12) NULL,
	------------[PR_TOTAL_NON_REVENUE_TAX] [numeric](38, 12) NULL,
	------------[NIGHTS] [int] NULL,
	------------[NO_OF_STAYS] [int] NULL,
	------------[RESERVATION_NIGHTS] [int] NULL,
	------------[RESERVATION_ARRIVALS] [int] NULL,
	------------[RESERVATION_NO_OF_STAYS] [int] NULL,
	------------[DAY_USE_RESERVATIONS] [int] NULL,
	------------[CANCELLED_RESERVATIONS] [int] NULL,
	------------[NO_SHOW_RESERVATIONS] [int] NULL,
	------------[CITY] [varchar](40) NULL,
	------------[ZIP_CODE] [varchar](15) NULL,
	------------[DISTRICT] [varchar](10) NULL,
	------------[CASH_ROOM_NTS] [int] NULL,
	------------[COMP_ROOM_NTS] [int] NULL,
	------------[CASH_ROOM_REVENUE] [int] NULL,
	------------[COMP_ROOM_REVENUE] [int] NULL,
	------------[CHILDREN1] [int] NULL,
	------------[CHILDREN2] [int] NULL,
	------------[CHILDREN3] [int] NULL,
	------------[CHILDREN4] [int] NULL,
	------------[CHILDREN5] [int] NULL,
	------------[FF_MEMBERSHIP_TYPE] [varchar](20) NULL,
	------------[FG_MEMBERSHIP_TYPE] [varchar](20) NULL,
	------------[PROMOTION_CODE] [varchar](20) NULL,
	------------[RES_INSERT_SOURCE] [varchar](20) NULL,
	------------[RES_INSERT_SOURCE_TYPE] [varchar](40) NULL,
	------------[OWNER_FF_FLAG] [varchar](1) NULL,
	------------[OWNER_RENTAL_FLAG] [varchar](1) NULL,
	------------[CENTRAL_CURRENCY_CODE] [varchar](20) NULL,
	------------[CENTRAL_EXCHANGE_RATE] [int] NULL,
	------------[BOOKED_ROOM_CATEGORY] [varchar](20) NULL,
	------------[BUSINESS_DATE_CREATED] [date] NULL,
	------------[RATE_AMOUNT] [int] NULL,
	------------[PARENT_COMPANY_ID] [int] NULL,
	------------[HOUSE_USE_YN] [varchar](1) NULL,
	------------[COMPLIMENTARY_YN] [varchar](1) NULL,
	------------[BI_RESV_NAME_ID] [int] NULL,
	------------[ADV_FOOD_REVENUE] [int] NULL,
	------------[ADV_NON_REVENUE] [int] NULL,
	------------[ADV_OTHER_REVENUE] [int] NULL,
	------------[ADV_ROOM_REVENUE] [int] NULL,
	------------[ADV_TOTAL_FOOD_TAX] [int] NULL,
	------------[ADV_TOTAL_NON_REVENUE_TAX] [int] NULL,
	------------[ADV_TOTAL_OTHER_TAX] [int] NULL,
	------------[ADV_TOTAL_REVENUE] [int] NULL,
	------------[ADV_TOTAL_ROOM_TAX] [int] NULL,
	------------[ADV_TOTAL_TAX] [int] NULL,
	------------[PR_ADV_FOOD_REVENUE] [int] NULL,
	------------[PR_ADV_NON_REVENUE] [int] NULL,
	------------[PR_ADV_OTHER_REVENUE] [int] NULL,
	------------[PR_ADV_ROOM_REVENUE] [int] NULL,
	------------[PR_ADV_TOTAL_FOOD_TAX] [int] NULL,
	------------[PR_ADV_TOTAL_NON_REVENUE_TAX] [int] NULL,
	------------[PR_ADV_TOTAL_OTHER_TAX] [int] NULL,
	------------[PR_ADV_TOTAL_REVENUE] [int] NULL,
	------------[PR_ADV_TOTAL_ROOM_TAX] [int] NULL,
	------------[PR_ADV_TOTAL_TAX] [int] NULL,
	------------[UPSOLD_REVENUE] [int] NULL,
	------------[FLGD_ROOM_REVENUE] [int] NULL,
	------------[FLGD_FOOD_REVENUE] [int] NULL,
	------------[FLGD_NON_REVENUE] [int] NULL,
	------------[FLGD_OTHER_REVENUE] [int] NULL,
	------------[FLGD_TOTAL_ROOM_TAX] [int] NULL,
	------------[FLGD_TOTAL_FOOD_TAX] [int] NULL,
	------------[FLGD_TOTAL_NON_REVENUE_TAX] [int] NULL,
	------------[FLGD_TOTAL_OTHER_TAX] [int] NULL,
	------------[FLGD_TOTAL_REVENUE] [int] NULL,
	------------[FLGD_TOTAL_TAX] [int] NULL,
	------------[CONTACT_YN] [varchar](1) NULL,
	------------[EXTENDED_STAY_TIER] [int] NULL,
	------------[RS_ADV_TOTAL_REVENUE] [int] NULL,
	------------[RS_ADV_ROOM_REVENUE] [int] NULL,
	------------[RS_ADV_FOOD_REVENUE] [int] NULL,
	------------[RS_ADV_OTHER_REVENUE] [int] NULL,
	------------[RS_ADV_NON_REVENUE] [int] NULL,
	------------[RS_ADV_TOTAL_TAX] [int] NULL,
	------------[RS_ADV_ROOM_TAX] [int] NULL,
	------------[RS_ADV_FOOD_TAX] [int] NULL,
	------------[RS_ADV_OTHER_TAX] [int] NULL,
	------------[RS_ADV_NON_REVENUE_TAX] [int] NULL,
	------------[UPDATE_DATE] [date] NULL
) ON [PRIMARY]

GO


