SELECT TOP (1000) 
--[ACTIVE_YN]
--      ,[ACTUAL_CHECK_IN_DATE]
--      ,[ACTUAL_CHECK_OUT_DATE]
--      ,[ARRIVAL]
--      ,[ARRIVAL_TIME]
--      ,[BLOCK_CODE]
--      ,[BLOCK_DESCRIPTION]
--      ,[CONFIRMATION_NO]
--      ,[DEPARTURE]
--      ,[DEPARTURE_TIME]
--      ,[EMAIL]
--      ,[EMAIL_YN]
--      ,[FB_REVENUE]
--      ,[GENDER]
--      ,[GUEST_COUNTRY]
--      ,[GUEST_COUNTRY_DESC]
--      ,[GUEST_FIRST_NAME]
--      ,[GUEST_NAME]
      [INSERT_DATE]
      --,[MAIL_YN]
      --,[MARKET_CODE]
      --,[MEMBERSHIP_EXPIRATION_DATE]
      --,[MEMBERSHIP_LEVEL]
      --,[MEMBERSHIP_NAME_ON_CARD]
      --,[MEMBERSHIP_NUMBER]
      --,[MEMBERSHIP_TYPE]
      ,[NAME_MEMBERSHIP_ID]
      --,[NAME_MEMBERSHIP_LEVEL]
      --,[NAME_MEMBERSHIP_NUMBER]
      --,[NAME_MEMBERSHIP_TYPE]
      --,[NIGHTS]
      --,[NO_OF_ROOMS]
      --,[ORIGIN_OF_BOOKING]
      --,[PROMOTIONS]
      --,[RATE_CODE]
      --,[RESERVATION_DATE]
      --,[RESORT]
      --,[RESV_STATUS]
      --,[ROOM]
      --,[ROOM_RESORT]
      --,[ROOM_REVENUE]
      --,[TOTAL_REVENUE]
      --,[VIP_DESC]
      --,[VIP_NAME]
      --,[VIP_STATUS]
      --,[TOTAL_NIGHTS]
      --,[TOTAL_STAY]
      --,[LAST_STAY]
      --,[TOTAL_NIGHTS_LASTYR]
      --,[TOTAL_STAY_LASTYR]
      --,[FIRST_STAY_YN]
      --,[ROOM_CATEGORY_LABEL]
      --,[MY_ROOM_RATE]
      ,[RESV_NAME_ID]
      --,[ROOM_CLASS]
      ,[ETL_LAST_UPDATE_DATE]
      ,[UPDATE_DATE]
      ,[ETL_INSERT_DATE]
      --,[GUEST_PHONE]
      --,[PHONE_TYPE]
      --,[ADULTS]
      --,[CHILDREN]
  FROM [OperaDM].[dbo].[NAME_RESERVATION]
