BACKUP DATABASE ig_app 
TO  DISK = N'\\DBAMBK01PR\SQLBackup02\INFOGEN_UPGRADE\ig_app_DIFF.bak' 
WITH 
  DIFFERENTIAL
, FORMAT
, INIT
, COMPRESSION 
, STATS = 5

BACKUP DATABASE ig_business 
TO  DISK = N'\\DBAMBK01PR\SQLBackup02\INFOGEN_UPGRADE\ig_business_DIFF.bak' 
WITH 
  DIFFERENTIAL
, FORMAT
, INIT
, COMPRESSION 
, STATS = 5

BACKUP DATABASE ig_dimension 
TO  DISK = N'\\DBAMBK01PR\SQLBackup02\INFOGEN_UPGRADE\ig_dimension_DIFF.bak' 
WITH 
  DIFFERENTIAL
, FORMAT
, INIT
, COMPRESSION 
, STATS = 5

BACKUP DATABASE ig_log 
TO  DISK = N'\\DBAMBK01PR\SQLBackup02\INFOGEN_UPGRADE\ig_log_DIFF.bak' 
WITH 
  DIFFERENTIAL
, FORMAT
, INIT
, COMPRESSION 
, STATS = 5

BACKUP DATABASE ig_revconfig 
TO  DISK = N'\\DBAMBK01PR\SQLBackup02\INFOGEN_UPGRADE\ig_revconfig_DIFF.bak' 
WITH 
  DIFFERENTIAL
, FORMAT
, INIT
, COMPRESSION 
, STATS = 5

BACKUP DATABASE ig_task 
TO  DISK = N'\\DBAMBK01PR\SQLBackup02\INFOGEN_UPGRADE\ig_task_DIFF.bak' 
WITH 
  DIFFERENTIAL
, FORMAT
, INIT
, COMPRESSION 
, STATS = 5

BACKUP DATABASE ig_transaction 
TO  DISK = N'\\DBAMBK01PR\SQLBackup02\INFOGEN_UPGRADE\ig_transaction_DIFF.bak' 
WITH 
  DIFFERENTIAL
, FORMAT
, INIT
, COMPRESSION 
, STATS = 5

BACKUP DATABASE it_cfg 
TO  DISK = N'\\DBAMBK01PR\SQLBackup02\INFOGEN_UPGRADE\it_cfg_DIFF.bak' 
WITH 
  DIFFERENTIAL
, FORMAT
, INIT
, COMPRESSION 
, STATS = 5

BACKUP DATABASE it_ga 
TO  DISK = N'\\DBAMBK01PR\SQLBackup02\INFOGEN_UPGRADE\it_ga_DIFF.bak' 
WITH 
  DIFFERENTIAL
, FORMAT
, INIT
, COMPRESSION 
, STATS = 5

BACKUP DATABASE it_perms 
TO  DISK = N'\\DBAMBK01PR\SQLBackup02\INFOGEN_UPGRADE\it_perms_DIFF.bak' 
WITH 
  DIFFERENTIAL
, FORMAT
, INIT
, COMPRESSION 
, STATS = 5

BACKUP DATABASE it_rlt 
TO  DISK = N'\\DBAMBK01PR\SQLBackup02\INFOGEN_UPGRADE\it_rlt_DIFF.bak' 
WITH 
  DIFFERENTIAL
, FORMAT
, INIT
, COMPRESSION 
, STATS = 5

BACKUP DATABASE it_sysweb 
TO  DISK = N'\\DBAMBK01PR\SQLBackup02\INFOGEN_UPGRADE\it_sysweb_DIFF.bak' 
WITH 
  DIFFERENTIAL
, FORMAT
, INIT
, COMPRESSION 
, STATS = 5

BACKUP DATABASE it_trn 
TO  DISK = N'\\DBAMBK01PR\SQLBackup02\INFOGEN_UPGRADE\it_trn_DIFF.bak' 
WITH 
  DIFFERENTIAL
, FORMAT
, INIT
, COMPRESSION 
, STATS = 5

GO