USE master;
GO

ALTER DATABASE mmdata
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE;
GO

BACKUP DATABASE [mmdata] TO  DISK = N'\\DBAMBK01pr\SQLBackup01\mmdata.bak' WITH NOFORMAT, INIT,  NAME = N'mmdata-Full Database Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
GO

ALTER DATABASE mmdata
SET MULTI_USER
WITH ROLLBACK IMMEDIATE;
GO

ALTER DATABASE mmdata
SET READ_ONLY 
WITH ROLLBACK IMMEDIATE;
GO