SELECT A.[PlayerId]
, A.[TranId]
      ,A.[PrizeId]
, P.Prizecode
, P.[PrizeName]
, A.[PrizeQty]
, A.[TranCodeId]
, A.[GamingDt]
, A.[Shift]
, A.[AgingDt]
, A.[PostDtm]
, A.[ComputerName]
, A.[EmpID]
, A.[AuthEmpId]
, A.[DeptID]
, A.[CasinoID]
, A.[AreaID]
, A.[LocnID]
, A.[GameID]
, A.[DenomID]
, A.[GroupID]
, A.[PlayerTypeID]
, A.[DocumentNo]
, A.[Ref1]
, A.[Ref2]
, A.[AuthAward]
, A.[AwardUsed]
, A.[AwardCode]
, A.[RelatedTranId]
, A.[VoidTranId]
, A.[VoidEmpId]
, A.[VoidAuthEmpId]
, A.[IsVoid]
, A.[IsOpenItem]
, A.[Flags]
, A.[Outlet]
, A.[ItemCode]
, A.[IsDistributed]
, A.[SequenceId]
, A.[OldRelatedTranID]
, A.[SiteId]
, A.[ServerWorkStation]
, A.[DataRowVersion]
, A.[PlayerSessionId]
, A.[PromotionId]
, A.[TripDt]
, A.[TripId]
, A.[TripType]
, A.[RepId]
, A.[AllowedPurgeDt]
, A.[CreatedBy]
, A.[CreatedDtm]
, A.[ModifiedBy]
, A.[ModifiedDtm]
  FROM [iQ-Gaming].[CMP_13-1].[tAwards] A

  JOIN [CMP_13-1].[tPrize] P
  ON A.PrizeId = P.PrizeId

      where playerid = '10472679'
	    AND Prizecode = 'EvalSilver'

	order by gamingdt desc