SELECT TOP (1000) [TranID]
      ,[PlayerId]
      ,[IsVoid]
      ,[TranCodeID]
      ,[GamingDt]
      --,[Shift]
      --,[AgingDt]
      --,[PostDtm]
      --,[ComputerName]
      --,[EmpID]
      --,[AuthEmpId]
      --,[DeptID]
      --,[CasinoID]
      --,[AreaID]
      --,[LocnID]
      --,[GameID]
      --,[DenomID]
      --,[RepID]
      --,[DocumentNo]
      --,[Ref1]
      --,[Ref2]
      --,[IsOpenItem]
      --,[GroupID]
      --,[PlayerTypeID]
      --,[OriginalPlayerID]
      --,[RelatedTranID]
      --,[VoidTranID]
      --,[Flags]
      --,[IsDistributed]
      --,[OldRelatedTranID]
      --,[StratId]
      --,[RatingStartDtm]
      --,[RatingEndDtm]
      --,[CashBuyIn]
      --,[CreditBuyIn]
      --,[ChipBuyIn]
      --,[PromoBuyIn]
      --,[ECreditBuyIn]
      --,[ECashBuyIn]
      --,[RatingPeriodMinutes]
      --,[Plays]
      --,[Bet]
      --,[PaidOut]
      --,[WalkedWith]
      --,[TheorHoldPc]
      --,[TheorWin]
      --,[GamePts]
      --,[CasinoWinCalcMethod]
      --,[CasinoWin]
      --,[HighBet]
      --,[MgmtRating]
      --,[LocnMinBet]
      --,[LocnMaxBet]
      --,[CasinoStatistic]
      --,[CreatedDtm]
      --,[CreatedBy]
      --,[ModifiedDtm]
      --,[ModifiedBy]
      --,[SeatNo]
      --,[FreqId]
      --,[AdjBet]
      --,[AdjPaidOut]
      --,[AdjTheorWin]
      --,[AdjCasinoWin]
      --,[DataRowVersion]
      --,[ActualRatingStartTime]
      --,[ActualRatingEndTime]
      --,[TripDt]
      --,[TripId]
      --,[TripType]
      --,[AllowedPurgeDt]
      --,[VIPPlayerID]
      --,[BetByBet]
      --,[IsBetByBet]
      --,[AverageBet]
      ,[PromoChips]
  FROM [CMP13].[dbo].[tTableRating]

  WHERE [PromoChips] <> 0
    AND [PromoChips] IS NOT NULL

ORDER BY 
  [PlayerId]
, [GamingDt]
