SELECT
  i.GUEST_KEY 
, g.LASTNAME
, g.FIRSTNAME
, i.INVOICEID
, i.INVOICE_NO
, i.TOTAL
, i.NETTOTAL
, i.GRATUITY
, i.GTOTAL
, i.ENTERED

, g.ENTERED AS GUEST_REC_ENTERED
, g.UPDATED AS GUEST_REC_UPDATED

FROM SPAWIN...INVOICE AS i

JOIN SPAWIN...GUESTS AS g
ON i.GUEST_KEY = g.GUEST_KEY

ORDER BY 
  GUEST_KEY
, LASTNAME
, FIRSTNAME
, INVOICE_NO