USE [SDSVJPRD_Archive]
GO

DECLARE @GAMINGDATE DATETIME = '2018-05-23';

DECLARE @SITENUM SMALLINT = 209;

SELECT 
 SITE_NUM 
,REDEEMED_SLOT 
,REDEEMED_STAND 
,REDEEMED_DATE_TIME 
,ISSSE_SLOT 
,ISSUE_STAND 
,TICKET_NUMBER 
,[VALUE] 
,GAMING_DATE 
,asd 
,AREA 
,[TYPE] 
,SFTBARCODE 
,SFTAUDIT_CODE 
,CAST(0 AS FLOAT) AS SFT_CASH_COP_COUNT 
,CAST(0 AS FLOAT) AS SFT_CASH_COP_VALUE 
,CAST(0 AS FLOAT) AS SFT_NON_CASH_COP_COUNT 
,CAST(0 AS FLOAT) AS SFT_NON_CASH_COP_VALUE 

FROM COMMON.REPORT_VIEW_RID0504_CR59557_TKAVAR_MISSING_SOFTCOUNT_TICKETS_DETAIL_SCUPLOAD('2018-05-23', 209) --@SITENUM) 
--FROM COMMON.REPORT_VIEW_RID0504_CR59557_TKAVAR_MISSING_SOFTCOUNT_TICKETS_DETAIL_SCUPLOAD('05/23/2018', 209) 

WHERE asd = '2018-05-23' 

--AND SITE_NUM = @SITENUM 
--AND SITE_NUM IN (@SITENUM) 


AND SFTBARCODE IS NULL 
AND isSoftCountUploaded = 1    

order by REDEEMED_SLOT