--SELECT SLPRUV_SLP_ID,SLPRU_PTYP_ID,SLPRU_VALUE,SLPRU_GDAY_DATE,OptLockVersion,CREATED_TS 
--FROM  ACCOUNTING.SLIP_ROLLUP_VALUES (NOLOCK)  
--WHERE CAST(SLPRU_GDAY_DATE as DATE) >= DATEADD(MONTH, -12, GETUTCDATE()) AND (SLPRUV_SLP_ID >= 232902095001700015 OR SLPRU_GDAY_DATE >= '2023-10-17')

SELECT MAX(MVR_ID)
FROM  ACCOUNTING.METER_VALUE_ROLLUP (NOLOCK)  

SELECT MVR_ID,MVR_NAST_ID,MVR_GDAY_DATE,MVR_PTYP_ID,MVR_PLAYS_VAL,MVR_BETS_VAL,MVR_WINS_VAL,MVR_COIN_DROP_VAL,MVR_COIN_PURCHASE_VAL,MVR_COIN_COLLECTED_VAL,MVR_$1_VAL,MVR_$5_VAL,MVR_$10_VAL,MVR_$20_VAL,MVR_$50_VAL,MVR_$100_VAL,MVR_COUPON_CREDIT_VAL,MVR_BILL_CREDIT_VAL,MVR_EFT_IN_PROMO_CASH_VAL,MVR_EFT_OUT_PROMO_CASH_VAL,MVR_EFT_IN_NON_CASH_VAL,MVR_EFT_OUT_NON_CASH_VAL,MVR_TKT_IN_CASH_VAL,MVR_TKT_OUT_CASH_VAL,MVR_TKT_IN_NON_CASH_VAL,MVR_TKT_OUT_NON_CASH_VAL,MVR_TKT_IN_CNT_CASH_VAL,MVR_TKT_OUT_CNT_CASH_VAL,MVR_TKT_IN_CNT_NON_CASH_VAL,MVR_TKT_OUT_CNT_NON_CASH_VAL,MVR_HP_JACKPOT_VAL,MVR_CANCELLED_CREDIT_HP_VAL,MVR_HP_PROG_JACKPOT_VAL,MVR_MC_PAID_PROG_WINS_VAL,MVR_MC_PAID_MYST_JACKPOT_VAL,MVR_HP_MYST_JACKPOT_VAL,MVR_EFT_IN_CASH_VAL,MVR_EFT_OUT_CASH_VAL,MVR_GAME_EFT_CASH_IN_VAL,MVR_GAME_EFT_NON_CASH_IN_VAL,MVR_GAME_HP_JACKPOT_VAL,MVR_TKT_PROMO_CASH_IN_VAL,MVR_TKT_PROMO_CNT_CASH_IN_VAL,MVR_NET_DROP_VAL,MVR_DAYS_ONLINE_VAL,MVR_DAYS_OFFLINE_VAL,MVR_TKT_EXPENSE_VAL,MVR_TKT_CASH_EXP_VAL,MVR_TKT_CASH_CNT_EXP_VAL,MVR_TKT_NON_CASH_EXP_VAL,MVR_TKT_NON_CASH_CNT_EXP_VAL,MVR_TOTAL_EXPENSE_VAL,MVR_THEORETICAL_WIN_VAL,MVR_IS_LATEST_VAL,MVR_PRD_START_TS,MVR_PRD_DAYS_ELAPSED,MVR_PRD_DAYS_TOTAL,OptLockVersion,MVR_CASH_HOST_TKT_TRANS_VAL,MVR_CASH_HOST_TKT_TRANS_CNT_VAL,MVR_HOPPER_CNT_VAL,MVR_GAME_CREDITS_VAL,MVR_RESTRICTED_BETS_VAL,MVR_SLOT_DOOR_OPEN_VAL,MVR_UNRESTRICTED_BETS_VAL 
FROM  ACCOUNTING.METER_VALUE_ROLLUP (NOLOCK)  
WHERE CAST(MVR_GDAY_DATE as DATE) >= DATEADD(MONTH, -12, GETUTCDATE()) AND (MVR_ID >= 232932095001700063 OR MVR_GDAY_DATE >= '2023-10-18')
--WHERE CAST(MVR_GDAY_DATE as DATE) >= DATEADD(MONTH, -12, GETUTCDATE()) AND (MVR_ID >= 232912095001700063 OR MVR_GDAY_DATE >= CAST('2023-10-18' as DATE))

--SELECT SLPRUV_SLP_ID,SLPRU_PTYP_ID,SLPRU_VALUE,SLPRU_GDAY_DATE,OptLockVersion,CREATED_TS 
--FROM  ACCOUNTING.SLIP_ROLLUP_VALUES (NOLOCK)  
--WHERE CAST(SLPRU_GDAY_DATE as DATE) >= DATEADD(MONTH, -12, GETUTCDATE()) AND (SLPRUV_SLP_ID >= 232922095001700015 OR SLPRU_GDAY_DATE >= '2023-10-19')