SELECT SLPRUV_SLP_ID,SLPRU_PTYP_ID,SLPRU_VALUE,SLPRU_GDAY_DATE,OptLockVersion,CREATED_TS 
FROM  ACCOUNTING.SLIP_ROLLUP_VALUES (NOLOCK)  
WHERE CAST(SLPRU_GDAY_DATE as DATE) >= DATEADD(MONTH, -12, GETUTCDATE()) AND (SLPRUV_SLP_ID >= 232902095001700015 OR SLPRU_GDAY_DATE >= '2023-10-17')