
BACKUP DATABASE CMKTCRYPTO 
TO DISK = N'J:\_PreUpgrade_Backups\CMKTCRYPTO_DIFF.bak' 
WITH
  DIFFERENTIAL 
, CHECKSUM
, NOFORMAT
, COMPRESSION
, INIT
, STATS = 5
GO

BACKUP DATABASE CMP_RATING 
TO DISK = N'J:\_PreUpgrade_Backups\CMP_RATING_DIFF.bak' 
WITH 
  DIFFERENTIAL 
, CHECKSUM
, NOFORMAT
, COMPRESSION
, INIT
, STATS = 5
GO


----BACKUP DATABASE CMP13 
----TO DISK = N'J:\_PreUpgrade_Backups\CMP13_DIFF.bak' 
----WITH 
----  DIFFERENTIAL 
----, CHECKSUM
----, NOFORMAT
----, COMPRESSION
----, INIT
----, STATS = 5
----GO


BACKUP DATABASE CMPAPI 
TO DISK = N'J:\_PreUpgrade_Backups\CMPAPI_DIFF.bak' 
WITH 
  DIFFERENTIAL 
, CHECKSUM
, NOFORMAT
, COMPRESSION
, INIT
, STATS = 5
GO


BACKUP DATABASE CMPSDS 
TO DISK = N'J:\_PreUpgrade_Backups\CMPSDS_DIFF.bak' 
WITH 
  DIFFERENTIAL 
, CHECKSUM
, NOFORMAT
, COMPRESSION
, INIT
, STATS = 5
GO


BACKUP DATABASE dbInfogenesis 
TO DISK = N'J:\_PreUpgrade_Backups\dbInfogenesis_DIFF.bak' 
WITH 
  DIFFERENTIAL 
, CHECKSUM
, NOFORMAT
, COMPRESSION
, INIT
, STATS = 5
GO


BACKUP DATABASE PKMS_OBJ 
TO DISK = N'J:\_PreUpgrade_Backups\PKMS_OBJ_DIFF.bak' 
WITH 
  DIFFERENTIAL 
, CHECKSUM
, NOFORMAT
, COMPRESSION
, INIT
, STATS = 5
GO


BACKUP DATABASE PrintManager 
TO DISK = N'J:\_PreUpgrade_Backups\PrintManager_DIFF.bak' 
WITH 
  DIFFERENTIAL 
, CHECKSUM
, NOFORMAT
, COMPRESSION
, INIT
, STATS = 5
GO


BACKUP DATABASE TV13 
TO DISK = N'J:\_PreUpgrade_Backups\TV13_DIFF.bak' 
WITH 
  DIFFERENTIAL 
, CHECKSUM
, NOFORMAT
, COMPRESSION
, INIT
, STATS = 5
GO


BACKUP DATABASE TVAlert13 
TO DISK = N'J:\_PreUpgrade_Backups\TVAlert13_DIFF.bak' 
WITH 
  DIFFERENTIAL 
, CHECKSUM
, NOFORMAT
, COMPRESSION
, INIT
, STATS = 5
GO


BACKUP DATABASE vCMSUpdate 
TO DISK = N'J:\_PreUpgrade_Backups\vCMSUpdate_DIFF.bak' 
WITH 
  DIFFERENTIAL 
, CHECKSUM
, NOFORMAT
, COMPRESSION
, INIT
, STATS = 5
GO


BACKUP DATABASE ZipCodes 
TO DISK = N'J:\_PreUpgrade_Backups\ZipCodes_DIFF.bak' 
WITH 
  DIFFERENTIAL 
, CHECKSUM
, NOFORMAT
, COMPRESSION
, INIT
, STATS = 5
GO