USE [master]
GO

/****** Object:  Database [DriverJobDB]    Script Date: 8/18/2015 9:02:58 AM ******/
CREATE DATABASE [DriverJobDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DriverJobDB', FILENAME = N'F:\Data\DriverJobDB.mdf' , SIZE = 102400KB , MAXSIZE = UNLIMITED, FILEGROWTH = 102400KB )
 LOG ON 
( NAME = N'DriverJobDB_log', FILENAME = N'F:\Log\DriverJobDB_log.ldf' , SIZE = 256000KB , MAXSIZE = 2048GB , FILEGROWTH = 51200KB )
GO

ALTER DATABASE [DriverJobDB] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DriverJobDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DriverJobDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DriverJobDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DriverJobDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DriverJobDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DriverJobDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [DriverJobDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DriverJobDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DriverJobDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DriverJobDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DriverJobDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DriverJobDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DriverJobDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DriverJobDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DriverJobDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DriverJobDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DriverJobDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DriverJobDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DriverJobDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DriverJobDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DriverJobDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DriverJobDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DriverJobDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DriverJobDB] SET RECOVERY FULL 
GO

ALTER DATABASE [DriverJobDB] SET  MULTI_USER 
GO

ALTER DATABASE [DriverJobDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DriverJobDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DriverJobDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DriverJobDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DriverJobDB] SET  READ_WRITE 
GO


