ALTER LOGIN [SSRS_User] DISABLE
REVOKE CONNECT SQL TO [VIEJAS\IT_Apps] AS DBAdmin;
REVOKE CONNECT SQL TO [VIEJAS\ITappsSQLadmin] ;
REVOKE CONNECT SQL TO[VIEJAS\ITappsSQLadmin] as DBAdmin ;

REVOKE VIEW ANY DATABASE TO [public] as DBAdmin ;