/****** Script for SelectTopNRows command from SSMS  ******/
SELECT 
 [SPID]
,[TextData]
      --,[BinaryData]
      --,[DatabaseID]
      --,[TransactionID]
      --,[LineNumber]
      --,[NTUserName]
      --,[NTDomainName]
,[HostName]
      --,[ClientProcessID]
,[ApplicationName]
,[LoginName]
,[SPID]
,[Duration]
,DATEADD(HOUR,-8,[StartTime]) AS StartTime
,DATEADD(HOUR,-8,[EndTime]) AS EndTime
,[Reads]
,[Writes]
,[CPU]
      --,[Permissions]
      --,[Severity]
      ,[EventSubClass]
      --,[ObjectID]
      --,[Success]
      --,[IndexID]
      --,[IntegerData]
      --,[ServerName]
      ,[EventClass]
      --,[ObjectType]
      --,[NestLevel]
      --,[State]
      --,[Error]
      --,[Mode]
      --,[Handle]
,[ObjectName]
,[DatabaseName]
      --,[FileName]
      --,[OwnerName]
      --,[RoleName]
      --,[TargetUserName]
      --,[DBUserName]
      --,[LoginSid]
      --,[TargetLoginName]
      --,[TargetLoginSid]
      --,[ColumnPermissions]
,[LinkedServerName]
      --,[ProviderName]
      --,[MethodName]
,[RowCounts]
      --,[RequestID]
      --,[XactSequence]
      --,[EventSequence]
      --,[BigintData1]
      --,[BigintData2]
      --,[GUID]
      --,[IntegerData2]
      --,[ObjectID2]
      --,[Type]
      --,[OwnerID]
      --,[ParentName]
      --,[IsSystem]
      --,[Offset]
      --,[SourceDatabaseID]
      --,[SqlHandle]
      --,[SessionLoginName]
      --,[PlanHandle]
      --,[GroupID]
  FROM [DBA].[dbo].[temp_trc]

  WHERE [TextData] IS NOT NULL

  ORDER BY StartTime ASC
