--Listing 3: Create Filegroup FG
 
--USE [master]
--GO
--ALTER DATABASE [CMKTDB_ARCHIVE] ADD FILEGROUP [FG_tAwards]
--GO
 
--USE [master]
--GO
--ALTER DATABASE [CMKTDB_ARCHIVE] 
--ADD FILE ( NAME = N'CMKTDB_ARCHIVE_tAwards', FILENAME = N'F:\UserDBdata\CMKTDB_ARCHIVE_tAwards.ndf')
--TO FILEGROUP [FG_tAwards]
--GO

USE [CMKTDB_ARCHIVE]
GO
DROP INDEX [PK_tAwards] ON [dbo].[tAwards] WITH ( ONLINE = OFF )
GO
 
CREATE CLUSTERED INDEX [PK_tAwards] ON [dbo].[tAwards]
(
	[TranId] ASC,
	[GamingDt] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) 
ON [FG_tAwards]
GO



USE [CMKTDB_ARCHIVE]
GO

ALTER TABLE [dbo].[tAwards] DROP CONSTRAINT [PK_tAwards] WITH ( ONLINE = OFF ) -- 53 min
GO

ALTER TABLE [dbo].[tAwards] ADD  CONSTRAINT [PK_tAwards] PRIMARY KEY CLUSTERED 
(
	[TranId] ASC,
	[GamingDt] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
ON [FG_tAwards]
GO

