SELECT DISTINCT OWNER, OBJECT_NAME
FROM DBA_OBJECTS
WHERE OBJECT_TYPE = 'TABLE'
AND OWNER = '[some other schema]'


SELECT *
FROM OPENQUERY(OPERA, 'SELECT  table_name, owner FROM  dba_tables ORDER BY  owner, table_name')

SELECT *
FROM OPENQUERY(OPERA, 'SELECT  VIEW_NAME, OWNER FROM  DBA_VIEWS ORDER BY  OWNER, VIEW_NAME')