SELECT COUNT(*) AS MARKET_CODES_TEMPLATE_TABLE_ROWCOUNT
FROM [OPERA]..[OPERA].[MARKET_CODES_TEMPLATE]
GO
SELECT TOP 60 *
FROM [OPERA]..[OPERA].[MARKET_CODES_TEMPLATE]
ORDER BY UPDATE_DATE DESC
GO


SELECT COUNT(*) AS MARKET_GROUPS_TABLE_ROWCOUNT
FROM [OPERA]..[OPERA].[MARKET_GROUPS]
GO
SELECT TOP 60 *
FROM [OPERA]..[OPERA].[MARKET_GROUPS]
ORDER BY UPDATE_DATE DESC
GO


SELECT COUNT(*) AS MARKET_GROUPS_TEMPLATE_TABLE_ROWCOUNT
FROM [OPERA]..[OPERA].[MARKET_GROUPS_TEMPLATE]
GO
SELECT TOP 60 *
FROM [OPERA]..[OPERA].[MARKET_GROUPS_TEMPLATE]
ORDER BY UPDATE_DATE DESC
GO


SELECT COUNT(*) AS MARKET_STAT_DAILY_TABLE_ROWCOUNT
FROM [OPERA]..[OPERA].[MARKET_STAT_DAILY]
GO
SELECT TOP 60 *
FROM [OPERA]..[OPERA].[MARKET_STAT_DAILY]
ORDER BY BUSINESS_DATE DESC
GO



SELECT COUNT(*) AS ROOM_TABLE_ROWCOUNT
FROM [OPERA]..[OPERA].[ROOM]
GO
SELECT TOP 60 *
FROM [OPERA]..[OPERA].[ROOM]
ORDER BY UPDATE_DATE DESC
GO

SELECT COUNT(*) AS ROOM_CATEGORY_STATISTICS_ROWCOUNT
FROM [OPERA]..[OPERA].[ROOM_CATEGORY_STATISTICS]
GO
SELECT TOP 60 *
FROM [OPERA]..[OPERA].[ROOM_CATEGORY_STATISTICS]
ORDER BY BUSINESS_DATE DESC
GO

SELECT COUNT(*) AS ROOM_CATEGORY_TEMPLATE_TABLE_ROWCOUNT
FROM [OPERA]..[OPERA].[ROOM_CATEGORY_TEMPLATE]
GO
SELECT TOP 60 *
FROM [OPERA]..[OPERA].[ROOM_CATEGORY_TEMPLATE]
ORDER BY UPDATE_DATE DESC
GO

SELECT COUNT(*) AS ROOM_CLASSES_TEMPLATE_TABLE_ROWCOUNT
FROM [OPERA]..[OPERA].[ROOM_CLASSES_TEMPLATE]
GO
SELECT TOP 60 *
FROM [OPERA]..[OPERA].[ROOM_CLASSES_TEMPLATE]
ORDER BY INSERT_DATE DESC
GO



SELECT COUNT(*) AS RESERVATION_STAT_DAILY_TABLE_ROWCOUNT
FROM [OPERA]..[OPERA].[RESERVATION_STAT_DAILY]
GO
SELECT TOP 60 *
FROM [OPERA]..[OPERA].[RESERVATION_STAT_DAILY]
ORDER BY BUSINESS_DATE DESC
GO

SELECT COUNT(*) AS NAME_RESERVATION_VIEW_ROWCOUNT
FROM [OPERA]..[OPERA].NAME_RESERVATION
GO
SELECT TOP 60 *
FROM [OPERA]..[OPERA]. NAME_RESERVATION
ORDER BY BUSINESS_DATE DESC
GO

SELECT *
FROM OPENQUERY(OPERA, 'SELECT COUNT(*) AS NAME_RESERVATION_VIEW_ROWCOUNT FROM OPERA.NAME_RESERVATION')
GO

SELECT *
FROM OPENQUERY(OPERA, 'SELECT * FROM OPERA.NAME_RESERVATION WHERE RESV_NAME_ID <=(SELECT max(RESV_NAME_ID)+60 FROM OPERA.NAME_RESERVATION) ORDER BY RESV_NAME_ID DESC')
--FROM OPENQUERY(OPERA, 'SELECT * FROM (SELECT * FROM OPERA.NAME_RESERVATION ORDER BY ARRIVAL DESC) WHERE rownum <=60'
GO

--SELECT * FROM (SELECT *, UPDATE_DATE, ROW_NUMBER() OVER(PARTITION BY UPDATE_DATE ORDER BY UPDATE_DATE DESC) rn FROM OPERA.NAME_RESERVATION) WHERE rn=1 AND rownum<=60  --ORDER BY create_time desc