--USE Prod;
--GRANT SELECT ON OBJECT::lawson.GLTRANS TO [VIEJAS\ERevak];
--GO

GRANT CONNECT TO [VIEJAS\ERevak];

USE Prod;
GRANT SELECT ON OBJECT::lawson.GLTRANS TO [VIEJAS\llofstrom];
GO

GRANT CONNECT TO [VIEJAS\llofstrom];