/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [Tier_Type]
      ,[Requal_Month]
      ,[Qualification_Period_Start_Month]
      ,[Qualification_Period_End_Month]
      ,[Next_Requal_Date]
      ,[Next_Requal_Qualification_Period_Start_Date]
      ,[Next_Requal_Qualification_Period_End_Date]
      ,[Current_Requal_Date]
      ,[Current_Requal_Qualification_Period_Start_Date]
      ,[Current_Requal_Qualification_Period_End_Date]
  FROM [RequalDB].[dbo].[R_01_Next_Requal_Dates]

	SELECT TOP (1000) [Tier_Type]
      ,[Requal_Month]
      ,[Qualification_Period_Start_Month]
      ,[Qualification_Period_End_Month]
      ,[Next_Requal_Date]
      ,[Current_Requal_Qualification_Period_Start_Date]
      ,[Current_Requal_Qualification_Period_End_Date]
  FROM [RequalDB].[dbo].[R_temp_01_Next_Requal_Dates]