USE [master]
GO

/****** Object:  Database [RequalDB]    Script Date: 9/14/2020 2:36:52 PM ******/
DROP DATABASE [RequalDB]
GO

/****** Object:  Database [RequalDB]    Script Date: 9/14/2020 2:36:52 PM ******/
CREATE DATABASE [RequalDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RequalDB_data', FILENAME = N'C:\DatabaseFiles\RequalDB.mdf' , SIZE = 1515520KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'RequalDB_log', FILENAME = N'C:\DatabaseFiles\RequalDB_log.ldf' , SIZE = 2695168KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RequalDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RequalDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RequalDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RequalDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RequalDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RequalDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [RequalDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [RequalDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RequalDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RequalDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RequalDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RequalDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RequalDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RequalDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RequalDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RequalDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [RequalDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RequalDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RequalDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RequalDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RequalDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RequalDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RequalDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RequalDB] SET RECOVERY FULL 
GO

ALTER DATABASE [RequalDB] SET  MULTI_USER 
GO

ALTER DATABASE [RequalDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RequalDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [RequalDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [RequalDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [RequalDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [RequalDB] SET QUERY_STORE = OFF
GO

USE [RequalDB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [RequalDB] SET  READ_WRITE 
GO


