/****** Script for SelectTopNRows command from SSMS  ******/
SELECT 
  [Acct]
   , [PlayerID]
      ,[Requal_Month]
      ,[Current_Tier]
      ,[Current_Requal_Message_YN]

      ,[Current_Requal_Qualification_Period_Start_Date]
      ,[Current_Requal_Qualification_Period_End_Date]
      ,[Current_Requal_Valid_Through_Date]
      ,[Current_Requal_Tier]
      ,[Current_Requal_Upgrade_Tier]
      ,[Next_Requal_Qualification_Period_Start_Date]
      ,[Next_Requal_Play_Through_Date]
      ,[Next_Requal_Qualification_Period_End_Date]
      ,[Next_Requal_Date]
      ,[Next_Requal_Tier]
      ,[Next_Requal_Upgrade_Message_YN]
      ,[Next_Requal_Upgrade_Tier]
      ,[Points_To_Next_Requal_Upgrade_Tier]
      ,[Points_To_Next_Requal_Upgrade_Tier_Percentage]
      ,sum([Non-Poker_Base_Points])
      --,[Points_To_Current_Requal_Upgrade_Tier]
  FROM [RequalDB].[dbo].[Requal_15a_Data_Export]

    where PlayerID = '1426933'

group by
  [Acct]
,    [PlayerID]
      ,[Requal_Month]
     ,[Current_Tier]
      ,[Current_Requal_Message_YN]
      ,[Current_Requal_Qualification_Period_Start_Date]
      ,[Current_Requal_Qualification_Period_End_Date]
      ,[Current_Requal_Valid_Through_Date]
      ,[Current_Requal_Tier]
      ,[Current_Requal_Upgrade_Tier]
      ,[Next_Requal_Qualification_Period_Start_Date]
      ,[Next_Requal_Play_Through_Date]
      ,[Next_Requal_Qualification_Period_End_Date]
      ,[Next_Requal_Date]
      ,[Next_Requal_Tier]
      ,[Next_Requal_Upgrade_Message_YN]
      ,[Next_Requal_Upgrade_Tier]
      ,[Points_To_Next_Requal_Upgrade_Tier]
      ,[Points_To_Next_Requal_Upgrade_Tier_Percentage]

order by 
  [Acct]
,    [PlayerID]
      ,[Requal_Month]
     ,[Current_Tier]
      ,[Current_Requal_Message_YN]
      ,[Current_Requal_Qualification_Period_Start_Date]
--      ,[Current_Requal_Qualification_Period_End_Date]
--      ,[Current_Requal_Valid_Through_Date]
--      ,[Current_Requal_Tier]
--      ,[Current_Requal_Upgrade_Tier]
--      ,[Next_Requal_Qualification_Period_Start_Date]
--      ,[Next_Requal_Play_Through_Date]
--      ,[Next_Requal_Qualification_Period_End_Date]
--      ,[Next_Requal_Date]
--      ,[Next_Requal_Tier]
--      ,[Next_Requal_Upgrade_Message_YN]
--      ,[Next_Requal_Upgrade_Tier]
--      ,[Points_To_Next_Requal_Upgrade_Tier]
--      ,[Points_To_Next_Requal_Upgrade_Tier_Percentage]